// Code generated by gen-test-suites. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: testing/cases/api/v1/notebook_service/cases.proto

package notebookservicecasesv1

import (
	v11 "github.com/at-ishikawa/langner/gen-protos/api/v1"
	v1 "github.com/at-ishikawa/langner/testrunner/gen-protos/testing/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotebookDetailTestSuite struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Cases         []*GetNotebookDetailTestCase `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotebookDetailTestSuite) Reset() {
	*x = GetNotebookDetailTestSuite{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailTestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailTestSuite) ProtoMessage() {}

func (x *GetNotebookDetailTestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailTestSuite.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailTestSuite) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotebookDetailTestSuite) GetCases() []*GetNotebookDetailTestCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

type GetNotebookDetailTestCase struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Name          string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         []*v1.SetupStep               `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`
	Request       *v11.GetNotebookDetailRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Expected      *GetNotebookDetailExpected    `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Vars          map[string]string             `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotebookDetailTestCase) Reset() {
	*x = GetNotebookDetailTestCase{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailTestCase) ProtoMessage() {}

func (x *GetNotebookDetailTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailTestCase.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailTestCase) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{1}
}

func (x *GetNotebookDetailTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNotebookDetailTestCase) GetSetup() []*v1.SetupStep {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *GetNotebookDetailTestCase) GetRequest() *v11.GetNotebookDetailRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetNotebookDetailTestCase) GetExpected() *GetNotebookDetailExpected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *GetNotebookDetailTestCase) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type GetNotebookDetailExpected struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	Status            uint32                         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body              *v11.GetNotebookDetailResponse `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Error             *v1.ExpectedError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FieldExpectations []*v1.FieldExpectation         `protobuf:"bytes,4,rep,name=field_expectations,json=fieldExpectations,proto3" json:"field_expectations,omitempty"`
	State             []*v1.StateAssertion           `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetNotebookDetailExpected) Reset() {
	*x = GetNotebookDetailExpected{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailExpected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailExpected) ProtoMessage() {}

func (x *GetNotebookDetailExpected) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailExpected.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailExpected) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{2}
}

func (x *GetNotebookDetailExpected) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetNotebookDetailExpected) GetBody() *v11.GetNotebookDetailResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetNotebookDetailExpected) GetError() *v1.ExpectedError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetNotebookDetailExpected) GetFieldExpectations() []*v1.FieldExpectation {
	if x != nil {
		return x.FieldExpectations
	}
	return nil
}

func (x *GetNotebookDetailExpected) GetState() []*v1.StateAssertion {
	if x != nil {
		return x.State
	}
	return nil
}

type ExportNotebookPDFTestSuite struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Cases         []*ExportNotebookPDFTestCase `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNotebookPDFTestSuite) Reset() {
	*x = ExportNotebookPDFTestSuite{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFTestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFTestSuite) ProtoMessage() {}

func (x *ExportNotebookPDFTestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFTestSuite.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFTestSuite) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{3}
}

func (x *ExportNotebookPDFTestSuite) GetCases() []*ExportNotebookPDFTestCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

type ExportNotebookPDFTestCase struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Name          string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         []*v1.SetupStep               `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`
	Request       *v11.ExportNotebookPDFRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Expected      *ExportNotebookPDFExpected    `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Vars          map[string]string             `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNotebookPDFTestCase) Reset() {
	*x = ExportNotebookPDFTestCase{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFTestCase) ProtoMessage() {}

func (x *ExportNotebookPDFTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFTestCase.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFTestCase) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{4}
}

func (x *ExportNotebookPDFTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportNotebookPDFTestCase) GetSetup() []*v1.SetupStep {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *ExportNotebookPDFTestCase) GetRequest() *v11.ExportNotebookPDFRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExportNotebookPDFTestCase) GetExpected() *ExportNotebookPDFExpected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *ExportNotebookPDFTestCase) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type ExportNotebookPDFExpected struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	Status            uint32                         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body              *v11.ExportNotebookPDFResponse `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Error             *v1.ExpectedError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FieldExpectations []*v1.FieldExpectation         `protobuf:"bytes,4,rep,name=field_expectations,json=fieldExpectations,proto3" json:"field_expectations,omitempty"`
	State             []*v1.StateAssertion           `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExportNotebookPDFExpected) Reset() {
	*x = ExportNotebookPDFExpected{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFExpected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFExpected) ProtoMessage() {}

func (x *ExportNotebookPDFExpected) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFExpected.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFExpected) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{5}
}

func (x *ExportNotebookPDFExpected) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExportNotebookPDFExpected) GetBody() *v11.ExportNotebookPDFResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ExportNotebookPDFExpected) GetError() *v1.ExpectedError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExportNotebookPDFExpected) GetFieldExpectations() []*v1.FieldExpectation {
	if x != nil {
		return x.FieldExpectations
	}
	return nil
}

func (x *ExportNotebookPDFExpected) GetState() []*v1.StateAssertion {
	if x != nil {
		return x.State
	}
	return nil
}

type LookupWordTestSuite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cases         []*LookupWordTestCase  `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupWordTestSuite) Reset() {
	*x = LookupWordTestSuite{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWordTestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWordTestSuite) ProtoMessage() {}

func (x *LookupWordTestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWordTestSuite.ProtoReflect.Descriptor instead.
func (*LookupWordTestSuite) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{6}
}

func (x *LookupWordTestSuite) GetCases() []*LookupWordTestCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

type LookupWordTestCase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         []*v1.SetupStep        `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`
	Request       *v11.LookupWordRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Expected      *LookupWordExpected    `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupWordTestCase) Reset() {
	*x = LookupWordTestCase{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWordTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWordTestCase) ProtoMessage() {}

func (x *LookupWordTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWordTestCase.ProtoReflect.Descriptor instead.
func (*LookupWordTestCase) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{7}
}

func (x *LookupWordTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LookupWordTestCase) GetSetup() []*v1.SetupStep {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *LookupWordTestCase) GetRequest() *v11.LookupWordRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *LookupWordTestCase) GetExpected() *LookupWordExpected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *LookupWordTestCase) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type LookupWordExpected struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Status            uint32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body              *v11.LookupWordResponse `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Error             *v1.ExpectedError       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FieldExpectations []*v1.FieldExpectation  `protobuf:"bytes,4,rep,name=field_expectations,json=fieldExpectations,proto3" json:"field_expectations,omitempty"`
	State             []*v1.StateAssertion    `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LookupWordExpected) Reset() {
	*x = LookupWordExpected{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWordExpected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWordExpected) ProtoMessage() {}

func (x *LookupWordExpected) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWordExpected.ProtoReflect.Descriptor instead.
func (*LookupWordExpected) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{8}
}

func (x *LookupWordExpected) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LookupWordExpected) GetBody() *v11.LookupWordResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LookupWordExpected) GetError() *v1.ExpectedError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *LookupWordExpected) GetFieldExpectations() []*v1.FieldExpectation {
	if x != nil {
		return x.FieldExpectations
	}
	return nil
}

func (x *LookupWordExpected) GetState() []*v1.StateAssertion {
	if x != nil {
		return x.State
	}
	return nil
}

type RegisterDefinitionTestSuite struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Cases         []*RegisterDefinitionTestCase `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDefinitionTestSuite) Reset() {
	*x = RegisterDefinitionTestSuite{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDefinitionTestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDefinitionTestSuite) ProtoMessage() {}

func (x *RegisterDefinitionTestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDefinitionTestSuite.ProtoReflect.Descriptor instead.
func (*RegisterDefinitionTestSuite) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterDefinitionTestSuite) GetCases() []*RegisterDefinitionTestCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

type RegisterDefinitionTestCase struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Name          string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         []*v1.SetupStep                `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`
	Request       *v11.RegisterDefinitionRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Expected      *RegisterDefinitionExpected    `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Vars          map[string]string              `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDefinitionTestCase) Reset() {
	*x = RegisterDefinitionTestCase{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDefinitionTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDefinitionTestCase) ProtoMessage() {}

func (x *RegisterDefinitionTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDefinitionTestCase.ProtoReflect.Descriptor instead.
func (*RegisterDefinitionTestCase) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterDefinitionTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterDefinitionTestCase) GetSetup() []*v1.SetupStep {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *RegisterDefinitionTestCase) GetRequest() *v11.RegisterDefinitionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RegisterDefinitionTestCase) GetExpected() *RegisterDefinitionExpected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *RegisterDefinitionTestCase) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type RegisterDefinitionExpected struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	Status            uint32                          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body              *v11.RegisterDefinitionResponse `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Error             *v1.ExpectedError               `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FieldExpectations []*v1.FieldExpectation          `protobuf:"bytes,4,rep,name=field_expectations,json=fieldExpectations,proto3" json:"field_expectations,omitempty"`
	State             []*v1.StateAssertion            `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterDefinitionExpected) Reset() {
	*x = RegisterDefinitionExpected{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDefinitionExpected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDefinitionExpected) ProtoMessage() {}

func (x *RegisterDefinitionExpected) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDefinitionExpected.ProtoReflect.Descriptor instead.
func (*RegisterDefinitionExpected) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterDefinitionExpected) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RegisterDefinitionExpected) GetBody() *v11.RegisterDefinitionResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RegisterDefinitionExpected) GetError() *v1.ExpectedError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RegisterDefinitionExpected) GetFieldExpectations() []*v1.FieldExpectation {
	if x != nil {
		return x.FieldExpectations
	}
	return nil
}

func (x *RegisterDefinitionExpected) GetState() []*v1.StateAssertion {
	if x != nil {
		return x.State
	}
	return nil
}

type DeleteDefinitionTestSuite struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Cases         []*DeleteDefinitionTestCase `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionTestSuite) Reset() {
	*x = DeleteDefinitionTestSuite{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionTestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionTestSuite) ProtoMessage() {}

func (x *DeleteDefinitionTestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionTestSuite.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionTestSuite) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDefinitionTestSuite) GetCases() []*DeleteDefinitionTestCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

type DeleteDefinitionTestCase struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Name          string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         []*v1.SetupStep              `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`
	Request       *v11.DeleteDefinitionRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Expected      *DeleteDefinitionExpected    `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Vars          map[string]string            `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionTestCase) Reset() {
	*x = DeleteDefinitionTestCase{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionTestCase) ProtoMessage() {}

func (x *DeleteDefinitionTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionTestCase.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionTestCase) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDefinitionTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDefinitionTestCase) GetSetup() []*v1.SetupStep {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *DeleteDefinitionTestCase) GetRequest() *v11.DeleteDefinitionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *DeleteDefinitionTestCase) GetExpected() *DeleteDefinitionExpected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *DeleteDefinitionTestCase) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type DeleteDefinitionExpected struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	Status            uint32                        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body              *v11.DeleteDefinitionResponse `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Error             *v1.ExpectedError             `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FieldExpectations []*v1.FieldExpectation        `protobuf:"bytes,4,rep,name=field_expectations,json=fieldExpectations,proto3" json:"field_expectations,omitempty"`
	State             []*v1.StateAssertion          `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteDefinitionExpected) Reset() {
	*x = DeleteDefinitionExpected{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionExpected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionExpected) ProtoMessage() {}

func (x *DeleteDefinitionExpected) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionExpected.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionExpected) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDefinitionExpected) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteDefinitionExpected) GetBody() *v11.DeleteDefinitionResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DeleteDefinitionExpected) GetError() *v1.ExpectedError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DeleteDefinitionExpected) GetFieldExpectations() []*v1.FieldExpectation {
	if x != nil {
		return x.FieldExpectations
	}
	return nil
}

func (x *DeleteDefinitionExpected) GetState() []*v1.StateAssertion {
	if x != nil {
		return x.State
	}
	return nil
}

type GetEtymologyNotebookTestSuite struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Cases         []*GetEtymologyNotebookTestCase `protobuf:"bytes,1,rep,name=cases,proto3" json:"cases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtymologyNotebookTestSuite) Reset() {
	*x = GetEtymologyNotebookTestSuite{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtymologyNotebookTestSuite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtymologyNotebookTestSuite) ProtoMessage() {}

func (x *GetEtymologyNotebookTestSuite) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtymologyNotebookTestSuite.ProtoReflect.Descriptor instead.
func (*GetEtymologyNotebookTestSuite) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{15}
}

func (x *GetEtymologyNotebookTestSuite) GetCases() []*GetEtymologyNotebookTestCase {
	if x != nil {
		return x.Cases
	}
	return nil
}

type GetEtymologyNotebookTestCase struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Name          string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         []*v1.SetupStep                  `protobuf:"bytes,2,rep,name=setup,proto3" json:"setup,omitempty"`
	Request       *v11.GetEtymologyNotebookRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Expected      *GetEtymologyNotebookExpected    `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	Vars          map[string]string                `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtymologyNotebookTestCase) Reset() {
	*x = GetEtymologyNotebookTestCase{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtymologyNotebookTestCase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtymologyNotebookTestCase) ProtoMessage() {}

func (x *GetEtymologyNotebookTestCase) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtymologyNotebookTestCase.ProtoReflect.Descriptor instead.
func (*GetEtymologyNotebookTestCase) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{16}
}

func (x *GetEtymologyNotebookTestCase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEtymologyNotebookTestCase) GetSetup() []*v1.SetupStep {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *GetEtymologyNotebookTestCase) GetRequest() *v11.GetEtymologyNotebookRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetEtymologyNotebookTestCase) GetExpected() *GetEtymologyNotebookExpected {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *GetEtymologyNotebookTestCase) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type GetEtymologyNotebookExpected struct {
	state             protoimpl.MessageState            `protogen:"open.v1"`
	Status            uint32                            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body              *v11.GetEtymologyNotebookResponse `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Error             *v1.ExpectedError                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	FieldExpectations []*v1.FieldExpectation            `protobuf:"bytes,4,rep,name=field_expectations,json=fieldExpectations,proto3" json:"field_expectations,omitempty"`
	State             []*v1.StateAssertion              `protobuf:"bytes,5,rep,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetEtymologyNotebookExpected) Reset() {
	*x = GetEtymologyNotebookExpected{}
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtymologyNotebookExpected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtymologyNotebookExpected) ProtoMessage() {}

func (x *GetEtymologyNotebookExpected) ProtoReflect() protoreflect.Message {
	mi := &file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtymologyNotebookExpected.ProtoReflect.Descriptor instead.
func (*GetEtymologyNotebookExpected) Descriptor() ([]byte, []int) {
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP(), []int{17}
}

func (x *GetEtymologyNotebookExpected) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetEtymologyNotebookExpected) GetBody() *v11.GetEtymologyNotebookResponse {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetEtymologyNotebookExpected) GetError() *v1.ExpectedError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetEtymologyNotebookExpected) GetFieldExpectations() []*v1.FieldExpectation {
	if x != nil {
		return x.FieldExpectations
	}
	return nil
}

func (x *GetEtymologyNotebookExpected) GetState() []*v1.StateAssertion {
	if x != nil {
		return x.State
	}
	return nil
}

var File_testing_cases_api_v1_notebook_service_cases_proto protoreflect.FileDescriptor

const file_testing_cases_api_v1_notebook_service_cases_proto_rawDesc = "" +
	"\n" +
	"1testing/cases/api/v1/notebook_service/cases.proto\x12%testing.cases.api.v1.notebook_service\x1a\x15api/v1/notebook.proto\x1a\x1atesting/v1/test_case.proto\"t\n" +
	"\x1aGetNotebookDetailTestSuite\x12V\n" +
	"\x05cases\x18\x01 \x03(\v2@.testing.cases.api.v1.notebook_service.GetNotebookDetailTestCaseR\x05cases\"\x8f\x03\n" +
	"\x19GetNotebookDetailTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05setup\x18\x02 \x03(\v2\x15.testing.v1.SetupStepR\x05setup\x12:\n" +
	"\arequest\x18\x03 \x01(\v2 .api.v1.GetNotebookDetailRequestR\arequest\x12\\\n" +
	"\bexpected\x18\x04 \x01(\v2@.testing.cases.api.v1.notebook_service.GetNotebookDetailExpectedR\bexpected\x12^\n" +
	"\x04vars\x18\x05 \x03(\v2J.testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\x19GetNotebookDetailExpected\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x125\n" +
	"\x04body\x18\x02 \x01(\v2!.api.v1.GetNotebookDetailResponseR\x04body\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.testing.v1.ExpectedErrorR\x05error\x12K\n" +
	"\x12field_expectations\x18\x04 \x03(\v2\x1c.testing.v1.FieldExpectationR\x11fieldExpectations\x120\n" +
	"\x05state\x18\x05 \x03(\v2\x1a.testing.v1.StateAssertionR\x05state\"t\n" +
	"\x1aExportNotebookPDFTestSuite\x12V\n" +
	"\x05cases\x18\x01 \x03(\v2@.testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCaseR\x05cases\"\x8f\x03\n" +
	"\x19ExportNotebookPDFTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05setup\x18\x02 \x03(\v2\x15.testing.v1.SetupStepR\x05setup\x12:\n" +
	"\arequest\x18\x03 \x01(\v2 .api.v1.ExportNotebookPDFRequestR\arequest\x12\\\n" +
	"\bexpected\x18\x04 \x01(\v2@.testing.cases.api.v1.notebook_service.ExportNotebookPDFExpectedR\bexpected\x12^\n" +
	"\x04vars\x18\x05 \x03(\v2J.testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\x19ExportNotebookPDFExpected\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x125\n" +
	"\x04body\x18\x02 \x01(\v2!.api.v1.ExportNotebookPDFResponseR\x04body\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.testing.v1.ExpectedErrorR\x05error\x12K\n" +
	"\x12field_expectations\x18\x04 \x03(\v2\x1c.testing.v1.FieldExpectationR\x11fieldExpectations\x120\n" +
	"\x05state\x18\x05 \x03(\v2\x1a.testing.v1.StateAssertionR\x05state\"f\n" +
	"\x13LookupWordTestSuite\x12O\n" +
	"\x05cases\x18\x01 \x03(\v29.testing.cases.api.v1.notebook_service.LookupWordTestCaseR\x05cases\"\xf3\x02\n" +
	"\x12LookupWordTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05setup\x18\x02 \x03(\v2\x15.testing.v1.SetupStepR\x05setup\x123\n" +
	"\arequest\x18\x03 \x01(\v2\x19.api.v1.LookupWordRequestR\arequest\x12U\n" +
	"\bexpected\x18\x04 \x01(\v29.testing.cases.api.v1.notebook_service.LookupWordExpectedR\bexpected\x12W\n" +
	"\x04vars\x18\x05 \x03(\v2C.testing.cases.api.v1.notebook_service.LookupWordTestCase.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x12LookupWordExpected\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12.\n" +
	"\x04body\x18\x02 \x01(\v2\x1a.api.v1.LookupWordResponseR\x04body\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.testing.v1.ExpectedErrorR\x05error\x12K\n" +
	"\x12field_expectations\x18\x04 \x03(\v2\x1c.testing.v1.FieldExpectationR\x11fieldExpectations\x120\n" +
	"\x05state\x18\x05 \x03(\v2\x1a.testing.v1.StateAssertionR\x05state\"v\n" +
	"\x1bRegisterDefinitionTestSuite\x12W\n" +
	"\x05cases\x18\x01 \x03(\v2A.testing.cases.api.v1.notebook_service.RegisterDefinitionTestCaseR\x05cases\"\x93\x03\n" +
	"\x1aRegisterDefinitionTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05setup\x18\x02 \x03(\v2\x15.testing.v1.SetupStepR\x05setup\x12;\n" +
	"\arequest\x18\x03 \x01(\v2!.api.v1.RegisterDefinitionRequestR\arequest\x12]\n" +
	"\bexpected\x18\x04 \x01(\v2A.testing.cases.api.v1.notebook_service.RegisterDefinitionExpectedR\bexpected\x12_\n" +
	"\x04vars\x18\x05 \x03(\v2K.testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\x1aRegisterDefinitionExpected\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x126\n" +
	"\x04body\x18\x02 \x01(\v2\".api.v1.RegisterDefinitionResponseR\x04body\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.testing.v1.ExpectedErrorR\x05error\x12K\n" +
	"\x12field_expectations\x18\x04 \x03(\v2\x1c.testing.v1.FieldExpectationR\x11fieldExpectations\x120\n" +
	"\x05state\x18\x05 \x03(\v2\x1a.testing.v1.StateAssertionR\x05state\"r\n" +
	"\x19DeleteDefinitionTestSuite\x12U\n" +
	"\x05cases\x18\x01 \x03(\v2?.testing.cases.api.v1.notebook_service.DeleteDefinitionTestCaseR\x05cases\"\x8b\x03\n" +
	"\x18DeleteDefinitionTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05setup\x18\x02 \x03(\v2\x15.testing.v1.SetupStepR\x05setup\x129\n" +
	"\arequest\x18\x03 \x01(\v2\x1f.api.v1.DeleteDefinitionRequestR\arequest\x12[\n" +
	"\bexpected\x18\x04 \x01(\v2?.testing.cases.api.v1.notebook_service.DeleteDefinitionExpectedR\bexpected\x12]\n" +
	"\x04vars\x18\x05 \x03(\v2I.testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\x18DeleteDefinitionExpected\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x124\n" +
	"\x04body\x18\x02 \x01(\v2 .api.v1.DeleteDefinitionResponseR\x04body\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.testing.v1.ExpectedErrorR\x05error\x12K\n" +
	"\x12field_expectations\x18\x04 \x03(\v2\x1c.testing.v1.FieldExpectationR\x11fieldExpectations\x120\n" +
	"\x05state\x18\x05 \x03(\v2\x1a.testing.v1.StateAssertionR\x05state\"z\n" +
	"\x1dGetEtymologyNotebookTestSuite\x12Y\n" +
	"\x05cases\x18\x01 \x03(\v2C.testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCaseR\x05cases\"\x9b\x03\n" +
	"\x1cGetEtymologyNotebookTestCase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05setup\x18\x02 \x03(\v2\x15.testing.v1.SetupStepR\x05setup\x12=\n" +
	"\arequest\x18\x03 \x01(\v2#.api.v1.GetEtymologyNotebookRequestR\arequest\x12_\n" +
	"\bexpected\x18\x04 \x01(\v2C.testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpectedR\bexpected\x12a\n" +
	"\x04vars\x18\x05 \x03(\v2M.testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\x1cGetEtymologyNotebookExpected\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x128\n" +
	"\x04body\x18\x02 \x01(\v2$.api.v1.GetEtymologyNotebookResponseR\x04body\x12/\n" +
	"\x05error\x18\x03 \x01(\v2\x19.testing.v1.ExpectedErrorR\x05error\x12K\n" +
	"\x12field_expectations\x18\x04 \x03(\v2\x1c.testing.v1.FieldExpectationR\x11fieldExpectations\x120\n" +
	"\x05state\x18\x05 \x03(\v2\x1a.testing.v1.StateAssertionR\x05stateBhZfgithub.com/at-ishikawa/langner/gen-protos/testing/cases/api/v1/notebook_service;notebookservicecasesv1b\x06proto3"

var (
	file_testing_cases_api_v1_notebook_service_cases_proto_rawDescOnce sync.Once
	file_testing_cases_api_v1_notebook_service_cases_proto_rawDescData []byte
)

func file_testing_cases_api_v1_notebook_service_cases_proto_rawDescGZIP() []byte {
	file_testing_cases_api_v1_notebook_service_cases_proto_rawDescOnce.Do(func() {
		file_testing_cases_api_v1_notebook_service_cases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testing_cases_api_v1_notebook_service_cases_proto_rawDesc), len(file_testing_cases_api_v1_notebook_service_cases_proto_rawDesc)))
	})
	return file_testing_cases_api_v1_notebook_service_cases_proto_rawDescData
}

var file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_testing_cases_api_v1_notebook_service_cases_proto_goTypes = []any{
	(*GetNotebookDetailTestSuite)(nil),       // 0: testing.cases.api.v1.notebook_service.GetNotebookDetailTestSuite
	(*GetNotebookDetailTestCase)(nil),        // 1: testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase
	(*GetNotebookDetailExpected)(nil),        // 2: testing.cases.api.v1.notebook_service.GetNotebookDetailExpected
	(*ExportNotebookPDFTestSuite)(nil),       // 3: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestSuite
	(*ExportNotebookPDFTestCase)(nil),        // 4: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase
	(*ExportNotebookPDFExpected)(nil),        // 5: testing.cases.api.v1.notebook_service.ExportNotebookPDFExpected
	(*LookupWordTestSuite)(nil),              // 6: testing.cases.api.v1.notebook_service.LookupWordTestSuite
	(*LookupWordTestCase)(nil),               // 7: testing.cases.api.v1.notebook_service.LookupWordTestCase
	(*LookupWordExpected)(nil),               // 8: testing.cases.api.v1.notebook_service.LookupWordExpected
	(*RegisterDefinitionTestSuite)(nil),      // 9: testing.cases.api.v1.notebook_service.RegisterDefinitionTestSuite
	(*RegisterDefinitionTestCase)(nil),       // 10: testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase
	(*RegisterDefinitionExpected)(nil),       // 11: testing.cases.api.v1.notebook_service.RegisterDefinitionExpected
	(*DeleteDefinitionTestSuite)(nil),        // 12: testing.cases.api.v1.notebook_service.DeleteDefinitionTestSuite
	(*DeleteDefinitionTestCase)(nil),         // 13: testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase
	(*DeleteDefinitionExpected)(nil),         // 14: testing.cases.api.v1.notebook_service.DeleteDefinitionExpected
	(*GetEtymologyNotebookTestSuite)(nil),    // 15: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestSuite
	(*GetEtymologyNotebookTestCase)(nil),     // 16: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase
	(*GetEtymologyNotebookExpected)(nil),     // 17: testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpected
	nil,                                      // 18: testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.VarsEntry
	nil,                                      // 19: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.VarsEntry
	nil,                                      // 20: testing.cases.api.v1.notebook_service.LookupWordTestCase.VarsEntry
	nil,                                      // 21: testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.VarsEntry
	nil,                                      // 22: testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.VarsEntry
	nil,                                      // 23: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.VarsEntry
	(*v1.SetupStep)(nil),                     // 24: testing.v1.SetupStep
	(*v11.GetNotebookDetailRequest)(nil),     // 25: api.v1.GetNotebookDetailRequest
	(*v11.GetNotebookDetailResponse)(nil),    // 26: api.v1.GetNotebookDetailResponse
	(*v1.ExpectedError)(nil),                 // 27: testing.v1.ExpectedError
	(*v1.FieldExpectation)(nil),              // 28: testing.v1.FieldExpectation
	(*v1.StateAssertion)(nil),                // 29: testing.v1.StateAssertion
	(*v11.ExportNotebookPDFRequest)(nil),     // 30: api.v1.ExportNotebookPDFRequest
	(*v11.ExportNotebookPDFResponse)(nil),    // 31: api.v1.ExportNotebookPDFResponse
	(*v11.LookupWordRequest)(nil),            // 32: api.v1.LookupWordRequest
	(*v11.LookupWordResponse)(nil),           // 33: api.v1.LookupWordResponse
	(*v11.RegisterDefinitionRequest)(nil),    // 34: api.v1.RegisterDefinitionRequest
	(*v11.RegisterDefinitionResponse)(nil),   // 35: api.v1.RegisterDefinitionResponse
	(*v11.DeleteDefinitionRequest)(nil),      // 36: api.v1.DeleteDefinitionRequest
	(*v11.DeleteDefinitionResponse)(nil),     // 37: api.v1.DeleteDefinitionResponse
	(*v11.GetEtymologyNotebookRequest)(nil),  // 38: api.v1.GetEtymologyNotebookRequest
	(*v11.GetEtymologyNotebookResponse)(nil), // 39: api.v1.GetEtymologyNotebookResponse
}
var file_testing_cases_api_v1_notebook_service_cases_proto_depIdxs = []int32{
	1,  // 0: testing.cases.api.v1.notebook_service.GetNotebookDetailTestSuite.cases:type_name -> testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase
	24, // 1: testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.setup:type_name -> testing.v1.SetupStep
	25, // 2: testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.request:type_name -> api.v1.GetNotebookDetailRequest
	2,  // 3: testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.expected:type_name -> testing.cases.api.v1.notebook_service.GetNotebookDetailExpected
	18, // 4: testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.vars:type_name -> testing.cases.api.v1.notebook_service.GetNotebookDetailTestCase.VarsEntry
	26, // 5: testing.cases.api.v1.notebook_service.GetNotebookDetailExpected.body:type_name -> api.v1.GetNotebookDetailResponse
	27, // 6: testing.cases.api.v1.notebook_service.GetNotebookDetailExpected.error:type_name -> testing.v1.ExpectedError
	28, // 7: testing.cases.api.v1.notebook_service.GetNotebookDetailExpected.field_expectations:type_name -> testing.v1.FieldExpectation
	29, // 8: testing.cases.api.v1.notebook_service.GetNotebookDetailExpected.state:type_name -> testing.v1.StateAssertion
	4,  // 9: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestSuite.cases:type_name -> testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase
	24, // 10: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.setup:type_name -> testing.v1.SetupStep
	30, // 11: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.request:type_name -> api.v1.ExportNotebookPDFRequest
	5,  // 12: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.expected:type_name -> testing.cases.api.v1.notebook_service.ExportNotebookPDFExpected
	19, // 13: testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.vars:type_name -> testing.cases.api.v1.notebook_service.ExportNotebookPDFTestCase.VarsEntry
	31, // 14: testing.cases.api.v1.notebook_service.ExportNotebookPDFExpected.body:type_name -> api.v1.ExportNotebookPDFResponse
	27, // 15: testing.cases.api.v1.notebook_service.ExportNotebookPDFExpected.error:type_name -> testing.v1.ExpectedError
	28, // 16: testing.cases.api.v1.notebook_service.ExportNotebookPDFExpected.field_expectations:type_name -> testing.v1.FieldExpectation
	29, // 17: testing.cases.api.v1.notebook_service.ExportNotebookPDFExpected.state:type_name -> testing.v1.StateAssertion
	7,  // 18: testing.cases.api.v1.notebook_service.LookupWordTestSuite.cases:type_name -> testing.cases.api.v1.notebook_service.LookupWordTestCase
	24, // 19: testing.cases.api.v1.notebook_service.LookupWordTestCase.setup:type_name -> testing.v1.SetupStep
	32, // 20: testing.cases.api.v1.notebook_service.LookupWordTestCase.request:type_name -> api.v1.LookupWordRequest
	8,  // 21: testing.cases.api.v1.notebook_service.LookupWordTestCase.expected:type_name -> testing.cases.api.v1.notebook_service.LookupWordExpected
	20, // 22: testing.cases.api.v1.notebook_service.LookupWordTestCase.vars:type_name -> testing.cases.api.v1.notebook_service.LookupWordTestCase.VarsEntry
	33, // 23: testing.cases.api.v1.notebook_service.LookupWordExpected.body:type_name -> api.v1.LookupWordResponse
	27, // 24: testing.cases.api.v1.notebook_service.LookupWordExpected.error:type_name -> testing.v1.ExpectedError
	28, // 25: testing.cases.api.v1.notebook_service.LookupWordExpected.field_expectations:type_name -> testing.v1.FieldExpectation
	29, // 26: testing.cases.api.v1.notebook_service.LookupWordExpected.state:type_name -> testing.v1.StateAssertion
	10, // 27: testing.cases.api.v1.notebook_service.RegisterDefinitionTestSuite.cases:type_name -> testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase
	24, // 28: testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.setup:type_name -> testing.v1.SetupStep
	34, // 29: testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.request:type_name -> api.v1.RegisterDefinitionRequest
	11, // 30: testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.expected:type_name -> testing.cases.api.v1.notebook_service.RegisterDefinitionExpected
	21, // 31: testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.vars:type_name -> testing.cases.api.v1.notebook_service.RegisterDefinitionTestCase.VarsEntry
	35, // 32: testing.cases.api.v1.notebook_service.RegisterDefinitionExpected.body:type_name -> api.v1.RegisterDefinitionResponse
	27, // 33: testing.cases.api.v1.notebook_service.RegisterDefinitionExpected.error:type_name -> testing.v1.ExpectedError
	28, // 34: testing.cases.api.v1.notebook_service.RegisterDefinitionExpected.field_expectations:type_name -> testing.v1.FieldExpectation
	29, // 35: testing.cases.api.v1.notebook_service.RegisterDefinitionExpected.state:type_name -> testing.v1.StateAssertion
	13, // 36: testing.cases.api.v1.notebook_service.DeleteDefinitionTestSuite.cases:type_name -> testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase
	24, // 37: testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.setup:type_name -> testing.v1.SetupStep
	36, // 38: testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.request:type_name -> api.v1.DeleteDefinitionRequest
	14, // 39: testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.expected:type_name -> testing.cases.api.v1.notebook_service.DeleteDefinitionExpected
	22, // 40: testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.vars:type_name -> testing.cases.api.v1.notebook_service.DeleteDefinitionTestCase.VarsEntry
	37, // 41: testing.cases.api.v1.notebook_service.DeleteDefinitionExpected.body:type_name -> api.v1.DeleteDefinitionResponse
	27, // 42: testing.cases.api.v1.notebook_service.DeleteDefinitionExpected.error:type_name -> testing.v1.ExpectedError
	28, // 43: testing.cases.api.v1.notebook_service.DeleteDefinitionExpected.field_expectations:type_name -> testing.v1.FieldExpectation
	29, // 44: testing.cases.api.v1.notebook_service.DeleteDefinitionExpected.state:type_name -> testing.v1.StateAssertion
	16, // 45: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestSuite.cases:type_name -> testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase
	24, // 46: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.setup:type_name -> testing.v1.SetupStep
	38, // 47: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.request:type_name -> api.v1.GetEtymologyNotebookRequest
	17, // 48: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.expected:type_name -> testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpected
	23, // 49: testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.vars:type_name -> testing.cases.api.v1.notebook_service.GetEtymologyNotebookTestCase.VarsEntry
	39, // 50: testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpected.body:type_name -> api.v1.GetEtymologyNotebookResponse
	27, // 51: testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpected.error:type_name -> testing.v1.ExpectedError
	28, // 52: testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpected.field_expectations:type_name -> testing.v1.FieldExpectation
	29, // 53: testing.cases.api.v1.notebook_service.GetEtymologyNotebookExpected.state:type_name -> testing.v1.StateAssertion
	54, // [54:54] is the sub-list for method output_type
	54, // [54:54] is the sub-list for method input_type
	54, // [54:54] is the sub-list for extension type_name
	54, // [54:54] is the sub-list for extension extendee
	0,  // [0:54] is the sub-list for field type_name
}

func init() { file_testing_cases_api_v1_notebook_service_cases_proto_init() }
func file_testing_cases_api_v1_notebook_service_cases_proto_init() {
	if File_testing_cases_api_v1_notebook_service_cases_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testing_cases_api_v1_notebook_service_cases_proto_rawDesc), len(file_testing_cases_api_v1_notebook_service_cases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testing_cases_api_v1_notebook_service_cases_proto_goTypes,
		DependencyIndexes: file_testing_cases_api_v1_notebook_service_cases_proto_depIdxs,
		MessageInfos:      file_testing_cases_api_v1_notebook_service_cases_proto_msgTypes,
	}.Build()
	File_testing_cases_api_v1_notebook_service_cases_proto = out.File
	file_testing_cases_api_v1_notebook_service_cases_proto_goTypes = nil
	file_testing_cases_api_v1_notebook_service_cases_proto_depIdxs = nil
}
