// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/quiz.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/at-ishikawa/langner/gen-protos/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QuizServiceName is the fully-qualified name of the QuizService service.
	QuizServiceName = "api.v1.QuizService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QuizServiceGetQuizOptionsProcedure is the fully-qualified name of the QuizService's
	// GetQuizOptions RPC.
	QuizServiceGetQuizOptionsProcedure = "/api.v1.QuizService/GetQuizOptions"
	// QuizServiceStartQuizProcedure is the fully-qualified name of the QuizService's StartQuiz RPC.
	QuizServiceStartQuizProcedure = "/api.v1.QuizService/StartQuiz"
	// QuizServiceSubmitAnswerProcedure is the fully-qualified name of the QuizService's SubmitAnswer
	// RPC.
	QuizServiceSubmitAnswerProcedure = "/api.v1.QuizService/SubmitAnswer"
)

// QuizServiceClient is a client for the api.v1.QuizService service.
type QuizServiceClient interface {
	GetQuizOptions(context.Context, *connect.Request[v1.GetQuizOptionsRequest]) (*connect.Response[v1.GetQuizOptionsResponse], error)
	StartQuiz(context.Context, *connect.Request[v1.StartQuizRequest]) (*connect.Response[v1.StartQuizResponse], error)
	SubmitAnswer(context.Context, *connect.Request[v1.SubmitAnswerRequest]) (*connect.Response[v1.SubmitAnswerResponse], error)
}

// NewQuizServiceClient constructs a client for the api.v1.QuizService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQuizServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QuizServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	quizServiceMethods := v1.File_api_v1_quiz_proto.Services().ByName("QuizService").Methods()
	return &quizServiceClient{
		getQuizOptions: connect.NewClient[v1.GetQuizOptionsRequest, v1.GetQuizOptionsResponse](
			httpClient,
			baseURL+QuizServiceGetQuizOptionsProcedure,
			connect.WithSchema(quizServiceMethods.ByName("GetQuizOptions")),
			connect.WithClientOptions(opts...),
		),
		startQuiz: connect.NewClient[v1.StartQuizRequest, v1.StartQuizResponse](
			httpClient,
			baseURL+QuizServiceStartQuizProcedure,
			connect.WithSchema(quizServiceMethods.ByName("StartQuiz")),
			connect.WithClientOptions(opts...),
		),
		submitAnswer: connect.NewClient[v1.SubmitAnswerRequest, v1.SubmitAnswerResponse](
			httpClient,
			baseURL+QuizServiceSubmitAnswerProcedure,
			connect.WithSchema(quizServiceMethods.ByName("SubmitAnswer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// quizServiceClient implements QuizServiceClient.
type quizServiceClient struct {
	getQuizOptions *connect.Client[v1.GetQuizOptionsRequest, v1.GetQuizOptionsResponse]
	startQuiz      *connect.Client[v1.StartQuizRequest, v1.StartQuizResponse]
	submitAnswer   *connect.Client[v1.SubmitAnswerRequest, v1.SubmitAnswerResponse]
}

// GetQuizOptions calls api.v1.QuizService.GetQuizOptions.
func (c *quizServiceClient) GetQuizOptions(ctx context.Context, req *connect.Request[v1.GetQuizOptionsRequest]) (*connect.Response[v1.GetQuizOptionsResponse], error) {
	return c.getQuizOptions.CallUnary(ctx, req)
}

// StartQuiz calls api.v1.QuizService.StartQuiz.
func (c *quizServiceClient) StartQuiz(ctx context.Context, req *connect.Request[v1.StartQuizRequest]) (*connect.Response[v1.StartQuizResponse], error) {
	return c.startQuiz.CallUnary(ctx, req)
}

// SubmitAnswer calls api.v1.QuizService.SubmitAnswer.
func (c *quizServiceClient) SubmitAnswer(ctx context.Context, req *connect.Request[v1.SubmitAnswerRequest]) (*connect.Response[v1.SubmitAnswerResponse], error) {
	return c.submitAnswer.CallUnary(ctx, req)
}

// QuizServiceHandler is an implementation of the api.v1.QuizService service.
type QuizServiceHandler interface {
	GetQuizOptions(context.Context, *connect.Request[v1.GetQuizOptionsRequest]) (*connect.Response[v1.GetQuizOptionsResponse], error)
	StartQuiz(context.Context, *connect.Request[v1.StartQuizRequest]) (*connect.Response[v1.StartQuizResponse], error)
	SubmitAnswer(context.Context, *connect.Request[v1.SubmitAnswerRequest]) (*connect.Response[v1.SubmitAnswerResponse], error)
}

// NewQuizServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQuizServiceHandler(svc QuizServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	quizServiceMethods := v1.File_api_v1_quiz_proto.Services().ByName("QuizService").Methods()
	quizServiceGetQuizOptionsHandler := connect.NewUnaryHandler(
		QuizServiceGetQuizOptionsProcedure,
		svc.GetQuizOptions,
		connect.WithSchema(quizServiceMethods.ByName("GetQuizOptions")),
		connect.WithHandlerOptions(opts...),
	)
	quizServiceStartQuizHandler := connect.NewUnaryHandler(
		QuizServiceStartQuizProcedure,
		svc.StartQuiz,
		connect.WithSchema(quizServiceMethods.ByName("StartQuiz")),
		connect.WithHandlerOptions(opts...),
	)
	quizServiceSubmitAnswerHandler := connect.NewUnaryHandler(
		QuizServiceSubmitAnswerProcedure,
		svc.SubmitAnswer,
		connect.WithSchema(quizServiceMethods.ByName("SubmitAnswer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.QuizService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QuizServiceGetQuizOptionsProcedure:
			quizServiceGetQuizOptionsHandler.ServeHTTP(w, r)
		case QuizServiceStartQuizProcedure:
			quizServiceStartQuizHandler.ServeHTTP(w, r)
		case QuizServiceSubmitAnswerProcedure:
			quizServiceSubmitAnswerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQuizServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQuizServiceHandler struct{}

func (UnimplementedQuizServiceHandler) GetQuizOptions(context.Context, *connect.Request[v1.GetQuizOptionsRequest]) (*connect.Response[v1.GetQuizOptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.QuizService.GetQuizOptions is not implemented"))
}

func (UnimplementedQuizServiceHandler) StartQuiz(context.Context, *connect.Request[v1.StartQuizRequest]) (*connect.Response[v1.StartQuizResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.QuizService.StartQuiz is not implemented"))
}

func (UnimplementedQuizServiceHandler) SubmitAnswer(context.Context, *connect.Request[v1.SubmitAnswerRequest]) (*connect.Response[v1.SubmitAnswerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.QuizService.SubmitAnswer is not implemented"))
}
