// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file api/v1/quiz.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/quiz.proto.
 */
export const file_api_v1_quiz: GenFile = /*@__PURE__*/
  fileDesc("ChFhcGkvdjEvcXVpei5wcm90bxIGYXBpLnYxIhcKFUdldFF1aXpPcHRpb25zUmVxdWVzdCJEChZHZXRRdWl6T3B0aW9uc1Jlc3BvbnNlEioKCW5vdGVib29rcxgBIAMoCzIXLmFwaS52MS5Ob3RlYm9va1N1bW1hcnkiSgoPTm90ZWJvb2tTdW1tYXJ5EhMKC25vdGVib29rX2lkGAEgASgJEgwKBG5hbWUYAiABKAkSFAoMcmV2aWV3X2NvdW50GAMgASgFIkMKEFN0YXJ0UXVpelJlcXVlc3QSFAoMbm90ZWJvb2tfaWRzGAEgAygJEhkKEWluY2x1ZGVfdW5zdHVkaWVkGAIgASgIIjoKEVN0YXJ0UXVpelJlc3BvbnNlEiUKCmZsYXNoY2FyZHMYASADKAsyES5hcGkudjEuRmxhc2hjYXJkIk4KCUZsYXNoY2FyZBIPCgdub3RlX2lkGAEgASgDEg0KBWVudHJ5GAIgASgJEiEKCGV4YW1wbGVzGAMgAygLMg8uYXBpLnYxLkV4YW1wbGUiKAoHRXhhbXBsZRIMCgR0ZXh0GAEgASgJEg8KB3NwZWFrZXIYAiABKAkiUAoTU3VibWl0QW5zd2VyUmVxdWVzdBIPCgdub3RlX2lkGAEgASgDEg4KBmFuc3dlchgCIAEoCRIYChByZXNwb25zZV90aW1lX21zGAMgASgDIkgKFFN1Ym1pdEFuc3dlclJlc3BvbnNlEg8KB2NvcnJlY3QYASABKAgSDwoHbWVhbmluZxgCIAEoCRIOCgZyZWFzb24YAyABKAky6wEKC1F1aXpTZXJ2aWNlEk8KDkdldFF1aXpPcHRpb25zEh0uYXBpLnYxLkdldFF1aXpPcHRpb25zUmVxdWVzdBoeLmFwaS52MS5HZXRRdWl6T3B0aW9uc1Jlc3BvbnNlEkAKCVN0YXJ0UXVpehIYLmFwaS52MS5TdGFydFF1aXpSZXF1ZXN0GhkuYXBpLnYxLlN0YXJ0UXVpelJlc3BvbnNlEkkKDFN1Ym1pdEFuc3dlchIbLmFwaS52MS5TdWJtaXRBbnN3ZXJSZXF1ZXN0GhwuYXBpLnYxLlN1Ym1pdEFuc3dlclJlc3BvbnNlQjhaNmdpdGh1Yi5jb20vYXQtaXNoaWthd2EvbGFuZ25lci9nZW4tcHJvdG9zL2FwaS92MTthcGl2MWIGcHJvdG8z");

/**
 * @generated from message api.v1.GetQuizOptionsRequest
 */
export type GetQuizOptionsRequest = Message<"api.v1.GetQuizOptionsRequest"> & {
};

/**
 * Describes the message api.v1.GetQuizOptionsRequest.
 * Use `create(GetQuizOptionsRequestSchema)` to create a new message.
 */
export const GetQuizOptionsRequestSchema: GenMessage<GetQuizOptionsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 0);

/**
 * @generated from message api.v1.GetQuizOptionsResponse
 */
export type GetQuizOptionsResponse = Message<"api.v1.GetQuizOptionsResponse"> & {
  /**
   * @generated from field: repeated api.v1.NotebookSummary notebooks = 1;
   */
  notebooks: NotebookSummary[];
};

/**
 * Describes the message api.v1.GetQuizOptionsResponse.
 * Use `create(GetQuizOptionsResponseSchema)` to create a new message.
 */
export const GetQuizOptionsResponseSchema: GenMessage<GetQuizOptionsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 1);

/**
 * @generated from message api.v1.NotebookSummary
 */
export type NotebookSummary = Message<"api.v1.NotebookSummary"> & {
  /**
   * @generated from field: string notebook_id = 1;
   */
  notebookId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 review_count = 3;
   */
  reviewCount: number;
};

/**
 * Describes the message api.v1.NotebookSummary.
 * Use `create(NotebookSummarySchema)` to create a new message.
 */
export const NotebookSummarySchema: GenMessage<NotebookSummary> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 2);

/**
 * @generated from message api.v1.StartQuizRequest
 */
export type StartQuizRequest = Message<"api.v1.StartQuizRequest"> & {
  /**
   * @generated from field: repeated string notebook_ids = 1;
   */
  notebookIds: string[];

  /**
   * @generated from field: bool include_unstudied = 2;
   */
  includeUnstudied: boolean;
};

/**
 * Describes the message api.v1.StartQuizRequest.
 * Use `create(StartQuizRequestSchema)` to create a new message.
 */
export const StartQuizRequestSchema: GenMessage<StartQuizRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 3);

/**
 * @generated from message api.v1.StartQuizResponse
 */
export type StartQuizResponse = Message<"api.v1.StartQuizResponse"> & {
  /**
   * @generated from field: repeated api.v1.Flashcard flashcards = 1;
   */
  flashcards: Flashcard[];
};

/**
 * Describes the message api.v1.StartQuizResponse.
 * Use `create(StartQuizResponseSchema)` to create a new message.
 */
export const StartQuizResponseSchema: GenMessage<StartQuizResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 4);

/**
 * @generated from message api.v1.Flashcard
 */
export type Flashcard = Message<"api.v1.Flashcard"> & {
  /**
   * @generated from field: int64 note_id = 1;
   */
  noteId: bigint;

  /**
   * @generated from field: string entry = 2;
   */
  entry: string;

  /**
   * @generated from field: repeated api.v1.Example examples = 3;
   */
  examples: Example[];
};

/**
 * Describes the message api.v1.Flashcard.
 * Use `create(FlashcardSchema)` to create a new message.
 */
export const FlashcardSchema: GenMessage<Flashcard> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 5);

/**
 * @generated from message api.v1.Example
 */
export type Example = Message<"api.v1.Example"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * @generated from field: string speaker = 2;
   */
  speaker: string;
};

/**
 * Describes the message api.v1.Example.
 * Use `create(ExampleSchema)` to create a new message.
 */
export const ExampleSchema: GenMessage<Example> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 6);

/**
 * @generated from message api.v1.SubmitAnswerRequest
 */
export type SubmitAnswerRequest = Message<"api.v1.SubmitAnswerRequest"> & {
  /**
   * @generated from field: int64 note_id = 1;
   */
  noteId: bigint;

  /**
   * @generated from field: string answer = 2;
   */
  answer: string;

  /**
   * @generated from field: int64 response_time_ms = 3;
   */
  responseTimeMs: bigint;
};

/**
 * Describes the message api.v1.SubmitAnswerRequest.
 * Use `create(SubmitAnswerRequestSchema)` to create a new message.
 */
export const SubmitAnswerRequestSchema: GenMessage<SubmitAnswerRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 7);

/**
 * @generated from message api.v1.SubmitAnswerResponse
 */
export type SubmitAnswerResponse = Message<"api.v1.SubmitAnswerResponse"> & {
  /**
   * @generated from field: bool correct = 1;
   */
  correct: boolean;

  /**
   * @generated from field: string meaning = 2;
   */
  meaning: string;

  /**
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message api.v1.SubmitAnswerResponse.
 * Use `create(SubmitAnswerResponseSchema)` to create a new message.
 */
export const SubmitAnswerResponseSchema: GenMessage<SubmitAnswerResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_quiz, 8);

/**
 * @generated from service api.v1.QuizService
 */
export const QuizService: GenService<{
  /**
   * @generated from rpc api.v1.QuizService.GetQuizOptions
   */
  getQuizOptions: {
    methodKind: "unary";
    input: typeof GetQuizOptionsRequestSchema;
    output: typeof GetQuizOptionsResponseSchema;
  },
  /**
   * @generated from rpc api.v1.QuizService.StartQuiz
   */
  startQuiz: {
    methodKind: "unary";
    input: typeof StartQuizRequestSchema;
    output: typeof StartQuizResponseSchema;
  },
  /**
   * @generated from rpc api.v1.QuizService.SubmitAnswer
   */
  submitAnswer: {
    methodKind: "unary";
    input: typeof SubmitAnswerRequestSchema;
    output: typeof SubmitAnswerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_quiz, 0);

