// Code generated by MockGen. DO NOT EDIT.
// Source: datasync.go
//
// Generated by this command:
//
//	mockgen -source=datasync.go -destination=../mocks/datasync/mock_datasync.go -package=mock_datasync
//

// Package mock_datasync is a generated GoMock package.
package mock_datasync

import (
	context "context"
	reflect "reflect"

	rapidapi "github.com/at-ishikawa/langner/internal/dictionary/rapidapi"
	learning "github.com/at-ishikawa/langner/internal/learning"
	notebook "github.com/at-ishikawa/langner/internal/notebook"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteSource is a mock of NoteSource interface.
type MockNoteSource struct {
	ctrl     *gomock.Controller
	recorder *MockNoteSourceMockRecorder
	isgomock struct{}
}

// MockNoteSourceMockRecorder is the mock recorder for MockNoteSource.
type MockNoteSourceMockRecorder struct {
	mock *MockNoteSource
}

// NewMockNoteSource creates a new mock instance.
func NewMockNoteSource(ctrl *gomock.Controller) *MockNoteSource {
	mock := &MockNoteSource{ctrl: ctrl}
	mock.recorder = &MockNoteSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteSource) EXPECT() *MockNoteSourceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockNoteSource) FindAll(ctx context.Context) ([]notebook.NoteRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.NoteRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockNoteSourceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockNoteSource)(nil).FindAll), ctx)
}

// MockLearningSource is a mock of LearningSource interface.
type MockLearningSource struct {
	ctrl     *gomock.Controller
	recorder *MockLearningSourceMockRecorder
	isgomock struct{}
}

// MockLearningSourceMockRecorder is the mock recorder for MockLearningSource.
type MockLearningSourceMockRecorder struct {
	mock *MockLearningSource
}

// NewMockLearningSource creates a new mock instance.
func NewMockLearningSource(ctrl *gomock.Controller) *MockLearningSource {
	mock := &MockLearningSource{ctrl: ctrl}
	mock.recorder = &MockLearningSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLearningSource) EXPECT() *MockLearningSourceMockRecorder {
	return m.recorder
}

// FindByNotebookID mocks base method.
func (m *MockLearningSource) FindByNotebookID(notebookID string) ([]notebook.LearningHistoryExpression, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNotebookID", notebookID)
	ret0, _ := ret[0].([]notebook.LearningHistoryExpression)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNotebookID indicates an expected call of FindByNotebookID.
func (mr *MockLearningSourceMockRecorder) FindByNotebookID(notebookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNotebookID", reflect.TypeOf((*MockLearningSource)(nil).FindByNotebookID), notebookID)
}

// MockDictionarySource is a mock of DictionarySource interface.
type MockDictionarySource struct {
	ctrl     *gomock.Controller
	recorder *MockDictionarySourceMockRecorder
	isgomock struct{}
}

// MockDictionarySourceMockRecorder is the mock recorder for MockDictionarySource.
type MockDictionarySourceMockRecorder struct {
	mock *MockDictionarySource
}

// NewMockDictionarySource creates a new mock instance.
func NewMockDictionarySource(ctrl *gomock.Controller) *MockDictionarySource {
	mock := &MockDictionarySource{ctrl: ctrl}
	mock.recorder = &MockDictionarySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDictionarySource) EXPECT() *MockDictionarySourceMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockDictionarySource) ReadAll() ([]rapidapi.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll")
	ret0, _ := ret[0].([]rapidapi.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockDictionarySourceMockRecorder) ReadAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockDictionarySource)(nil).ReadAll))
}

// MockEtymologyOriginSource is a mock of EtymologyOriginSource interface.
type MockEtymologyOriginSource struct {
	ctrl     *gomock.Controller
	recorder *MockEtymologyOriginSourceMockRecorder
	isgomock struct{}
}

// MockEtymologyOriginSourceMockRecorder is the mock recorder for MockEtymologyOriginSource.
type MockEtymologyOriginSourceMockRecorder struct {
	mock *MockEtymologyOriginSource
}

// NewMockEtymologyOriginSource creates a new mock instance.
func NewMockEtymologyOriginSource(ctrl *gomock.Controller) *MockEtymologyOriginSource {
	mock := &MockEtymologyOriginSource{ctrl: ctrl}
	mock.recorder = &MockEtymologyOriginSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEtymologyOriginSource) EXPECT() *MockEtymologyOriginSourceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockEtymologyOriginSource) FindAll(ctx context.Context) ([]notebook.EtymologyOriginRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.EtymologyOriginRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockEtymologyOriginSourceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockEtymologyOriginSource)(nil).FindAll), ctx)
}

// MockEtymologyDefinitionSource is a mock of EtymologyDefinitionSource interface.
type MockEtymologyDefinitionSource struct {
	ctrl     *gomock.Controller
	recorder *MockEtymologyDefinitionSourceMockRecorder
	isgomock struct{}
}

// MockEtymologyDefinitionSourceMockRecorder is the mock recorder for MockEtymologyDefinitionSource.
type MockEtymologyDefinitionSourceMockRecorder struct {
	mock *MockEtymologyDefinitionSource
}

// NewMockEtymologyDefinitionSource creates a new mock instance.
func NewMockEtymologyDefinitionSource(ctrl *gomock.Controller) *MockEtymologyDefinitionSource {
	mock := &MockEtymologyDefinitionSource{ctrl: ctrl}
	mock.recorder = &MockEtymologyDefinitionSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEtymologyDefinitionSource) EXPECT() *MockEtymologyDefinitionSourceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockEtymologyDefinitionSource) FindAll(ctx context.Context) ([]notebook.EtymologyDefinitionForImport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.EtymologyDefinitionForImport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockEtymologyDefinitionSourceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockEtymologyDefinitionSource)(nil).FindAll), ctx)
}

// MockEtymologyOriginFormSource is a mock of EtymologyOriginFormSource interface.
type MockEtymologyOriginFormSource struct {
	ctrl     *gomock.Controller
	recorder *MockEtymologyOriginFormSourceMockRecorder
	isgomock struct{}
}

// MockEtymologyOriginFormSourceMockRecorder is the mock recorder for MockEtymologyOriginFormSource.
type MockEtymologyOriginFormSourceMockRecorder struct {
	mock *MockEtymologyOriginFormSource
}

// NewMockEtymologyOriginFormSource creates a new mock instance.
func NewMockEtymologyOriginFormSource(ctrl *gomock.Controller) *MockEtymologyOriginFormSource {
	mock := &MockEtymologyOriginFormSource{ctrl: ctrl}
	mock.recorder = &MockEtymologyOriginFormSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEtymologyOriginFormSource) EXPECT() *MockEtymologyOriginFormSourceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockEtymologyOriginFormSource) FindAll(ctx context.Context) ([]notebook.EtymologyOriginFormForImport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.EtymologyOriginFormForImport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockEtymologyOriginFormSourceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockEtymologyOriginFormSource)(nil).FindAll), ctx)
}

// MockSemanticConceptSource is a mock of SemanticConceptSource interface.
type MockSemanticConceptSource struct {
	ctrl     *gomock.Controller
	recorder *MockSemanticConceptSourceMockRecorder
	isgomock struct{}
}

// MockSemanticConceptSourceMockRecorder is the mock recorder for MockSemanticConceptSource.
type MockSemanticConceptSourceMockRecorder struct {
	mock *MockSemanticConceptSource
}

// NewMockSemanticConceptSource creates a new mock instance.
func NewMockSemanticConceptSource(ctrl *gomock.Controller) *MockSemanticConceptSource {
	mock := &MockSemanticConceptSource{ctrl: ctrl}
	mock.recorder = &MockSemanticConceptSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemanticConceptSource) EXPECT() *MockSemanticConceptSourceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockSemanticConceptSource) FindAll(ctx context.Context) ([]notebook.SemanticConceptForImport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.SemanticConceptForImport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSemanticConceptSourceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSemanticConceptSource)(nil).FindAll), ctx)
}

// MockConceptRelationSource is a mock of ConceptRelationSource interface.
type MockConceptRelationSource struct {
	ctrl     *gomock.Controller
	recorder *MockConceptRelationSourceMockRecorder
	isgomock struct{}
}

// MockConceptRelationSourceMockRecorder is the mock recorder for MockConceptRelationSource.
type MockConceptRelationSourceMockRecorder struct {
	mock *MockConceptRelationSource
}

// NewMockConceptRelationSource creates a new mock instance.
func NewMockConceptRelationSource(ctrl *gomock.Controller) *MockConceptRelationSource {
	mock := &MockConceptRelationSource{ctrl: ctrl}
	mock.recorder = &MockConceptRelationSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConceptRelationSource) EXPECT() *MockConceptRelationSourceMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockConceptRelationSource) FindAll(ctx context.Context) ([]notebook.ConceptRelationForImport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.ConceptRelationForImport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockConceptRelationSourceMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockConceptRelationSource)(nil).FindAll), ctx)
}

// MockNoteSink is a mock of NoteSink interface.
type MockNoteSink struct {
	ctrl     *gomock.Controller
	recorder *MockNoteSinkMockRecorder
	isgomock struct{}
}

// MockNoteSinkMockRecorder is the mock recorder for MockNoteSink.
type MockNoteSinkMockRecorder struct {
	mock *MockNoteSink
}

// NewMockNoteSink creates a new mock instance.
func NewMockNoteSink(ctrl *gomock.Controller) *MockNoteSink {
	mock := &MockNoteSink{ctrl: ctrl}
	mock.recorder = &MockNoteSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteSink) EXPECT() *MockNoteSinkMockRecorder {
	return m.recorder
}

// WriteAll mocks base method.
func (m *MockNoteSink) WriteAll(notes []notebook.NoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAll", notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAll indicates an expected call of WriteAll.
func (mr *MockNoteSinkMockRecorder) WriteAll(notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAll", reflect.TypeOf((*MockNoteSink)(nil).WriteAll), notes)
}

// MockLearningSink is a mock of LearningSink interface.
type MockLearningSink struct {
	ctrl     *gomock.Controller
	recorder *MockLearningSinkMockRecorder
	isgomock struct{}
}

// MockLearningSinkMockRecorder is the mock recorder for MockLearningSink.
type MockLearningSinkMockRecorder struct {
	mock *MockLearningSink
}

// NewMockLearningSink creates a new mock instance.
func NewMockLearningSink(ctrl *gomock.Controller) *MockLearningSink {
	mock := &MockLearningSink{ctrl: ctrl}
	mock.recorder = &MockLearningSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLearningSink) EXPECT() *MockLearningSinkMockRecorder {
	return m.recorder
}

// WriteAll mocks base method.
func (m *MockLearningSink) WriteAll(notes []notebook.NoteRecord, logs []learning.LearningLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAll", notes, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAll indicates an expected call of WriteAll.
func (mr *MockLearningSinkMockRecorder) WriteAll(notes, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAll", reflect.TypeOf((*MockLearningSink)(nil).WriteAll), notes, logs)
}

// MockDictionarySink is a mock of DictionarySink interface.
type MockDictionarySink struct {
	ctrl     *gomock.Controller
	recorder *MockDictionarySinkMockRecorder
	isgomock struct{}
}

// MockDictionarySinkMockRecorder is the mock recorder for MockDictionarySink.
type MockDictionarySinkMockRecorder struct {
	mock *MockDictionarySink
}

// NewMockDictionarySink creates a new mock instance.
func NewMockDictionarySink(ctrl *gomock.Controller) *MockDictionarySink {
	mock := &MockDictionarySink{ctrl: ctrl}
	mock.recorder = &MockDictionarySinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDictionarySink) EXPECT() *MockDictionarySinkMockRecorder {
	return m.recorder
}

// WriteAll mocks base method.
func (m *MockDictionarySink) WriteAll(entries []rapidapi.DictionaryExportEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAll", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAll indicates an expected call of WriteAll.
func (mr *MockDictionarySinkMockRecorder) WriteAll(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAll", reflect.TypeOf((*MockDictionarySink)(nil).WriteAll), entries)
}
