// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../mocks/inference/mock_client.go -package=mock_inference
//

// Package mock_inference is a generated GoMock package.
package mock_inference

import (
	context "context"
	reflect "reflect"

	inference "github.com/at-ishikawa/langner/internal/inference"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AnswerMeanings mocks base method.
func (m *MockClient) AnswerMeanings(ctx context.Context, params inference.AnswerMeaningsRequest) (inference.AnswerMeaningsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerMeanings", ctx, params)
	ret0, _ := ret[0].(inference.AnswerMeaningsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnswerMeanings indicates an expected call of AnswerMeanings.
func (mr *MockClientMockRecorder) AnswerMeanings(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerMeanings", reflect.TypeOf((*MockClient)(nil).AnswerMeanings), ctx, params)
}

// ValidateWordForm mocks base method.
func (m *MockClient) ValidateWordForm(ctx context.Context, params inference.ValidateWordFormRequest) (inference.ValidateWordFormResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWordForm", ctx, params)
	ret0, _ := ret[0].(inference.ValidateWordFormResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateWordForm indicates an expected call of ValidateWordForm.
func (mr *MockClientMockRecorder) ValidateWordForm(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWordForm", reflect.TypeOf((*MockClient)(nil).ValidateWordForm), ctx, params)
}
