// Code generated by MockGen. DO NOT EDIT.
// Source: note_repository.go
//
// Generated by this command:
//
//	mockgen -source=note_repository.go -destination=../mocks/notebook/mock_note_repository.go -package=mock_notebook
//

// Package mock_notebook is a generated GoMock package.
package mock_notebook

import (
	context "context"
	reflect "reflect"

	notebook "github.com/at-ishikawa/langner/internal/notebook"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteRepository is a mock of NoteRepository interface.
type MockNoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNoteRepositoryMockRecorder
	isgomock struct{}
}

// MockNoteRepositoryMockRecorder is the mock recorder for MockNoteRepository.
type MockNoteRepositoryMockRecorder struct {
	mock *MockNoteRepository
}

// NewMockNoteRepository creates a new mock instance.
func NewMockNoteRepository(ctrl *gomock.Controller) *MockNoteRepository {
	mock := &MockNoteRepository{ctrl: ctrl}
	mock.recorder = &MockNoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteRepository) EXPECT() *MockNoteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNoteRepository) Create(ctx context.Context, n *notebook.NoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNoteRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNoteRepository)(nil).Create), ctx, n)
}

// CreateNotebookNote mocks base method.
func (m *MockNoteRepository) CreateNotebookNote(ctx context.Context, nn *notebook.NotebookNote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotebookNote", ctx, nn)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotebookNote indicates an expected call of CreateNotebookNote.
func (mr *MockNoteRepositoryMockRecorder) CreateNotebookNote(ctx, nn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotebookNote", reflect.TypeOf((*MockNoteRepository)(nil).CreateNotebookNote), ctx, nn)
}

// FindAll mocks base method.
func (m *MockNoteRepository) FindAll(ctx context.Context) ([]notebook.NoteRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.NoteRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockNoteRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockNoteRepository)(nil).FindAll), ctx)
}

// Update mocks base method.
func (m *MockNoteRepository) Update(ctx context.Context, n *notebook.NoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNoteRepositoryMockRecorder) Update(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNoteRepository)(nil).Update), ctx, n)
}
