// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notebook/note_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/notebook/note_repository.go -destination=internal/mocks/notebook/mock_note_repository.go -package=mock_notebook
//

// Package mock_notebook is a generated GoMock package.
package mock_notebook

import (
	context "context"
	reflect "reflect"

	notebook "github.com/at-ishikawa/langner/internal/notebook"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteRepository is a mock of NoteRepository interface.
type MockNoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNoteRepositoryMockRecorder
	isgomock struct{}
}

// MockNoteRepositoryMockRecorder is the mock recorder for MockNoteRepository.
type MockNoteRepositoryMockRecorder struct {
	mock *MockNoteRepository
}

// NewMockNoteRepository creates a new mock instance.
func NewMockNoteRepository(ctrl *gomock.Controller) *MockNoteRepository {
	mock := &MockNoteRepository{ctrl: ctrl}
	mock.recorder = &MockNoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteRepository) EXPECT() *MockNoteRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockNoteRepository) BatchCreate(ctx context.Context, notes []*notebook.NoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockNoteRepositoryMockRecorder) BatchCreate(ctx, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockNoteRepository)(nil).BatchCreate), ctx, notes)
}

// BatchUpdate mocks base method.
func (m *MockNoteRepository) BatchUpdate(ctx context.Context, notes []*notebook.NoteRecord, newNotebookNotes []notebook.NotebookNote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", ctx, notes, newNotebookNotes)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockNoteRepositoryMockRecorder) BatchUpdate(ctx, notes, newNotebookNotes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockNoteRepository)(nil).BatchUpdate), ctx, notes, newNotebookNotes)
}

// Create mocks base method.
func (m *MockNoteRepository) Create(ctx context.Context, note *notebook.NoteRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, note)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNoteRepositoryMockRecorder) Create(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNoteRepository)(nil).Create), ctx, note)
}

// Delete mocks base method.
func (m *MockNoteRepository) Delete(ctx context.Context, notebookID, expression string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, notebookID, expression)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNoteRepositoryMockRecorder) Delete(ctx, notebookID, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNoteRepository)(nil).Delete), ctx, notebookID, expression)
}

// FindAll mocks base method.
func (m *MockNoteRepository) FindAll(ctx context.Context) ([]notebook.NoteRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]notebook.NoteRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockNoteRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockNoteRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockNoteRepository) FindByID(ctx context.Context, id int64) (*notebook.NoteRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*notebook.NoteRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNoteRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNoteRepository)(nil).FindByID), ctx, id)
}
