// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/quiz.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuizOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizOptionsRequest) Reset() {
	*x = GetQuizOptionsRequest{}
	mi := &file_api_v1_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizOptionsRequest) ProtoMessage() {}

func (x *GetQuizOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetQuizOptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{0}
}

type GetQuizOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notebooks     []*NotebookSummary     `protobuf:"bytes,1,rep,name=notebooks,proto3" json:"notebooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuizOptionsResponse) Reset() {
	*x = GetQuizOptionsResponse{}
	mi := &file_api_v1_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuizOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizOptionsResponse) ProtoMessage() {}

func (x *GetQuizOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetQuizOptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuizOptionsResponse) GetNotebooks() []*NotebookSummary {
	if x != nil {
		return x.Notebooks
	}
	return nil
}

type NotebookSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,3,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotebookSummary) Reset() {
	*x = NotebookSummary{}
	mi := &file_api_v1_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotebookSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotebookSummary) ProtoMessage() {}

func (x *NotebookSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotebookSummary.ProtoReflect.Descriptor instead.
func (*NotebookSummary) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *NotebookSummary) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *NotebookSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotebookSummary) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type StartQuizRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotebookIds      []string               `protobuf:"bytes,1,rep,name=notebook_ids,json=notebookIds,proto3" json:"notebook_ids,omitempty"`
	IncludeUnstudied bool                   `protobuf:"varint,2,opt,name=include_unstudied,json=includeUnstudied,proto3" json:"include_unstudied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartQuizRequest) Reset() {
	*x = StartQuizRequest{}
	mi := &file_api_v1_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQuizRequest) ProtoMessage() {}

func (x *StartQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQuizRequest.ProtoReflect.Descriptor instead.
func (*StartQuizRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *StartQuizRequest) GetNotebookIds() []string {
	if x != nil {
		return x.NotebookIds
	}
	return nil
}

func (x *StartQuizRequest) GetIncludeUnstudied() bool {
	if x != nil {
		return x.IncludeUnstudied
	}
	return false
}

type StartQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flashcards    []*Flashcard           `protobuf:"bytes,1,rep,name=flashcards,proto3" json:"flashcards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartQuizResponse) Reset() {
	*x = StartQuizResponse{}
	mi := &file_api_v1_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQuizResponse) ProtoMessage() {}

func (x *StartQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQuizResponse.ProtoReflect.Descriptor instead.
func (*StartQuizResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *StartQuizResponse) GetFlashcards() []*Flashcard {
	if x != nil {
		return x.Flashcards
	}
	return nil
}

type Flashcard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Entry         string                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	Examples      []*Example             `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flashcard) Reset() {
	*x = Flashcard{}
	mi := &file_api_v1_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flashcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flashcard) ProtoMessage() {}

func (x *Flashcard) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flashcard.ProtoReflect.Descriptor instead.
func (*Flashcard) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *Flashcard) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *Flashcard) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *Flashcard) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Speaker       string                 `protobuf:"bytes,2,opt,name=speaker,proto3" json:"speaker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_api_v1_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *Example) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Example) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

type SubmitAnswerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NoteId         int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Answer         string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,3,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_api_v1_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitAnswerRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *SubmitAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitAnswerRequest) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correct       bool                   `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	Meaning       string                 `protobuf:"bytes,2,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_api_v1_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitAnswerResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *SubmitAnswerResponse) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *SubmitAnswerResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_v1_quiz_proto protoreflect.FileDescriptor

const file_api_v1_quiz_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/quiz.proto\x12\x06api.v1\"\x17\n" +
	"\x15GetQuizOptionsRequest\"O\n" +
	"\x16GetQuizOptionsResponse\x125\n" +
	"\tnotebooks\x18\x01 \x03(\v2\x17.api.v1.NotebookSummaryR\tnotebooks\"i\n" +
	"\x0fNotebookSummary\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\tR\n" +
	"notebookId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\freview_count\x18\x03 \x01(\x05R\vreviewCount\"b\n" +
	"\x10StartQuizRequest\x12!\n" +
	"\fnotebook_ids\x18\x01 \x03(\tR\vnotebookIds\x12+\n" +
	"\x11include_unstudied\x18\x02 \x01(\bR\x10includeUnstudied\"F\n" +
	"\x11StartQuizResponse\x121\n" +
	"\n" +
	"flashcards\x18\x01 \x03(\v2\x11.api.v1.FlashcardR\n" +
	"flashcards\"g\n" +
	"\tFlashcard\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x14\n" +
	"\x05entry\x18\x02 \x01(\tR\x05entry\x12+\n" +
	"\bexamples\x18\x03 \x03(\v2\x0f.api.v1.ExampleR\bexamples\"7\n" +
	"\aExample\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x18\n" +
	"\aspeaker\x18\x02 \x01(\tR\aspeaker\"p\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12(\n" +
	"\x10response_time_ms\x18\x03 \x01(\x03R\x0eresponseTimeMs\"b\n" +
	"\x14SubmitAnswerResponse\x12\x18\n" +
	"\acorrect\x18\x01 \x01(\bR\acorrect\x12\x18\n" +
	"\ameaning\x18\x02 \x01(\tR\ameaning\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xeb\x01\n" +
	"\vQuizService\x12O\n" +
	"\x0eGetQuizOptions\x12\x1d.api.v1.GetQuizOptionsRequest\x1a\x1e.api.v1.GetQuizOptionsResponse\x12@\n" +
	"\tStartQuiz\x12\x18.api.v1.StartQuizRequest\x1a\x19.api.v1.StartQuizResponse\x12I\n" +
	"\fSubmitAnswer\x12\x1b.api.v1.SubmitAnswerRequest\x1a\x1c.api.v1.SubmitAnswerResponseB8Z6github.com/at-ishikawa/langner/gen-protos/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_quiz_proto_rawDescOnce sync.Once
	file_api_v1_quiz_proto_rawDescData []byte
)

func file_api_v1_quiz_proto_rawDescGZIP() []byte {
	file_api_v1_quiz_proto_rawDescOnce.Do(func() {
		file_api_v1_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_quiz_proto_rawDesc), len(file_api_v1_quiz_proto_rawDesc)))
	})
	return file_api_v1_quiz_proto_rawDescData
}

var file_api_v1_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_quiz_proto_goTypes = []any{
	(*GetQuizOptionsRequest)(nil),  // 0: api.v1.GetQuizOptionsRequest
	(*GetQuizOptionsResponse)(nil), // 1: api.v1.GetQuizOptionsResponse
	(*NotebookSummary)(nil),        // 2: api.v1.NotebookSummary
	(*StartQuizRequest)(nil),       // 3: api.v1.StartQuizRequest
	(*StartQuizResponse)(nil),      // 4: api.v1.StartQuizResponse
	(*Flashcard)(nil),              // 5: api.v1.Flashcard
	(*Example)(nil),                // 6: api.v1.Example
	(*SubmitAnswerRequest)(nil),    // 7: api.v1.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil),   // 8: api.v1.SubmitAnswerResponse
}
var file_api_v1_quiz_proto_depIdxs = []int32{
	2, // 0: api.v1.GetQuizOptionsResponse.notebooks:type_name -> api.v1.NotebookSummary
	5, // 1: api.v1.StartQuizResponse.flashcards:type_name -> api.v1.Flashcard
	6, // 2: api.v1.Flashcard.examples:type_name -> api.v1.Example
	0, // 3: api.v1.QuizService.GetQuizOptions:input_type -> api.v1.GetQuizOptionsRequest
	3, // 4: api.v1.QuizService.StartQuiz:input_type -> api.v1.StartQuizRequest
	7, // 5: api.v1.QuizService.SubmitAnswer:input_type -> api.v1.SubmitAnswerRequest
	1, // 6: api.v1.QuizService.GetQuizOptions:output_type -> api.v1.GetQuizOptionsResponse
	4, // 7: api.v1.QuizService.StartQuiz:output_type -> api.v1.StartQuizResponse
	8, // 8: api.v1.QuizService.SubmitAnswer:output_type -> api.v1.SubmitAnswerResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_quiz_proto_init() }
func file_api_v1_quiz_proto_init() {
	if File_api_v1_quiz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_quiz_proto_rawDesc), len(file_api_v1_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_quiz_proto_goTypes,
		DependencyIndexes: file_api_v1_quiz_proto_depIdxs,
		MessageInfos:      file_api_v1_quiz_proto_msgTypes,
	}.Build()
	File_api_v1_quiz_proto = out.File
	file_api_v1_quiz_proto_goTypes = nil
	file_api_v1_quiz_proto_depIdxs = nil
}
