package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"connectrpc.com/connect"
	"github.com/jmoiron/sqlx"
	"github.com/spf13/cobra"

	"github.com/at-ishikawa/langner/gen-protos/api/v1/apiv1connect"
	"github.com/at-ishikawa/langner/internal/analytics"
	"github.com/at-ishikawa/langner/internal/auth"
	"github.com/at-ishikawa/langner/internal/bootstrap"
	"github.com/at-ishikawa/langner/internal/config"
	"github.com/at-ishikawa/langner/internal/database"
	"github.com/at-ishikawa/langner/internal/datasync"
	"github.com/at-ishikawa/langner/internal/dictionary"
	"github.com/at-ishikawa/langner/internal/dictionary/rapidapi"
	"github.com/at-ishikawa/langner/internal/inference"
	"github.com/at-ishikawa/langner/internal/inference/gemini"
	"github.com/at-ishikawa/langner/internal/inference/mock"
	"github.com/at-ishikawa/langner/internal/inference/openai"
	"github.com/at-ishikawa/langner/internal/notebook"
	"github.com/at-ishikawa/langner/internal/quiz"
	"github.com/at-ishikawa/langner/internal/server"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

var configFile string

func main() {
	rootCmd := &cobra.Command{
		Use:           "langner-server",
		Short:         "Langner quiz service HTTP server",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			return run(cmd.Context())
		},
	}
	rootCmd.Flags().StringVar(&configFile, "config", "", "config file path")

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run(ctx context.Context) error {
	app := bootstrap.New()

	cfg, err := loadConfig()
	if err != nil {
		return fmt.Errorf("loadConfig() > %w", err)
	}

	var inferenceClient inference.Client
	switch cfg.Inference.Mode {
	case "mock":
		inferenceClient = mock.NewClient()
		slog.Info("using mock inference client (substring grader)")
	case "gemini":
		if cfg.Gemini.APIKey != "" {
			geminiClient := gemini.NewClient(cfg.Gemini.APIKey, cfg.Gemini.Model, inference.DefaultMaxRetryAttempts)
			defer func() {
				_ = geminiClient.Close()
			}()
			inferenceClient = geminiClient
			slog.Info("using Gemini inference provider", "model", cfg.Gemini.Model)
		} else {
			slog.Warn("GEMINI_API_KEY is not set; quiz grading features will be unavailable")
		}
	default:
		if cfg.OpenAI.APIKey != "" {
			openaiClient := openai.NewClient(cfg.OpenAI.APIKey, cfg.OpenAI.Model, inference.DefaultMaxRetryAttempts)
			defer func() {
				_ = openaiClient.Close()
			}()
			inferenceClient = openaiClient
		} else {
			slog.Warn("OPENAI_API_KEY is not set; quiz grading features will be unavailable")
		}
	}

	dictionaryMap, err := loadDictionaryMap(cfg.Dictionaries.RapidAPI.CacheDirectory)
	if err != nil {
		slog.Warn("failed to load dictionary cache", "error", err)
		dictionaryMap = make(map[string]rapidapi.Response)
	}

	loggingInterceptor := connect.UnaryInterceptorFunc(func(next connect.UnaryFunc) connect.UnaryFunc {
		return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
			resp, err := next(ctx, req)
			if err != nil {
				slog.Error("rpc error", "procedure", req.Spec().Procedure, "error", err)
			}
			return resp, err
		}
	})

	// A database is REQUIRED: auth is always mounted and every RPC is gated, so
	// users / per-user state / device-flow rows must live in Postgres. buildAuth
	// fails fast when db is nil, so if the connection cannot be opened the server
	// refuses to start (rather than silently running ungated).
	var db *sqlx.DB
	if cfg.Database.Host != "" && cfg.Database.Password != "" {
		opened, err := database.Open(cfg.Database)
		if err != nil {
			slog.Error("failed to open database", "error", err)
		} else {
			db = opened
			app.AddShutdownHook(func(ctx context.Context) error {
				return db.Close()
			})
		}
	}

	// Always-on auth (design §2). Google-OAuth sign-in mints a langner access
	// JWT for the web SPA (delivered in the URL fragment, no session cookie) and
	// the RFC 8628 device flow mints one for the CLI; EVERY connect RPC is gated
	// behind a valid `Authorization: Bearer` token. buildAuth fails fast if the
	// database or TOKEN_SIGNING_KEY is missing, so the server never starts
	// silently ungated.
	authSetup, err := buildAuth(cfg, db)
	if err != nil {
		return fmt.Errorf("set up auth: %w", err)
	}
	slog.Info("auth enabled; all RPCs require a valid bearer access token (web + CLI)")

	// User-STATE repositories. When a database is configured, writes go to the
	// DB ONLY — the runtime never rewrites the on-disk learning_notes YAML
	// (frozen at import time, regenerated by `langner export-db`) — and reads
	// are served from the DB via historyStore. Without a database both reads
	// and writes use the on-disk YAML, exactly as before.
	repos := bootstrap.BuildStateRepositories(cfg.Notebooks, cfg.Quiz, db)
	learningRepo := repos.Learning
	noteRepo := repos.Note
	historyStore := repos.HistoryStore

	// Analytics reads through the same learning-history seam the quiz service
	// uses: the DB-backed store when a database is connected, else the on-disk
	// YAML learning_notes files. The store is applied to yamlAnalyticsRepo
	// below via WithHistoryStore; here we start from the YAML reader.
	yamlAnalyticsRepo := analytics.NewYAMLRepository(cfg.Notebooks.LearningNotesDirectory)
	// Journals are read alongside stories (they share the story format, see
	// quiz.Service.newReader) so a grammar attempt's notebook — a journal —
	// resolves here too; LoadGrammars then attaches the corrections
	// themselves, which resolveGrammar needs to turn a correction id back
	// into its mistake/fix text.
	analyticsStoryDirectories := append(append([]string{}, cfg.Notebooks.StoriesDirectories...), cfg.Notebooks.JournalsDirectories...)
	if reader, err := notebook.NewReader(
		analyticsStoryDirectories,
		cfg.Notebooks.FlashcardsDirectories,
		cfg.Notebooks.BooksDirectories,
		cfg.Notebooks.DefinitionsDirectories,
		cfg.Notebooks.EtymologyDirectories,
		dictionaryMap,
	); err != nil {
		slog.Warn("analytics meaning lookup disabled — notebook reader init failed", "error", err)
	} else if err := reader.LoadGrammars(cfg.Notebooks.GrammarsDirectories); err != nil {
		slog.Warn("analytics grammar meaning lookup disabled — LoadGrammars failed", "error", err)
	} else {
		yamlAnalyticsRepo = yamlAnalyticsRepo.WithMetadataResolver(analytics.NewNotebookMetadataResolver(reader))
	}

	// historyStore is the DB-backed READ side for learning history, non-nil
	// only when a database is connected. It reconstructs the same per-notebook
	// LearningHistory shape the YAML reader produced (notes + learning_logs +
	// skip flags + etymology origins), keyed by the SAME canonical storage key
	// the write path used, so reads stay symmetric with writes (learning-
	// history invariant L2). In YAML-only mode it is nil and the quiz service,
	// notebook handler, and analytics fall back to the on-disk files.
	if historyStore != nil {
		yamlAnalyticsRepo = yamlAnalyticsRepo.WithHistoryStore(historyStore)
		slog.Info("database connected; user-state writes go to the database only (learning_notes YAML frozen at runtime), learning-history reads served from DB")
	}
	analyticsRepo := analytics.Repository(yamlAnalyticsRepo)

	svc := quiz.NewService(cfg.Notebooks, inferenceClient, dictionaryMap, learningRepo, cfg.Quiz)
	// Swap the quiz service's learning-history reads to the DB store when one
	// was built above; a nil store keeps the YAML fallback.
	svc.SetHistoryStore(historyStore)
	// Route the deliberate Exclude action (SkipWord/ResumeWord) to the DB
	// skip-flag tables in DB mode instead of the on-disk learning_notes YAML;
	// nil skip-flag repo keeps the YAML skip path.
	svc.SetSkipStores(repos.SkipFlags, repos.Note, repos.Origin)
	// DB mode: install the ensure-on-serve hook so a notebook whose YAML gained
	// units without a fresh `migrate import-db` still gets its notes rows
	// created additively when its cards are served — self-healing exclude/
	// SkipWord and every other note-keyed DB write. Reuses the same YAML note
	// source + DB note repo the CLI importer uses, but never runs the
	// destructive reconcile pass. YAML-only mode leaves the hook nil.
	if db != nil {
		if ensureReader, rerr := notebook.NewReader(
			cfg.Notebooks.StoriesDirectories,
			cfg.Notebooks.FlashcardsDirectories,
			cfg.Notebooks.BooksDirectories,
			cfg.Notebooks.DefinitionsDirectories,
			cfg.Notebooks.EtymologyDirectories,
			dictionaryMap,
		); rerr != nil {
			slog.Warn("ensure-on-serve disabled — notebook reader init failed", "error", rerr)
		} else {
			noteSource := notebook.NewYAMLNoteRepository(ensureReader)
			ensurer := datasync.NewImporter(noteRepo, nil, noteSource, nil, nil, nil, io.Discard)
			svc.SetNoteEnsurer(ensurer)
		}
	}
	// Enforce notebook public/private visibility on every quiz read path (auth
	// Phase 3). Nil (no DB) keeps every notebook visible.
	svc.SetNotebookACL(repos.ACL)

	dictConfig := dictionary.Config{
		RapidAPIHost: cfg.Dictionaries.RapidAPI.Host,
		RapidAPIKey:  cfg.Dictionaries.RapidAPI.Key,
	}
	dictReader := dictionary.NewReader(cfg.Dictionaries.RapidAPI.CacheDirectory, dictConfig)
	notebookHandler := server.NewNotebookHandler(cfg.Notebooks, cfg.Templates, dictionaryMap, dictReader, inferenceClient, noteRepo)
	// Serve the Learn page's learning-history reads (status / next-review /
	// exclusion badges) from the DB too, so they stay fresh once the on-disk
	// learning_notes YAML is frozen in DB mode. Nil keeps the YAML fallback.
	notebookHandler.SetHistoryStore(historyStore)
	// Hard-reject a private notebook the requesting user can't see on the Learn
	// page's detail / etymology / PDF paths (auth Phase 3). Nil keeps every
	// notebook visible (no DB).
	notebookHandler.SetNotebookACL(repos.ACL)

	handler := server.NewQuizHandler(svc)
	handler.SetNoteRepository(noteRepo)
	analyticsHandler := server.NewAnalyticsHandler(analyticsRepo)

	// The auth interceptor rejects any RPC lacking a verified session (populated
	// in request ctx by AuthBearerMiddleware). It is appended UNCONDITIONALLY —
	// auth is always on (design §2).
	interceptors := []connect.Interceptor{loggingInterceptor, server.NewAuthInterceptor()}
	handlerOpts := connect.WithInterceptors(interceptors...)
	path, h := apiv1connect.NewQuizServiceHandler(handler, handlerOpts)
	notebookPath, notebookH := apiv1connect.NewNotebookServiceHandler(notebookHandler, handlerOpts)
	analyticsPath, analyticsH := apiv1connect.NewAnalyticsServiceHandler(analyticsHandler, handlerOpts)

	mux := http.NewServeMux()
	mux.Handle(path, h)
	mux.Handle(notebookPath, notebookH)
	mux.Handle(analyticsPath, analyticsH)

	// Auth endpoints are plain HTTP, registered OUTSIDE the connect interceptor
	// so an unauthenticated user/CLI can sign in. The web sign-in mints a bearer
	// (fragment redirect); the device endpoints drive the CLI flow. Device
	// approval happens INSIDE /auth/google/callback (no /auth/device/approve).
	mux.HandleFunc("/auth/google/login", authSetup.handler.Login)
	mux.HandleFunc("/auth/google/callback", authSetup.handler.Callback)
	mux.HandleFunc("/auth/logout", authSetup.handler.Logout)
	mux.HandleFunc("/auth/me", authSetup.handler.Me)
	mux.HandleFunc("/auth/device/code", authSetup.deviceHandler.RequestCode)
	mux.HandleFunc("/auth/device/token", authSetup.deviceHandler.Token)
	mux.HandleFunc("/auth/device/deny", authSetup.deviceHandler.Deny)
	mux.HandleFunc("/auth/device", authSetup.deviceHandler.ShowApprovalPage)
	mux.HandleFunc("/auth/token/refresh", authSetup.deviceHandler.Refresh)
	mux.HandleFunc("/auth/token/revoke", authSetup.deviceHandler.Revoke)

	rootHandler := h2c.NewHandler(mux, &http2.Server{})
	// The ONLY auth path: populate the request context from the bearer access
	// token for both the connect interceptor and /auth/me. Never rejects —
	// /auth/* and CORS preflight pass through; the interceptor gates RPCs.
	rootHandler = server.AuthBearerMiddleware(rootHandler, authSetup.tokens)

	srv := &http.Server{
		Addr:    fmt.Sprintf(":%d", cfg.Server.Port),
		Handler: corsMiddleware(rootHandler, cfg.Server.CORS.AllowedOrigins),
	}
	app.AddShutdownHook(srv.Shutdown)

	// Lightweight periodic sweep of expired device-authorization rows (design
	// §5). Cheap: the expires_at index supports it. Stops with ctx.
	go sweepExpiredDeviceCodes(ctx, authSetup.deviceCodes)

	return app.Run(ctx, func(ctx context.Context) error {
		slog.Info("starting server", "addr", srv.Addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			return err
		}
		return nil
	})
}

// sweepExpiredDeviceCodes deletes expired device rows every 10 minutes until
// ctx is cancelled.
func sweepExpiredDeviceCodes(ctx context.Context, repo *auth.CLIDeviceCodeRepository) {
	ticker := time.NewTicker(10 * time.Minute)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			if n, err := repo.DeleteExpired(ctx, time.Now()); err != nil {
				slog.Warn("device: sweep expired codes failed", "error", err)
			} else if n > 0 {
				slog.Debug("device: swept expired codes", "deleted", n)
			}
		}
	}
}

func loadConfig() (*config.Config, error) {
	loader, err := config.NewConfigLoader(configFile)
	if err != nil {
		return nil, fmt.Errorf("config.NewConfigLoader() > %w", err)
	}
	return loader.Load()
}

func loadDictionaryMap(cacheDir string) (map[string]rapidapi.Response, error) {
	responses, err := rapidapi.NewReader().Read(cacheDir)
	if err != nil {
		return nil, fmt.Errorf("rapidapi.NewReader().Read() > %w", err)
	}
	return rapidapi.FromResponsesToMap(responses), nil
}

// authComponents holds the pieces main wires for always-on bearer auth: the
// OAuth/web-token handler, the device-flow handler, the shared access-token
// signer, and the device-code repository (for the expiry sweeper).
type authComponents struct {
	handler       *server.AuthHandler
	deviceHandler *server.DeviceAuthHandler
	tokens        *auth.TokenSigner
	deviceCodes   *auth.CLIDeviceCodeRepository
}

// buildAuth constructs the OAuth/web-token handler, the device-flow handler,
// the single access-token signer (TOKEN_SIGNING_KEY, which also keys the OAuth
// state signer), and the CLI repositories. It fails fast when the database or
// TOKEN_SIGNING_KEY is missing, so a misconfigured deployment never starts
// silently ungated (design §2).
func buildAuth(cfg *config.Config, db *sqlx.DB) (*authComponents, error) {
	if db == nil {
		return nil, errors.New("auth requires a database (users / device-flow rows live in Postgres) — set database.* and DB_PASSWORD")
	}
	key := auth.DecodeKey(cfg.Auth.TokenSigningKey)
	tokens, err := auth.NewTokenSigner(key)
	if err != nil {
		return nil, fmt.Errorf("TOKEN_SIGNING_KEY is required: %w", err)
	}
	state, err := auth.NewStateSigner(key)
	if err != nil {
		return nil, fmt.Errorf("state signing key: %w", err)
	}
	users := auth.NewUserRepository(db)
	deviceCodes := auth.NewCLIDeviceCodeRepository(db)
	refreshTokens := auth.NewCLIRefreshTokenRepository(db)
	authenticator := auth.NewOAuthClient(cfg.Auth.GoogleClientID, cfg.Auth.GoogleClientSecret, cfg.Auth.RedirectURL, nil)
	handler := server.NewAuthHandler(server.AuthHandlerConfig{
		Authenticator:  authenticator,
		Tokens:         tokens,
		State:          state,
		Users:          users,
		DeviceCodes:    deviceCodes,
		AllowedEmails:  cfg.Auth.AllowedEmails,
		FrontendURL:    cfg.Auth.FrontendURL,
		AllowedOrigins: cfg.Server.CORS.AllowedOrigins,
		CookieSecure:   cfg.Auth.CookieSecure,
		CookieSameSite: parseSameSite(cfg.Auth.CookieSameSite),
	})
	deviceHandler := server.NewDeviceAuthHandler(server.DeviceAuthHandlerConfig{
		DeviceCodes:     deviceCodes,
		RefreshTokens:   refreshTokens,
		Tokens:          tokens,
		FrontendURL:     cfg.Auth.FrontendURL,
		VerificationURI: deviceVerificationURI(cfg.Auth.RedirectURL),
	})
	return &authComponents{handler: handler, deviceHandler: deviceHandler, tokens: tokens, deviceCodes: deviceCodes}, nil
}

// deviceVerificationURI derives the browser approval URL (…/auth/device) from
// the OAuth redirect_url's origin. The redirect_url is the API host the browser
// already returns to, so its scheme+host is the right base. Falls back to a
// bare path if the redirect_url can't be parsed.
func deviceVerificationURI(redirectURL string) string {
	u, err := url.Parse(redirectURL)
	if err != nil || u.Scheme == "" || u.Host == "" {
		return "/auth/device"
	}
	return u.Scheme + "://" + u.Host + "/auth/device"
}

func parseSameSite(s string) http.SameSite {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "strict":
		return http.SameSiteStrictMode
	case "none":
		return http.SameSiteNoneMode
	default:
		return http.SameSiteLaxMode
	}
}

// corsMiddleware serves explicit CORS for bearer-authenticated RPCs. Auth is a
// header (`Authorization: Bearer`), not a cookie, so NO
// Access-Control-Allow-Credentials is sent — the browser presents the bearer
// from a different origin (frontend 3100 ↔ backend 8080). It reflects the
// request Origin when it is configured (or when "*" is configured as a
// wildcard) and always allows the Authorization header.
func corsMiddleware(next http.Handler, allowedOrigins []string) http.Handler {
	allowAll := false
	allowed := make(map[string]bool, len(allowedOrigins))
	for _, o := range allowedOrigins {
		if o == "*" {
			allowAll = true
			break
		}
		allowed[o] = true
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")
		if origin != "" && (allowAll || allowed[origin]) {
			w.Header().Set("Access-Control-Allow-Origin", origin)
			w.Header().Set("Vary", "Origin")
		}
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Connect-Protocol-Version, Authorization")
		w.Header().Set("Access-Control-Max-Age", "3600")

		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}

		next.ServeHTTP(w, r)
	})
}
