// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/analytics.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/at-ishikawa/langner/gen-protos/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "api.v1.AnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticsServiceGetDailySummariesProcedure is the fully-qualified name of the AnalyticsService's
	// GetDailySummaries RPC.
	AnalyticsServiceGetDailySummariesProcedure = "/api.v1.AnalyticsService/GetDailySummaries"
	// AnalyticsServiceGetDayDetailProcedure is the fully-qualified name of the AnalyticsService's
	// GetDayDetail RPC.
	AnalyticsServiceGetDayDetailProcedure = "/api.v1.AnalyticsService/GetDayDetail"
	// AnalyticsServiceGetWordHistoryProcedure is the fully-qualified name of the AnalyticsService's
	// GetWordHistory RPC.
	AnalyticsServiceGetWordHistoryProcedure = "/api.v1.AnalyticsService/GetWordHistory"
)

// AnalyticsServiceClient is a client for the api.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	// GetDailySummaries returns one row per day with quiz activity in the
	// requested range, newest first. Each row carries the per-day rollup
	// shown on the Day List page.
	GetDailySummaries(context.Context, *connect.Request[v1.GetDailySummariesRequest]) (*connect.Response[v1.GetDailySummariesResponse], error)
	// GetDayDetail returns the words answered wrong on a specific day plus
	// the per-day rollup. Used by the Day Detail page.
	GetDayDetail(context.Context, *connect.Request[v1.GetDayDetailRequest]) (*connect.Response[v1.GetDayDetailResponse], error)
	// GetWordHistory returns every attempt for one (note_id, quiz_type)
	// pair, newest first, with the streak counts immediately before each
	// attempt. Used when the user expands a word card on the Day Detail
	// page.
	GetWordHistory(context.Context, *connect.Request[v1.GetWordHistoryRequest]) (*connect.Response[v1.GetWordHistoryResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the api.v1.AnalyticsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := v1.File_api_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		getDailySummaries: connect.NewClient[v1.GetDailySummariesRequest, v1.GetDailySummariesResponse](
			httpClient,
			baseURL+AnalyticsServiceGetDailySummariesProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetDailySummaries")),
			connect.WithClientOptions(opts...),
		),
		getDayDetail: connect.NewClient[v1.GetDayDetailRequest, v1.GetDayDetailResponse](
			httpClient,
			baseURL+AnalyticsServiceGetDayDetailProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetDayDetail")),
			connect.WithClientOptions(opts...),
		),
		getWordHistory: connect.NewClient[v1.GetWordHistoryRequest, v1.GetWordHistoryResponse](
			httpClient,
			baseURL+AnalyticsServiceGetWordHistoryProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetWordHistory")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	getDailySummaries *connect.Client[v1.GetDailySummariesRequest, v1.GetDailySummariesResponse]
	getDayDetail      *connect.Client[v1.GetDayDetailRequest, v1.GetDayDetailResponse]
	getWordHistory    *connect.Client[v1.GetWordHistoryRequest, v1.GetWordHistoryResponse]
}

// GetDailySummaries calls api.v1.AnalyticsService.GetDailySummaries.
func (c *analyticsServiceClient) GetDailySummaries(ctx context.Context, req *connect.Request[v1.GetDailySummariesRequest]) (*connect.Response[v1.GetDailySummariesResponse], error) {
	return c.getDailySummaries.CallUnary(ctx, req)
}

// GetDayDetail calls api.v1.AnalyticsService.GetDayDetail.
func (c *analyticsServiceClient) GetDayDetail(ctx context.Context, req *connect.Request[v1.GetDayDetailRequest]) (*connect.Response[v1.GetDayDetailResponse], error) {
	return c.getDayDetail.CallUnary(ctx, req)
}

// GetWordHistory calls api.v1.AnalyticsService.GetWordHistory.
func (c *analyticsServiceClient) GetWordHistory(ctx context.Context, req *connect.Request[v1.GetWordHistoryRequest]) (*connect.Response[v1.GetWordHistoryResponse], error) {
	return c.getWordHistory.CallUnary(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the api.v1.AnalyticsService service.
type AnalyticsServiceHandler interface {
	// GetDailySummaries returns one row per day with quiz activity in the
	// requested range, newest first. Each row carries the per-day rollup
	// shown on the Day List page.
	GetDailySummaries(context.Context, *connect.Request[v1.GetDailySummariesRequest]) (*connect.Response[v1.GetDailySummariesResponse], error)
	// GetDayDetail returns the words answered wrong on a specific day plus
	// the per-day rollup. Used by the Day Detail page.
	GetDayDetail(context.Context, *connect.Request[v1.GetDayDetailRequest]) (*connect.Response[v1.GetDayDetailResponse], error)
	// GetWordHistory returns every attempt for one (note_id, quiz_type)
	// pair, newest first, with the streak counts immediately before each
	// attempt. Used when the user expands a word card on the Day Detail
	// page.
	GetWordHistory(context.Context, *connect.Request[v1.GetWordHistoryRequest]) (*connect.Response[v1.GetWordHistoryResponse], error)
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := v1.File_api_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceGetDailySummariesHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetDailySummariesProcedure,
		svc.GetDailySummaries,
		connect.WithSchema(analyticsServiceMethods.ByName("GetDailySummaries")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetDayDetailHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetDayDetailProcedure,
		svc.GetDayDetail,
		connect.WithSchema(analyticsServiceMethods.ByName("GetDayDetail")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetWordHistoryHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetWordHistoryProcedure,
		svc.GetWordHistory,
		connect.WithSchema(analyticsServiceMethods.ByName("GetWordHistory")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceGetDailySummariesProcedure:
			analyticsServiceGetDailySummariesHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetDayDetailProcedure:
			analyticsServiceGetDayDetailHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetWordHistoryProcedure:
			analyticsServiceGetWordHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) GetDailySummaries(context.Context, *connect.Request[v1.GetDailySummariesRequest]) (*connect.Response[v1.GetDailySummariesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AnalyticsService.GetDailySummaries is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetDayDetail(context.Context, *connect.Request[v1.GetDayDetailRequest]) (*connect.Response[v1.GetDayDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AnalyticsService.GetDayDetail is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetWordHistory(context.Context, *connect.Request[v1.GetWordHistoryRequest]) (*connect.Response[v1.GetWordHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.AnalyticsService.GetWordHistory is not implemented"))
}
