// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/notebook.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/at-ishikawa/langner/gen-protos/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotebookServiceName is the fully-qualified name of the NotebookService service.
	NotebookServiceName = "api.v1.NotebookService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotebookServiceGetNotebookDetailProcedure is the fully-qualified name of the NotebookService's
	// GetNotebookDetail RPC.
	NotebookServiceGetNotebookDetailProcedure = "/api.v1.NotebookService/GetNotebookDetail"
	// NotebookServiceExportNotebookPDFProcedure is the fully-qualified name of the NotebookService's
	// ExportNotebookPDF RPC.
	NotebookServiceExportNotebookPDFProcedure = "/api.v1.NotebookService/ExportNotebookPDF"
)

// NotebookServiceClient is a client for the api.v1.NotebookService service.
type NotebookServiceClient interface {
	GetNotebookDetail(context.Context, *connect.Request[v1.GetNotebookDetailRequest]) (*connect.Response[v1.GetNotebookDetailResponse], error)
	ExportNotebookPDF(context.Context, *connect.Request[v1.ExportNotebookPDFRequest]) (*connect.Response[v1.ExportNotebookPDFResponse], error)
}

// NewNotebookServiceClient constructs a client for the api.v1.NotebookService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotebookServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotebookServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notebookServiceMethods := v1.File_api_v1_notebook_proto.Services().ByName("NotebookService").Methods()
	return &notebookServiceClient{
		getNotebookDetail: connect.NewClient[v1.GetNotebookDetailRequest, v1.GetNotebookDetailResponse](
			httpClient,
			baseURL+NotebookServiceGetNotebookDetailProcedure,
			connect.WithSchema(notebookServiceMethods.ByName("GetNotebookDetail")),
			connect.WithClientOptions(opts...),
		),
		exportNotebookPDF: connect.NewClient[v1.ExportNotebookPDFRequest, v1.ExportNotebookPDFResponse](
			httpClient,
			baseURL+NotebookServiceExportNotebookPDFProcedure,
			connect.WithSchema(notebookServiceMethods.ByName("ExportNotebookPDF")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notebookServiceClient implements NotebookServiceClient.
type notebookServiceClient struct {
	getNotebookDetail *connect.Client[v1.GetNotebookDetailRequest, v1.GetNotebookDetailResponse]
	exportNotebookPDF *connect.Client[v1.ExportNotebookPDFRequest, v1.ExportNotebookPDFResponse]
}

// GetNotebookDetail calls api.v1.NotebookService.GetNotebookDetail.
func (c *notebookServiceClient) GetNotebookDetail(ctx context.Context, req *connect.Request[v1.GetNotebookDetailRequest]) (*connect.Response[v1.GetNotebookDetailResponse], error) {
	return c.getNotebookDetail.CallUnary(ctx, req)
}

// ExportNotebookPDF calls api.v1.NotebookService.ExportNotebookPDF.
func (c *notebookServiceClient) ExportNotebookPDF(ctx context.Context, req *connect.Request[v1.ExportNotebookPDFRequest]) (*connect.Response[v1.ExportNotebookPDFResponse], error) {
	return c.exportNotebookPDF.CallUnary(ctx, req)
}

// NotebookServiceHandler is an implementation of the api.v1.NotebookService service.
type NotebookServiceHandler interface {
	GetNotebookDetail(context.Context, *connect.Request[v1.GetNotebookDetailRequest]) (*connect.Response[v1.GetNotebookDetailResponse], error)
	ExportNotebookPDF(context.Context, *connect.Request[v1.ExportNotebookPDFRequest]) (*connect.Response[v1.ExportNotebookPDFResponse], error)
}

// NewNotebookServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotebookServiceHandler(svc NotebookServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notebookServiceMethods := v1.File_api_v1_notebook_proto.Services().ByName("NotebookService").Methods()
	notebookServiceGetNotebookDetailHandler := connect.NewUnaryHandler(
		NotebookServiceGetNotebookDetailProcedure,
		svc.GetNotebookDetail,
		connect.WithSchema(notebookServiceMethods.ByName("GetNotebookDetail")),
		connect.WithHandlerOptions(opts...),
	)
	notebookServiceExportNotebookPDFHandler := connect.NewUnaryHandler(
		NotebookServiceExportNotebookPDFProcedure,
		svc.ExportNotebookPDF,
		connect.WithSchema(notebookServiceMethods.ByName("ExportNotebookPDF")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.NotebookService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotebookServiceGetNotebookDetailProcedure:
			notebookServiceGetNotebookDetailHandler.ServeHTTP(w, r)
		case NotebookServiceExportNotebookPDFProcedure:
			notebookServiceExportNotebookPDFHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotebookServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotebookServiceHandler struct{}

func (UnimplementedNotebookServiceHandler) GetNotebookDetail(context.Context, *connect.Request[v1.GetNotebookDetailRequest]) (*connect.Response[v1.GetNotebookDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.NotebookService.GetNotebookDetail is not implemented"))
}

func (UnimplementedNotebookServiceHandler) ExportNotebookPDF(context.Context, *connect.Request[v1.ExportNotebookPDFRequest]) (*connect.Response[v1.ExportNotebookPDFResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.NotebookService.ExportNotebookPDF is not implemented"))
}
