// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/analytics.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalyticsFilters carries the optional notebook + quiz-type filters used
// on both the Day List and Day Detail pages.
type AnalyticsFilters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notebook_id, when non-empty, restricts results to a single notebook.
	NotebookId string `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	// quiz_type, when non-empty, restricts results to a single quiz type
	// (e.g. "notebook", "etymology_breakdown"). Empty means all types.
	QuizType      string `protobuf:"bytes,2,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsFilters) Reset() {
	*x = AnalyticsFilters{}
	mi := &file_api_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsFilters) ProtoMessage() {}

func (x *AnalyticsFilters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsFilters.ProtoReflect.Descriptor instead.
func (*AnalyticsFilters) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsFilters) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *AnalyticsFilters) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

type GetDailySummariesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// range_days bounds the window: only days within now()-range_days are
	// returned. Zero means "all time".
	RangeDays     int32             `protobuf:"varint,1,opt,name=range_days,json=rangeDays,proto3" json:"range_days,omitempty"`
	Filters       *AnalyticsFilters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummariesRequest) Reset() {
	*x = GetDailySummariesRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummariesRequest) ProtoMessage() {}

func (x *GetDailySummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummariesRequest.ProtoReflect.Descriptor instead.
func (*GetDailySummariesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetDailySummariesRequest) GetRangeDays() int32 {
	if x != nil {
		return x.RangeDays
	}
	return 0
}

func (x *GetDailySummariesRequest) GetFilters() *AnalyticsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetDailySummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*DailySummary        `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummariesResponse) Reset() {
	*x = GetDailySummariesResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummariesResponse) ProtoMessage() {}

func (x *GetDailySummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummariesResponse.ProtoReflect.Descriptor instead.
func (*GetDailySummariesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetDailySummariesResponse) GetDays() []*DailySummary {
	if x != nil {
		return x.Days
	}
	return nil
}

// DailySummary is one row on the Day List.
type DailySummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in YYYY-MM-DD format.
	Date          string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	WrongCount    int32  `protobuf:"varint,2,opt,name=wrong_count,json=wrongCount,proto3" json:"wrong_count,omitempty"`
	TotalCount    int32  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NotebookCount int32  `protobuf:"varint,4,opt,name=notebook_count,json=notebookCount,proto3" json:"notebook_count,omitempty"`
	// quiz_types lists every quiz type that produced an attempt on this
	// day (e.g. ["notebook", "reverse", "etymology_breakdown"]).
	QuizTypes     []string `protobuf:"bytes,5,rep,name=quiz_types,json=quizTypes,proto3" json:"quiz_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySummary) Reset() {
	*x = DailySummary{}
	mi := &file_api_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySummary) ProtoMessage() {}

func (x *DailySummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySummary.ProtoReflect.Descriptor instead.
func (*DailySummary) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DailySummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailySummary) GetWrongCount() int32 {
	if x != nil {
		return x.WrongCount
	}
	return 0
}

func (x *DailySummary) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *DailySummary) GetNotebookCount() int32 {
	if x != nil {
		return x.NotebookCount
	}
	return 0
}

func (x *DailySummary) GetQuizTypes() []string {
	if x != nil {
		return x.QuizTypes
	}
	return nil
}

type GetDayDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in YYYY-MM-DD format.
	Date          string            `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Filters       *AnalyticsFilters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayDetailRequest) Reset() {
	*x = GetDayDetailRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayDetailRequest) ProtoMessage() {}

func (x *GetDayDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDayDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetDayDetailRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDayDetailRequest) GetFilters() *AnalyticsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetDayDetailResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Summary    *DailySummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	WrongWords []*WrongWord           `protobuf:"bytes,2,rep,name=wrong_words,json=wrongWords,proto3" json:"wrong_words,omitempty"`
	// previous_date and next_date are the adjacent days with quiz activity
	// matching the current filters, in YYYY-MM-DD format. Empty when no
	// adjacent day exists.
	PreviousDate  string `protobuf:"bytes,3,opt,name=previous_date,json=previousDate,proto3" json:"previous_date,omitempty"`
	NextDate      string `protobuf:"bytes,4,opt,name=next_date,json=nextDate,proto3" json:"next_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayDetailResponse) Reset() {
	*x = GetDayDetailResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayDetailResponse) ProtoMessage() {}

func (x *GetDayDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayDetailResponse.ProtoReflect.Descriptor instead.
func (*GetDayDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetDayDetailResponse) GetSummary() *DailySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetDayDetailResponse) GetWrongWords() []*WrongWord {
	if x != nil {
		return x.WrongWords
	}
	return nil
}

func (x *GetDayDetailResponse) GetPreviousDate() string {
	if x != nil {
		return x.PreviousDate
	}
	return ""
}

func (x *GetDayDetailResponse) GetNextDate() string {
	if x != nil {
		return x.NextDate
	}
	return ""
}

// WrongWord is one (word × quiz_type) attempt the user got wrong on the
// requested day, plus enough surrounding context to render the card.
type WrongWord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// note_id is the DB row id of the word. Zero when YAML-only.
	NoteId        int64  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	NotebookId    string `protobuf:"bytes,3,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	NotebookTitle string `protobuf:"bytes,4,opt,name=notebook_title,json=notebookTitle,proto3" json:"notebook_title,omitempty"`
	SceneTitle    string `protobuf:"bytes,5,opt,name=scene_title,json=sceneTitle,proto3" json:"scene_title,omitempty"`
	// quiz_type uses the same string values as LearningRecord.QuizType
	// (e.g. "notebook", "reverse", "etymology_breakdown").
	QuizType string `protobuf:"bytes,6,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	// recent_pattern is the last 5 attempts for this (word, quiz_type),
	// newest LAST so the row reads left-to-right. Each entry is one of
	// "correct", "wrong" or "none".
	RecentPattern []string `protobuf:"bytes,7,rep,name=recent_pattern,json=recentPattern,proto3" json:"recent_pattern,omitempty"`
	// current_wrong_streak counts consecutive wrong attempts ending at the
	// attempt on this day.
	CurrentWrongStreak int32 `protobuf:"varint,8,opt,name=current_wrong_streak,json=currentWrongStreak,proto3" json:"current_wrong_streak,omitempty"`
	// previous_correct_streak counts consecutive correct attempts
	// immediately before the current wrong streak (0 when the current
	// wrong streak starts from the very first attempt).
	PreviousCorrectStreak int32 `protobuf:"varint,9,opt,name=previous_correct_streak,json=previousCorrectStreak,proto3" json:"previous_correct_streak,omitempty"`
	// current_status is the learning status after the attempt on this day.
	CurrentStatus string `protobuf:"bytes,10,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrongWord) Reset() {
	*x = WrongWord{}
	mi := &file_api_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrongWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrongWord) ProtoMessage() {}

func (x *WrongWord) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrongWord.ProtoReflect.Descriptor instead.
func (*WrongWord) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *WrongWord) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *WrongWord) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *WrongWord) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *WrongWord) GetNotebookTitle() string {
	if x != nil {
		return x.NotebookTitle
	}
	return ""
}

func (x *WrongWord) GetSceneTitle() string {
	if x != nil {
		return x.SceneTitle
	}
	return ""
}

func (x *WrongWord) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *WrongWord) GetRecentPattern() []string {
	if x != nil {
		return x.RecentPattern
	}
	return nil
}

func (x *WrongWord) GetCurrentWrongStreak() int32 {
	if x != nil {
		return x.CurrentWrongStreak
	}
	return 0
}

func (x *WrongWord) GetPreviousCorrectStreak() int32 {
	if x != nil {
		return x.PreviousCorrectStreak
	}
	return 0
}

func (x *WrongWord) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

type GetWordHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	NotebookId    string                 `protobuf:"bytes,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Expression    string                 `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	QuizType      string                 `protobuf:"bytes,4,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordHistoryRequest) Reset() {
	*x = GetWordHistoryRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordHistoryRequest) ProtoMessage() {}

func (x *GetWordHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWordHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetWordHistoryRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GetWordHistoryRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *GetWordHistoryRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GetWordHistoryRequest) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

type GetWordHistoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Expression         string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	NotebookId         string                 `protobuf:"bytes,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	NotebookTitle      string                 `protobuf:"bytes,3,opt,name=notebook_title,json=notebookTitle,proto3" json:"notebook_title,omitempty"`
	CurrentStatus      string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	CurrentWrongStreak int32                  `protobuf:"varint,5,opt,name=current_wrong_streak,json=currentWrongStreak,proto3" json:"current_wrong_streak,omitempty"`
	Attempts           []*AttemptEntry        `protobuf:"bytes,6,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWordHistoryResponse) Reset() {
	*x = GetWordHistoryResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordHistoryResponse) ProtoMessage() {}

func (x *GetWordHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWordHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetWordHistoryResponse) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GetWordHistoryResponse) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *GetWordHistoryResponse) GetNotebookTitle() string {
	if x != nil {
		return x.NotebookTitle
	}
	return ""
}

func (x *GetWordHistoryResponse) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *GetWordHistoryResponse) GetCurrentWrongStreak() int32 {
	if x != nil {
		return x.CurrentWrongStreak
	}
	return 0
}

func (x *GetWordHistoryResponse) GetAttempts() []*AttemptEntry {
	if x != nil {
		return x.Attempts
	}
	return nil
}

// AttemptEntry is a single past attempt with the streak context just
// before it.
type AttemptEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in YYYY-MM-DD format.
	Date     string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	QuizType string `protobuf:"bytes,2,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	// result is "correct" or "wrong".
	Result  string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Quality int32  `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`
	// streak_before_wrong / streak_before_correct describe the run that
	// ended at this attempt. Exactly one is non-zero. Both zero means
	// this was the very first attempt.
	StreakBeforeWrong   int32 `protobuf:"varint,5,opt,name=streak_before_wrong,json=streakBeforeWrong,proto3" json:"streak_before_wrong,omitempty"`
	StreakBeforeCorrect int32 `protobuf:"varint,6,opt,name=streak_before_correct,json=streakBeforeCorrect,proto3" json:"streak_before_correct,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttemptEntry) Reset() {
	*x = AttemptEntry{}
	mi := &file_api_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptEntry) ProtoMessage() {}

func (x *AttemptEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptEntry.ProtoReflect.Descriptor instead.
func (*AttemptEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *AttemptEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AttemptEntry) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *AttemptEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AttemptEntry) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *AttemptEntry) GetStreakBeforeWrong() int32 {
	if x != nil {
		return x.StreakBeforeWrong
	}
	return 0
}

func (x *AttemptEntry) GetStreakBeforeCorrect() int32 {
	if x != nil {
		return x.StreakBeforeCorrect
	}
	return 0
}

var File_api_v1_analytics_proto protoreflect.FileDescriptor

const file_api_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/analytics.proto\x12\x06api.v1\x1a\x1bbuf/validate/validate.proto\"P\n" +
	"\x10AnalyticsFilters\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\tR\n" +
	"notebookId\x12\x1b\n" +
	"\tquiz_type\x18\x02 \x01(\tR\bquizType\"v\n" +
	"\x18GetDailySummariesRequest\x12&\n" +
	"\n" +
	"range_days\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\trangeDays\x122\n" +
	"\afilters\x18\x02 \x01(\v2\x18.api.v1.AnalyticsFiltersR\afilters\"E\n" +
	"\x19GetDailySummariesResponse\x12(\n" +
	"\x04days\x18\x01 \x03(\v2\x14.api.v1.DailySummaryR\x04days\"\xaa\x01\n" +
	"\fDailySummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vwrong_count\x18\x02 \x01(\x05R\n" +
	"wrongCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12%\n" +
	"\x0enotebook_count\x18\x04 \x01(\x05R\rnotebookCount\x12\x1d\n" +
	"\n" +
	"quiz_types\x18\x05 \x03(\tR\tquizTypes\"f\n" +
	"\x13GetDayDetailRequest\x12\x1b\n" +
	"\x04date\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04date\x122\n" +
	"\afilters\x18\x02 \x01(\v2\x18.api.v1.AnalyticsFiltersR\afilters\"\xbc\x01\n" +
	"\x14GetDayDetailResponse\x12.\n" +
	"\asummary\x18\x01 \x01(\v2\x14.api.v1.DailySummaryR\asummary\x122\n" +
	"\vwrong_words\x18\x02 \x03(\v2\x11.api.v1.WrongWordR\n" +
	"wrongWords\x12#\n" +
	"\rprevious_date\x18\x03 \x01(\tR\fpreviousDate\x12\x1b\n" +
	"\tnext_date\x18\x04 \x01(\tR\bnextDate\"\x82\x03\n" +
	"\tWrongWord\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1f\n" +
	"\vnotebook_id\x18\x03 \x01(\tR\n" +
	"notebookId\x12%\n" +
	"\x0enotebook_title\x18\x04 \x01(\tR\rnotebookTitle\x12\x1f\n" +
	"\vscene_title\x18\x05 \x01(\tR\n" +
	"sceneTitle\x12\x1b\n" +
	"\tquiz_type\x18\x06 \x01(\tR\bquizType\x12%\n" +
	"\x0erecent_pattern\x18\a \x03(\tR\rrecentPattern\x120\n" +
	"\x14current_wrong_streak\x18\b \x01(\x05R\x12currentWrongStreak\x126\n" +
	"\x17previous_correct_streak\x18\t \x01(\x05R\x15previousCorrectStreak\x12%\n" +
	"\x0ecurrent_status\x18\n" +
	" \x01(\tR\rcurrentStatus\"\xa0\x01\n" +
	"\x15GetWordHistoryRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\tR\n" +
	"notebookId\x12'\n" +
	"\n" +
	"expression\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"expression\x12$\n" +
	"\tquiz_type\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bquizType\"\x8b\x02\n" +
	"\x16GetWordHistoryResponse\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\tR\n" +
	"notebookId\x12%\n" +
	"\x0enotebook_title\x18\x03 \x01(\tR\rnotebookTitle\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\x120\n" +
	"\x14current_wrong_streak\x18\x05 \x01(\x05R\x12currentWrongStreak\x120\n" +
	"\battempts\x18\x06 \x03(\v2\x14.api.v1.AttemptEntryR\battempts\"\xd5\x01\n" +
	"\fAttemptEntry\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1b\n" +
	"\tquiz_type\x18\x02 \x01(\tR\bquizType\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x05R\aquality\x12.\n" +
	"\x13streak_before_wrong\x18\x05 \x01(\x05R\x11streakBeforeWrong\x122\n" +
	"\x15streak_before_correct\x18\x06 \x01(\x05R\x13streakBeforeCorrect2\x88\x02\n" +
	"\x10AnalyticsService\x12X\n" +
	"\x11GetDailySummaries\x12 .api.v1.GetDailySummariesRequest\x1a!.api.v1.GetDailySummariesResponse\x12I\n" +
	"\fGetDayDetail\x12\x1b.api.v1.GetDayDetailRequest\x1a\x1c.api.v1.GetDayDetailResponse\x12O\n" +
	"\x0eGetWordHistory\x12\x1d.api.v1.GetWordHistoryRequest\x1a\x1e.api.v1.GetWordHistoryResponseB8Z6github.com/at-ishikawa/langner/gen-protos/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_analytics_proto_rawDescOnce sync.Once
	file_api_v1_analytics_proto_rawDescData []byte
)

func file_api_v1_analytics_proto_rawDescGZIP() []byte {
	file_api_v1_analytics_proto_rawDescOnce.Do(func() {
		file_api_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_analytics_proto_rawDesc), len(file_api_v1_analytics_proto_rawDesc)))
	})
	return file_api_v1_analytics_proto_rawDescData
}

var file_api_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_analytics_proto_goTypes = []any{
	(*AnalyticsFilters)(nil),          // 0: api.v1.AnalyticsFilters
	(*GetDailySummariesRequest)(nil),  // 1: api.v1.GetDailySummariesRequest
	(*GetDailySummariesResponse)(nil), // 2: api.v1.GetDailySummariesResponse
	(*DailySummary)(nil),              // 3: api.v1.DailySummary
	(*GetDayDetailRequest)(nil),       // 4: api.v1.GetDayDetailRequest
	(*GetDayDetailResponse)(nil),      // 5: api.v1.GetDayDetailResponse
	(*WrongWord)(nil),                 // 6: api.v1.WrongWord
	(*GetWordHistoryRequest)(nil),     // 7: api.v1.GetWordHistoryRequest
	(*GetWordHistoryResponse)(nil),    // 8: api.v1.GetWordHistoryResponse
	(*AttemptEntry)(nil),              // 9: api.v1.AttemptEntry
}
var file_api_v1_analytics_proto_depIdxs = []int32{
	0, // 0: api.v1.GetDailySummariesRequest.filters:type_name -> api.v1.AnalyticsFilters
	3, // 1: api.v1.GetDailySummariesResponse.days:type_name -> api.v1.DailySummary
	0, // 2: api.v1.GetDayDetailRequest.filters:type_name -> api.v1.AnalyticsFilters
	3, // 3: api.v1.GetDayDetailResponse.summary:type_name -> api.v1.DailySummary
	6, // 4: api.v1.GetDayDetailResponse.wrong_words:type_name -> api.v1.WrongWord
	9, // 5: api.v1.GetWordHistoryResponse.attempts:type_name -> api.v1.AttemptEntry
	1, // 6: api.v1.AnalyticsService.GetDailySummaries:input_type -> api.v1.GetDailySummariesRequest
	4, // 7: api.v1.AnalyticsService.GetDayDetail:input_type -> api.v1.GetDayDetailRequest
	7, // 8: api.v1.AnalyticsService.GetWordHistory:input_type -> api.v1.GetWordHistoryRequest
	2, // 9: api.v1.AnalyticsService.GetDailySummaries:output_type -> api.v1.GetDailySummariesResponse
	5, // 10: api.v1.AnalyticsService.GetDayDetail:output_type -> api.v1.GetDayDetailResponse
	8, // 11: api.v1.AnalyticsService.GetWordHistory:output_type -> api.v1.GetWordHistoryResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_analytics_proto_init() }
func file_api_v1_analytics_proto_init() {
	if File_api_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_analytics_proto_rawDesc), len(file_api_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_analytics_proto_goTypes,
		DependencyIndexes: file_api_v1_analytics_proto_depIdxs,
		MessageInfos:      file_api_v1_analytics_proto_msgTypes,
	}.Build()
	File_api_v1_analytics_proto = out.File
	file_api_v1_analytics_proto_goTypes = nil
	file_api_v1_analytics_proto_depIdxs = nil
}
