// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/analytics.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Granularity is the width of one Trends bucket.
type Granularity int32

const (
	Granularity_GRANULARITY_UNSPECIFIED Granularity = 0
	Granularity_GRANULARITY_DAY         Granularity = 1
	Granularity_GRANULARITY_WEEK        Granularity = 2
	Granularity_GRANULARITY_MONTH       Granularity = 3
	Granularity_GRANULARITY_YEAR        Granularity = 4
)

// Enum value maps for Granularity.
var (
	Granularity_name = map[int32]string{
		0: "GRANULARITY_UNSPECIFIED",
		1: "GRANULARITY_DAY",
		2: "GRANULARITY_WEEK",
		3: "GRANULARITY_MONTH",
		4: "GRANULARITY_YEAR",
	}
	Granularity_value = map[string]int32{
		"GRANULARITY_UNSPECIFIED": 0,
		"GRANULARITY_DAY":         1,
		"GRANULARITY_WEEK":        2,
		"GRANULARITY_MONTH":       3,
		"GRANULARITY_YEAR":        4,
	}
)

func (x Granularity) Enum() *Granularity {
	p := new(Granularity)
	*p = x
	return p
}

func (x Granularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Granularity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_analytics_proto_enumTypes[0].Descriptor()
}

func (Granularity) Type() protoreflect.EnumType {
	return &file_api_v1_analytics_proto_enumTypes[0]
}

func (x Granularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Granularity.Descriptor instead.
func (Granularity) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{0}
}

// TrendGroupBy is the dimension each bucket's stack is split by. LEVEL
// groups every attempt by the spaced-repetition box it landed in (1, 7,
// 30, 90, … day intervals) — pairing it with the level_ups metric is how
// the UI shows "level-ups per box".
type TrendGroupBy int32

const (
	TrendGroupBy_TREND_GROUP_BY_UNSPECIFIED TrendGroupBy = 0 // no split — one series per bucket
	TrendGroupBy_TREND_GROUP_BY_QUIZ_TYPE   TrendGroupBy = 1
	TrendGroupBy_TREND_GROUP_BY_NOTEBOOK    TrendGroupBy = 2
	TrendGroupBy_TREND_GROUP_BY_STATUS      TrendGroupBy = 3
	TrendGroupBy_TREND_GROUP_BY_LEVEL       TrendGroupBy = 4
)

// Enum value maps for TrendGroupBy.
var (
	TrendGroupBy_name = map[int32]string{
		0: "TREND_GROUP_BY_UNSPECIFIED",
		1: "TREND_GROUP_BY_QUIZ_TYPE",
		2: "TREND_GROUP_BY_NOTEBOOK",
		3: "TREND_GROUP_BY_STATUS",
		4: "TREND_GROUP_BY_LEVEL",
	}
	TrendGroupBy_value = map[string]int32{
		"TREND_GROUP_BY_UNSPECIFIED": 0,
		"TREND_GROUP_BY_QUIZ_TYPE":   1,
		"TREND_GROUP_BY_NOTEBOOK":    2,
		"TREND_GROUP_BY_STATUS":      3,
		"TREND_GROUP_BY_LEVEL":       4,
	}
)

func (x TrendGroupBy) Enum() *TrendGroupBy {
	p := new(TrendGroupBy)
	*p = x
	return p
}

func (x TrendGroupBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrendGroupBy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_analytics_proto_enumTypes[1].Descriptor()
}

func (TrendGroupBy) Type() protoreflect.EnumType {
	return &file_api_v1_analytics_proto_enumTypes[1]
}

func (x TrendGroupBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrendGroupBy.Descriptor instead.
func (TrendGroupBy) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{1}
}

type GetTrendsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Granularity Granularity            `protobuf:"varint,1,opt,name=granularity,proto3,enum=api.v1.Granularity" json:"granularity,omitempty"`
	// start_date / end_date bound the window in YYYY-MM-DD (inclusive).
	// Empty start_date means "from the first attempt"; empty end_date means
	// "through today".
	StartDate     string            `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string            `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GroupBy       TrendGroupBy      `protobuf:"varint,4,opt,name=group_by,json=groupBy,proto3,enum=api.v1.TrendGroupBy" json:"group_by,omitempty"`
	Filters       *AnalyticsFilters `protobuf:"bytes,5,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendsRequest) Reset() {
	*x = GetTrendsRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendsRequest) ProtoMessage() {}

func (x *GetTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrendsRequest) GetGranularity() Granularity {
	if x != nil {
		return x.Granularity
	}
	return Granularity_GRANULARITY_UNSPECIFIED
}

func (x *GetTrendsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetTrendsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetTrendsRequest) GetGroupBy() TrendGroupBy {
	if x != nil {
		return x.GroupBy
	}
	return TrendGroupBy_TREND_GROUP_BY_UNSPECIFIED
}

func (x *GetTrendsRequest) GetFilters() *AnalyticsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetTrendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// buckets are chronological, oldest first, one per period that had
	// activity in the range.
	Buckets []*TrendBucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	// summary carries the range totals. Distinct-count metrics (words_tested,
	// words_learned) are de-duplicated over the WHOLE range, so they do not
	// equal the sum of the per-bucket values — a word tested in two months
	// is two bucket entries but one word in the range total.
	Summary *TrendsSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// backlog is a point-in-time snapshot at the end of the range, not a
	// flow over it.
	Backlog       *BacklogSnapshot `protobuf:"bytes,3,opt,name=backlog,proto3" json:"backlog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendsResponse) Reset() {
	*x = GetTrendsResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendsResponse) ProtoMessage() {}

func (x *GetTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendsResponse.ProtoReflect.Descriptor instead.
func (*GetTrendsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrendsResponse) GetBuckets() []*TrendBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *GetTrendsResponse) GetSummary() *TrendsSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetTrendsResponse) GetBacklog() *BacklogSnapshot {
	if x != nil {
		return x.Backlog
	}
	return nil
}

// TrendBucket is one period (day / week / month) of activity.
type TrendBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// period is the bucket's start date in YYYY-MM-DD.
	Period        string         `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Series        []*TrendSeries `protobuf:"bytes,2,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendBucket) Reset() {
	*x = TrendBucket{}
	mi := &file_api_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendBucket) ProtoMessage() {}

func (x *TrendBucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendBucket.ProtoReflect.Descriptor instead.
func (*TrendBucket) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TrendBucket) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *TrendBucket) GetSeries() []*TrendSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

// TrendSeries is one split of a bucket. When group_by is UNSPECIFIED the
// bucket has a single series with an empty group_key.
type TrendSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_key is the raw key (quiz type, notebook id, status, or box
	// interval in days as a string). Empty for the no-split series.
	GroupKey string `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// group_label is the human-readable label (notebook title, "7-day box", …).
	GroupLabel string `protobuf:"bytes,2,opt,name=group_label,json=groupLabel,proto3" json:"group_label,omitempty"`
	// attempts is every quiz answer in this bucket+series.
	Attempts int32 `protobuf:"varint,3,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// words_tested is the distinct words answered in this bucket+series — a
	// word drilled ten times counts once.
	WordsTested int32 `protobuf:"varint,4,opt,name=words_tested,json=wordsTested,proto3" json:"words_tested,omitempty"`
	// words_learned is the distinct words that crossed up into a retained
	// status (understood / usable / intuitive) in this bucket+series.
	WordsLearned int32 `protobuf:"varint,5,opt,name=words_learned,json=wordsLearned,proto3" json:"words_learned,omitempty"`
	// level_ups / lapses count spaced-repetition box transitions landing in
	// this bucket+series (a lapse is a box drop after a wrong answer).
	LevelUps      int32 `protobuf:"varint,6,opt,name=level_ups,json=levelUps,proto3" json:"level_ups,omitempty"`
	Lapses        int32 `protobuf:"varint,7,opt,name=lapses,proto3" json:"lapses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendSeries) Reset() {
	*x = TrendSeries{}
	mi := &file_api_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendSeries) ProtoMessage() {}

func (x *TrendSeries) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendSeries.ProtoReflect.Descriptor instead.
func (*TrendSeries) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *TrendSeries) GetGroupKey() string {
	if x != nil {
		return x.GroupKey
	}
	return ""
}

func (x *TrendSeries) GetGroupLabel() string {
	if x != nil {
		return x.GroupLabel
	}
	return ""
}

func (x *TrendSeries) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *TrendSeries) GetWordsTested() int32 {
	if x != nil {
		return x.WordsTested
	}
	return 0
}

func (x *TrendSeries) GetWordsLearned() int32 {
	if x != nil {
		return x.WordsLearned
	}
	return 0
}

func (x *TrendSeries) GetLevelUps() int32 {
	if x != nil {
		return x.LevelUps
	}
	return 0
}

func (x *TrendSeries) GetLapses() int32 {
	if x != nil {
		return x.Lapses
	}
	return 0
}

// TrendsSummary is the range total for each metric (see GetTrendsResponse
// on why distinct metrics don't sum the buckets).
type TrendsSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      int32                  `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	WordsTested   int32                  `protobuf:"varint,2,opt,name=words_tested,json=wordsTested,proto3" json:"words_tested,omitempty"`
	WordsLearned  int32                  `protobuf:"varint,3,opt,name=words_learned,json=wordsLearned,proto3" json:"words_learned,omitempty"`
	LevelUps      int32                  `protobuf:"varint,4,opt,name=level_ups,json=levelUps,proto3" json:"level_ups,omitempty"`
	Lapses        int32                  `protobuf:"varint,5,opt,name=lapses,proto3" json:"lapses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendsSummary) Reset() {
	*x = TrendsSummary{}
	mi := &file_api_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendsSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendsSummary) ProtoMessage() {}

func (x *TrendsSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendsSummary.ProtoReflect.Descriptor instead.
func (*TrendsSummary) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TrendsSummary) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *TrendsSummary) GetWordsTested() int32 {
	if x != nil {
		return x.WordsTested
	}
	return 0
}

func (x *TrendsSummary) GetWordsLearned() int32 {
	if x != nil {
		return x.WordsLearned
	}
	return 0
}

func (x *TrendsSummary) GetLevelUps() int32 {
	if x != nil {
		return x.LevelUps
	}
	return 0
}

func (x *TrendsSummary) GetLapses() int32 {
	if x != nil {
		return x.Lapses
	}
	return 0
}

// BacklogSnapshot is the state of the user's words at the end of the
// range — where things stand today, not what flowed over the period.
type BacklogSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// never_correct is words with attempts but no correct answer yet.
	NeverCorrect int32 `protobuf:"varint,1,opt,name=never_correct,json=neverCorrect,proto3" json:"never_correct,omitempty"`
	// in_progress is words being learned but not yet mastered.
	InProgress int32 `protobuf:"varint,2,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	// mastered is words whose latest status is usable or intuitive.
	Mastered      int32 `protobuf:"varint,3,opt,name=mastered,proto3" json:"mastered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacklogSnapshot) Reset() {
	*x = BacklogSnapshot{}
	mi := &file_api_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacklogSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacklogSnapshot) ProtoMessage() {}

func (x *BacklogSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacklogSnapshot.ProtoReflect.Descriptor instead.
func (*BacklogSnapshot) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *BacklogSnapshot) GetNeverCorrect() int32 {
	if x != nil {
		return x.NeverCorrect
	}
	return 0
}

func (x *BacklogSnapshot) GetInProgress() int32 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *BacklogSnapshot) GetMastered() int32 {
	if x != nil {
		return x.Mastered
	}
	return 0
}

// AnalyticsFilters carries the optional notebook + quiz-type filters used
// on both the Day List and Day Detail pages.
type AnalyticsFilters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notebook_id, when non-empty, restricts results to a single notebook.
	NotebookId string `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	// quiz_type, when non-empty, restricts results to a single quiz type
	// (e.g. "notebook", "etymology_breakdown"). Empty means all types.
	QuizType      string `protobuf:"bytes,2,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsFilters) Reset() {
	*x = AnalyticsFilters{}
	mi := &file_api_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsFilters) ProtoMessage() {}

func (x *AnalyticsFilters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsFilters.ProtoReflect.Descriptor instead.
func (*AnalyticsFilters) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyticsFilters) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *AnalyticsFilters) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

type GetDailySummariesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// range_days bounds the window: only days within now()-range_days are
	// returned. Zero means "all time".
	RangeDays     int32             `protobuf:"varint,1,opt,name=range_days,json=rangeDays,proto3" json:"range_days,omitempty"`
	Filters       *AnalyticsFilters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummariesRequest) Reset() {
	*x = GetDailySummariesRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummariesRequest) ProtoMessage() {}

func (x *GetDailySummariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummariesRequest.ProtoReflect.Descriptor instead.
func (*GetDailySummariesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetDailySummariesRequest) GetRangeDays() int32 {
	if x != nil {
		return x.RangeDays
	}
	return 0
}

func (x *GetDailySummariesRequest) GetFilters() *AnalyticsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetDailySummariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []*DailySummary        `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummariesResponse) Reset() {
	*x = GetDailySummariesResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummariesResponse) ProtoMessage() {}

func (x *GetDailySummariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummariesResponse.ProtoReflect.Descriptor instead.
func (*GetDailySummariesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetDailySummariesResponse) GetDays() []*DailySummary {
	if x != nil {
		return x.Days
	}
	return nil
}

// DailySummary is one row on the Day List.
type DailySummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in YYYY-MM-DD format.
	Date          string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	WrongCount    int32  `protobuf:"varint,2,opt,name=wrong_count,json=wrongCount,proto3" json:"wrong_count,omitempty"`
	TotalCount    int32  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NotebookCount int32  `protobuf:"varint,4,opt,name=notebook_count,json=notebookCount,proto3" json:"notebook_count,omitempty"`
	// quiz_types lists every quiz type that produced an attempt on this
	// day (e.g. ["notebook", "reverse", "etymology_breakdown"]).
	QuizTypes     []string `protobuf:"bytes,5,rep,name=quiz_types,json=quizTypes,proto3" json:"quiz_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySummary) Reset() {
	*x = DailySummary{}
	mi := &file_api_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySummary) ProtoMessage() {}

func (x *DailySummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySummary.ProtoReflect.Descriptor instead.
func (*DailySummary) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *DailySummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailySummary) GetWrongCount() int32 {
	if x != nil {
		return x.WrongCount
	}
	return 0
}

func (x *DailySummary) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *DailySummary) GetNotebookCount() int32 {
	if x != nil {
		return x.NotebookCount
	}
	return 0
}

func (x *DailySummary) GetQuizTypes() []string {
	if x != nil {
		return x.QuizTypes
	}
	return nil
}

type GetDayDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in YYYY-MM-DD format.
	Date          string            `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Filters       *AnalyticsFilters `protobuf:"bytes,2,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayDetailRequest) Reset() {
	*x = GetDayDetailRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayDetailRequest) ProtoMessage() {}

func (x *GetDayDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDayDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetDayDetailRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDayDetailRequest) GetFilters() *AnalyticsFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type GetDayDetailResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Summary    *DailySummary          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	WrongWords []*WrongWord           `protobuf:"bytes,2,rep,name=wrong_words,json=wrongWords,proto3" json:"wrong_words,omitempty"`
	// previous_date and next_date are the adjacent days with quiz activity
	// matching the current filters, in YYYY-MM-DD format. Empty when no
	// adjacent day exists.
	PreviousDate  string `protobuf:"bytes,3,opt,name=previous_date,json=previousDate,proto3" json:"previous_date,omitempty"`
	NextDate      string `protobuf:"bytes,4,opt,name=next_date,json=nextDate,proto3" json:"next_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDayDetailResponse) Reset() {
	*x = GetDayDetailResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDayDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDayDetailResponse) ProtoMessage() {}

func (x *GetDayDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDayDetailResponse.ProtoReflect.Descriptor instead.
func (*GetDayDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetDayDetailResponse) GetSummary() *DailySummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetDayDetailResponse) GetWrongWords() []*WrongWord {
	if x != nil {
		return x.WrongWords
	}
	return nil
}

func (x *GetDayDetailResponse) GetPreviousDate() string {
	if x != nil {
		return x.PreviousDate
	}
	return ""
}

func (x *GetDayDetailResponse) GetNextDate() string {
	if x != nil {
		return x.NextDate
	}
	return ""
}

// WrongWord is one (word × quiz_type) attempt the user got wrong on the
// requested day, plus enough surrounding context to render the card.
type WrongWord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// note_id is the DB row id of the word. Zero when YAML-only.
	NoteId        int64  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Expression    string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	NotebookId    string `protobuf:"bytes,3,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	NotebookTitle string `protobuf:"bytes,4,opt,name=notebook_title,json=notebookTitle,proto3" json:"notebook_title,omitempty"`
	SceneTitle    string `protobuf:"bytes,5,opt,name=scene_title,json=sceneTitle,proto3" json:"scene_title,omitempty"`
	// quiz_type uses the same string values as LearningRecord.QuizType
	// (e.g. "notebook", "reverse", "etymology_breakdown").
	QuizType string `protobuf:"bytes,6,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	// recent_pattern is the last 5 attempts for this (word, quiz_type),
	// newest LAST so the row reads left-to-right. Each entry is one of
	// "correct", "wrong" or "none".
	RecentPattern []string `protobuf:"bytes,7,rep,name=recent_pattern,json=recentPattern,proto3" json:"recent_pattern,omitempty"`
	// current_wrong_streak counts consecutive wrong attempts ending at the
	// attempt on this day.
	CurrentWrongStreak int32 `protobuf:"varint,8,opt,name=current_wrong_streak,json=currentWrongStreak,proto3" json:"current_wrong_streak,omitempty"`
	// previous_correct_streak counts consecutive correct attempts
	// immediately before the current wrong streak (0 when the current
	// wrong streak starts from the very first attempt).
	PreviousCorrectStreak int32 `protobuf:"varint,9,opt,name=previous_correct_streak,json=previousCorrectStreak,proto3" json:"previous_correct_streak,omitempty"`
	// current_status is the learning status after the attempt on this day.
	CurrentStatus string `protobuf:"bytes,10,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	// meaning is the canonical definition the learner was supposed to recall.
	// For reverse quizzes this is the prompt the learner saw — reading it on
	// the analytics card reproduces the original cognitive task. For
	// etymology origins this is the origin's meaning.
	Meaning string `protobuf:"bytes,11,opt,name=meaning,proto3" json:"meaning,omitempty"`
	// example_sentence is one illustrative usage of the expression, when
	// available. Empty when the source notebook has no examples for the
	// word (typical for etymology origins).
	ExampleSentence string `protobuf:"bytes,12,opt,name=example_sentence,json=exampleSentence,proto3" json:"example_sentence,omitempty"`
	// notebook_kind is "story", "flashcard", or "etymology". The frontend
	// uses it to decide which Learn route to deep-link to.
	NotebookKind string `protobuf:"bytes,13,opt,name=notebook_kind,json=notebookKind,proto3" json:"notebook_kind,omitempty"`
	// skipped is true when the user has currently excluded this word from
	// this quiz type (skipped_at set for the matching quiz_type slot).
	// The analytics card surfaces this with an "Excluded" badge so the
	// user understands why the word still surfaces in history but won't
	// come up in future quizzes until the skip is cleared.
	Skipped bool `protobuf:"varint,14,opt,name=skipped,proto3" json:"skipped,omitempty"`
	// related_groups carries the word's place in the concept graph: the
	// definitions-book concept it shares with sibling expressions, the
	// etymology concept its origin belongs to (and sibling origins under
	// the same concept), and concepts connected to that one via etymology
	// relations (antonym / synonym / hyponym / …). Empty when the
	// notebook has no concepts. The frontend collapses these into a chip
	// row under the meaning and the full block in the expanded panel so a
	// wrong word never reads in isolation.
	RelatedGroups []*RelatedGroup `protobuf:"bytes,15,rep,name=related_groups,json=relatedGroups,proto3" json:"related_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WrongWord) Reset() {
	*x = WrongWord{}
	mi := &file_api_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrongWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrongWord) ProtoMessage() {}

func (x *WrongWord) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrongWord.ProtoReflect.Descriptor instead.
func (*WrongWord) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *WrongWord) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *WrongWord) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *WrongWord) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *WrongWord) GetNotebookTitle() string {
	if x != nil {
		return x.NotebookTitle
	}
	return ""
}

func (x *WrongWord) GetSceneTitle() string {
	if x != nil {
		return x.SceneTitle
	}
	return ""
}

func (x *WrongWord) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *WrongWord) GetRecentPattern() []string {
	if x != nil {
		return x.RecentPattern
	}
	return nil
}

func (x *WrongWord) GetCurrentWrongStreak() int32 {
	if x != nil {
		return x.CurrentWrongStreak
	}
	return 0
}

func (x *WrongWord) GetPreviousCorrectStreak() int32 {
	if x != nil {
		return x.PreviousCorrectStreak
	}
	return 0
}

func (x *WrongWord) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *WrongWord) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *WrongWord) GetExampleSentence() string {
	if x != nil {
		return x.ExampleSentence
	}
	return ""
}

func (x *WrongWord) GetNotebookKind() string {
	if x != nil {
		return x.NotebookKind
	}
	return ""
}

func (x *WrongWord) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

func (x *WrongWord) GetRelatedGroups() []*RelatedGroup {
	if x != nil {
		return x.RelatedGroups
	}
	return nil
}

// RelatedGroup is one cluster of related entries surfaced on the
// analytics card. The grouping is intentionally flat (kind + label +
// member strings) so the same shape covers sibling words, sibling
// origins, and related-concept members — the frontend renders each as a
// labelled chip + list without per-kind branching.
type RelatedGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind names the cluster: "concept" for definitions-book sibling
	// words, "origin_family" for etymology sibling origins under the
	// word's origin's concept, and the relation type name ("antonym",
	// "synonym", "hyponym", …) for related-concept clusters.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// label is the human-readable header. For "concept" it's the head's
	// umbrella meaning (e.g. "clumsy in social situations"); for
	// "origin_family" / relation kinds it's the concept name with the
	// umbrella meaning ("leftness — left"). Empty when no umbrella was
	// declared.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// members are the cluster's entries as already-formatted strings —
	// e.g. "gaucherie", "sinister (Latin) — left", "dexterity". Ordering
	// is the order declared in the source notebook.
	Members       []string `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedGroup) Reset() {
	*x = RelatedGroup{}
	mi := &file_api_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedGroup) ProtoMessage() {}

func (x *RelatedGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedGroup.ProtoReflect.Descriptor instead.
func (*RelatedGroup) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *RelatedGroup) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RelatedGroup) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RelatedGroup) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetWordHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        int64                  `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	NotebookId    string                 `protobuf:"bytes,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Expression    string                 `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	QuizType      string                 `protobuf:"bytes,4,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWordHistoryRequest) Reset() {
	*x = GetWordHistoryRequest{}
	mi := &file_api_v1_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordHistoryRequest) ProtoMessage() {}

func (x *GetWordHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWordHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetWordHistoryRequest) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GetWordHistoryRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *GetWordHistoryRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GetWordHistoryRequest) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

type GetWordHistoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Expression         string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	NotebookId         string                 `protobuf:"bytes,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	NotebookTitle      string                 `protobuf:"bytes,3,opt,name=notebook_title,json=notebookTitle,proto3" json:"notebook_title,omitempty"`
	CurrentStatus      string                 `protobuf:"bytes,4,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	CurrentWrongStreak int32                  `protobuf:"varint,5,opt,name=current_wrong_streak,json=currentWrongStreak,proto3" json:"current_wrong_streak,omitempty"`
	Attempts           []*AttemptEntry        `protobuf:"bytes,6,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWordHistoryResponse) Reset() {
	*x = GetWordHistoryResponse{}
	mi := &file_api_v1_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWordHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordHistoryResponse) ProtoMessage() {}

func (x *GetWordHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWordHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *GetWordHistoryResponse) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GetWordHistoryResponse) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *GetWordHistoryResponse) GetNotebookTitle() string {
	if x != nil {
		return x.NotebookTitle
	}
	return ""
}

func (x *GetWordHistoryResponse) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

func (x *GetWordHistoryResponse) GetCurrentWrongStreak() int32 {
	if x != nil {
		return x.CurrentWrongStreak
	}
	return 0
}

func (x *GetWordHistoryResponse) GetAttempts() []*AttemptEntry {
	if x != nil {
		return x.Attempts
	}
	return nil
}

// AttemptEntry is a single past attempt with the streak context just
// before it.
type AttemptEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in YYYY-MM-DD format.
	Date     string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	QuizType string `protobuf:"bytes,2,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	// result is "correct" or "wrong".
	Result  string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Quality int32  `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`
	// streak_before_wrong / streak_before_correct describe the run that
	// ended at this attempt. Exactly one is non-zero. Both zero means
	// this was the very first attempt.
	StreakBeforeWrong   int32 `protobuf:"varint,5,opt,name=streak_before_wrong,json=streakBeforeWrong,proto3" json:"streak_before_wrong,omitempty"`
	StreakBeforeCorrect int32 `protobuf:"varint,6,opt,name=streak_before_correct,json=streakBeforeCorrect,proto3" json:"streak_before_correct,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttemptEntry) Reset() {
	*x = AttemptEntry{}
	mi := &file_api_v1_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptEntry) ProtoMessage() {}

func (x *AttemptEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptEntry.ProtoReflect.Descriptor instead.
func (*AttemptEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *AttemptEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AttemptEntry) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *AttemptEntry) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AttemptEntry) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *AttemptEntry) GetStreakBeforeWrong() int32 {
	if x != nil {
		return x.StreakBeforeWrong
	}
	return 0
}

func (x *AttemptEntry) GetStreakBeforeCorrect() int32 {
	if x != nil {
		return x.StreakBeforeCorrect
	}
	return 0
}

var File_api_v1_analytics_proto protoreflect.FileDescriptor

const file_api_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/analytics.proto\x12\x06api.v1\x1a\x1bbuf/validate/validate.proto\"\xe8\x01\n" +
	"\x10GetTrendsRequest\x125\n" +
	"\vgranularity\x18\x01 \x01(\x0e2\x13.api.v1.GranularityR\vgranularity\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12/\n" +
	"\bgroup_by\x18\x04 \x01(\x0e2\x14.api.v1.TrendGroupByR\agroupBy\x122\n" +
	"\afilters\x18\x05 \x01(\v2\x18.api.v1.AnalyticsFiltersR\afilters\"\xa6\x01\n" +
	"\x11GetTrendsResponse\x12-\n" +
	"\abuckets\x18\x01 \x03(\v2\x13.api.v1.TrendBucketR\abuckets\x12/\n" +
	"\asummary\x18\x02 \x01(\v2\x15.api.v1.TrendsSummaryR\asummary\x121\n" +
	"\abacklog\x18\x03 \x01(\v2\x17.api.v1.BacklogSnapshotR\abacklog\"R\n" +
	"\vTrendBucket\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12+\n" +
	"\x06series\x18\x02 \x03(\v2\x13.api.v1.TrendSeriesR\x06series\"\xe4\x01\n" +
	"\vTrendSeries\x12\x1b\n" +
	"\tgroup_key\x18\x01 \x01(\tR\bgroupKey\x12\x1f\n" +
	"\vgroup_label\x18\x02 \x01(\tR\n" +
	"groupLabel\x12\x1a\n" +
	"\battempts\x18\x03 \x01(\x05R\battempts\x12!\n" +
	"\fwords_tested\x18\x04 \x01(\x05R\vwordsTested\x12#\n" +
	"\rwords_learned\x18\x05 \x01(\x05R\fwordsLearned\x12\x1b\n" +
	"\tlevel_ups\x18\x06 \x01(\x05R\blevelUps\x12\x16\n" +
	"\x06lapses\x18\a \x01(\x05R\x06lapses\"\xa8\x01\n" +
	"\rTrendsSummary\x12\x1a\n" +
	"\battempts\x18\x01 \x01(\x05R\battempts\x12!\n" +
	"\fwords_tested\x18\x02 \x01(\x05R\vwordsTested\x12#\n" +
	"\rwords_learned\x18\x03 \x01(\x05R\fwordsLearned\x12\x1b\n" +
	"\tlevel_ups\x18\x04 \x01(\x05R\blevelUps\x12\x16\n" +
	"\x06lapses\x18\x05 \x01(\x05R\x06lapses\"s\n" +
	"\x0fBacklogSnapshot\x12#\n" +
	"\rnever_correct\x18\x01 \x01(\x05R\fneverCorrect\x12\x1f\n" +
	"\vin_progress\x18\x02 \x01(\x05R\n" +
	"inProgress\x12\x1a\n" +
	"\bmastered\x18\x03 \x01(\x05R\bmastered\"P\n" +
	"\x10AnalyticsFilters\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\tR\n" +
	"notebookId\x12\x1b\n" +
	"\tquiz_type\x18\x02 \x01(\tR\bquizType\"v\n" +
	"\x18GetDailySummariesRequest\x12&\n" +
	"\n" +
	"range_days\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\trangeDays\x122\n" +
	"\afilters\x18\x02 \x01(\v2\x18.api.v1.AnalyticsFiltersR\afilters\"E\n" +
	"\x19GetDailySummariesResponse\x12(\n" +
	"\x04days\x18\x01 \x03(\v2\x14.api.v1.DailySummaryR\x04days\"\xaa\x01\n" +
	"\fDailySummary\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vwrong_count\x18\x02 \x01(\x05R\n" +
	"wrongCount\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12%\n" +
	"\x0enotebook_count\x18\x04 \x01(\x05R\rnotebookCount\x12\x1d\n" +
	"\n" +
	"quiz_types\x18\x05 \x03(\tR\tquizTypes\"f\n" +
	"\x13GetDayDetailRequest\x12\x1b\n" +
	"\x04date\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04date\x122\n" +
	"\afilters\x18\x02 \x01(\v2\x18.api.v1.AnalyticsFiltersR\afilters\"\xbc\x01\n" +
	"\x14GetDayDetailResponse\x12.\n" +
	"\asummary\x18\x01 \x01(\v2\x14.api.v1.DailySummaryR\asummary\x122\n" +
	"\vwrong_words\x18\x02 \x03(\v2\x11.api.v1.WrongWordR\n" +
	"wrongWords\x12#\n" +
	"\rprevious_date\x18\x03 \x01(\tR\fpreviousDate\x12\x1b\n" +
	"\tnext_date\x18\x04 \x01(\tR\bnextDate\"\xc3\x04\n" +
	"\tWrongWord\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1e\n" +
	"\n" +
	"expression\x18\x02 \x01(\tR\n" +
	"expression\x12\x1f\n" +
	"\vnotebook_id\x18\x03 \x01(\tR\n" +
	"notebookId\x12%\n" +
	"\x0enotebook_title\x18\x04 \x01(\tR\rnotebookTitle\x12\x1f\n" +
	"\vscene_title\x18\x05 \x01(\tR\n" +
	"sceneTitle\x12\x1b\n" +
	"\tquiz_type\x18\x06 \x01(\tR\bquizType\x12%\n" +
	"\x0erecent_pattern\x18\a \x03(\tR\rrecentPattern\x120\n" +
	"\x14current_wrong_streak\x18\b \x01(\x05R\x12currentWrongStreak\x126\n" +
	"\x17previous_correct_streak\x18\t \x01(\x05R\x15previousCorrectStreak\x12%\n" +
	"\x0ecurrent_status\x18\n" +
	" \x01(\tR\rcurrentStatus\x12\x18\n" +
	"\ameaning\x18\v \x01(\tR\ameaning\x12)\n" +
	"\x10example_sentence\x18\f \x01(\tR\x0fexampleSentence\x12#\n" +
	"\rnotebook_kind\x18\r \x01(\tR\fnotebookKind\x12\x18\n" +
	"\askipped\x18\x0e \x01(\bR\askipped\x12;\n" +
	"\x0erelated_groups\x18\x0f \x03(\v2\x14.api.v1.RelatedGroupR\rrelatedGroups\"R\n" +
	"\fRelatedGroup\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembers\"\xa0\x01\n" +
	"\x15GetWordHistoryRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x03R\x06noteId\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\tR\n" +
	"notebookId\x12'\n" +
	"\n" +
	"expression\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"expression\x12$\n" +
	"\tquiz_type\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bquizType\"\x8b\x02\n" +
	"\x16GetWordHistoryResponse\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\tR\n" +
	"notebookId\x12%\n" +
	"\x0enotebook_title\x18\x03 \x01(\tR\rnotebookTitle\x12%\n" +
	"\x0ecurrent_status\x18\x04 \x01(\tR\rcurrentStatus\x120\n" +
	"\x14current_wrong_streak\x18\x05 \x01(\x05R\x12currentWrongStreak\x120\n" +
	"\battempts\x18\x06 \x03(\v2\x14.api.v1.AttemptEntryR\battempts\"\xd5\x01\n" +
	"\fAttemptEntry\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1b\n" +
	"\tquiz_type\x18\x02 \x01(\tR\bquizType\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x05R\aquality\x12.\n" +
	"\x13streak_before_wrong\x18\x05 \x01(\x05R\x11streakBeforeWrong\x122\n" +
	"\x15streak_before_correct\x18\x06 \x01(\x05R\x13streakBeforeCorrect*\x82\x01\n" +
	"\vGranularity\x12\x1b\n" +
	"\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGRANULARITY_DAY\x10\x01\x12\x14\n" +
	"\x10GRANULARITY_WEEK\x10\x02\x12\x15\n" +
	"\x11GRANULARITY_MONTH\x10\x03\x12\x14\n" +
	"\x10GRANULARITY_YEAR\x10\x04*\x9e\x01\n" +
	"\fTrendGroupBy\x12\x1e\n" +
	"\x1aTREND_GROUP_BY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TREND_GROUP_BY_QUIZ_TYPE\x10\x01\x12\x1b\n" +
	"\x17TREND_GROUP_BY_NOTEBOOK\x10\x02\x12\x19\n" +
	"\x15TREND_GROUP_BY_STATUS\x10\x03\x12\x18\n" +
	"\x14TREND_GROUP_BY_LEVEL\x10\x042\xca\x02\n" +
	"\x10AnalyticsService\x12X\n" +
	"\x11GetDailySummaries\x12 .api.v1.GetDailySummariesRequest\x1a!.api.v1.GetDailySummariesResponse\x12I\n" +
	"\fGetDayDetail\x12\x1b.api.v1.GetDayDetailRequest\x1a\x1c.api.v1.GetDayDetailResponse\x12O\n" +
	"\x0eGetWordHistory\x12\x1d.api.v1.GetWordHistoryRequest\x1a\x1e.api.v1.GetWordHistoryResponse\x12@\n" +
	"\tGetTrends\x12\x18.api.v1.GetTrendsRequest\x1a\x19.api.v1.GetTrendsResponseB8Z6github.com/at-ishikawa/langner/gen-protos/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_analytics_proto_rawDescOnce sync.Once
	file_api_v1_analytics_proto_rawDescData []byte
)

func file_api_v1_analytics_proto_rawDescGZIP() []byte {
	file_api_v1_analytics_proto_rawDescOnce.Do(func() {
		file_api_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_analytics_proto_rawDesc), len(file_api_v1_analytics_proto_rawDesc)))
	})
	return file_api_v1_analytics_proto_rawDescData
}

var file_api_v1_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_v1_analytics_proto_goTypes = []any{
	(Granularity)(0),                  // 0: api.v1.Granularity
	(TrendGroupBy)(0),                 // 1: api.v1.TrendGroupBy
	(*GetTrendsRequest)(nil),          // 2: api.v1.GetTrendsRequest
	(*GetTrendsResponse)(nil),         // 3: api.v1.GetTrendsResponse
	(*TrendBucket)(nil),               // 4: api.v1.TrendBucket
	(*TrendSeries)(nil),               // 5: api.v1.TrendSeries
	(*TrendsSummary)(nil),             // 6: api.v1.TrendsSummary
	(*BacklogSnapshot)(nil),           // 7: api.v1.BacklogSnapshot
	(*AnalyticsFilters)(nil),          // 8: api.v1.AnalyticsFilters
	(*GetDailySummariesRequest)(nil),  // 9: api.v1.GetDailySummariesRequest
	(*GetDailySummariesResponse)(nil), // 10: api.v1.GetDailySummariesResponse
	(*DailySummary)(nil),              // 11: api.v1.DailySummary
	(*GetDayDetailRequest)(nil),       // 12: api.v1.GetDayDetailRequest
	(*GetDayDetailResponse)(nil),      // 13: api.v1.GetDayDetailResponse
	(*WrongWord)(nil),                 // 14: api.v1.WrongWord
	(*RelatedGroup)(nil),              // 15: api.v1.RelatedGroup
	(*GetWordHistoryRequest)(nil),     // 16: api.v1.GetWordHistoryRequest
	(*GetWordHistoryResponse)(nil),    // 17: api.v1.GetWordHistoryResponse
	(*AttemptEntry)(nil),              // 18: api.v1.AttemptEntry
}
var file_api_v1_analytics_proto_depIdxs = []int32{
	0,  // 0: api.v1.GetTrendsRequest.granularity:type_name -> api.v1.Granularity
	1,  // 1: api.v1.GetTrendsRequest.group_by:type_name -> api.v1.TrendGroupBy
	8,  // 2: api.v1.GetTrendsRequest.filters:type_name -> api.v1.AnalyticsFilters
	4,  // 3: api.v1.GetTrendsResponse.buckets:type_name -> api.v1.TrendBucket
	6,  // 4: api.v1.GetTrendsResponse.summary:type_name -> api.v1.TrendsSummary
	7,  // 5: api.v1.GetTrendsResponse.backlog:type_name -> api.v1.BacklogSnapshot
	5,  // 6: api.v1.TrendBucket.series:type_name -> api.v1.TrendSeries
	8,  // 7: api.v1.GetDailySummariesRequest.filters:type_name -> api.v1.AnalyticsFilters
	11, // 8: api.v1.GetDailySummariesResponse.days:type_name -> api.v1.DailySummary
	8,  // 9: api.v1.GetDayDetailRequest.filters:type_name -> api.v1.AnalyticsFilters
	11, // 10: api.v1.GetDayDetailResponse.summary:type_name -> api.v1.DailySummary
	14, // 11: api.v1.GetDayDetailResponse.wrong_words:type_name -> api.v1.WrongWord
	15, // 12: api.v1.WrongWord.related_groups:type_name -> api.v1.RelatedGroup
	18, // 13: api.v1.GetWordHistoryResponse.attempts:type_name -> api.v1.AttemptEntry
	9,  // 14: api.v1.AnalyticsService.GetDailySummaries:input_type -> api.v1.GetDailySummariesRequest
	12, // 15: api.v1.AnalyticsService.GetDayDetail:input_type -> api.v1.GetDayDetailRequest
	16, // 16: api.v1.AnalyticsService.GetWordHistory:input_type -> api.v1.GetWordHistoryRequest
	2,  // 17: api.v1.AnalyticsService.GetTrends:input_type -> api.v1.GetTrendsRequest
	10, // 18: api.v1.AnalyticsService.GetDailySummaries:output_type -> api.v1.GetDailySummariesResponse
	13, // 19: api.v1.AnalyticsService.GetDayDetail:output_type -> api.v1.GetDayDetailResponse
	17, // 20: api.v1.AnalyticsService.GetWordHistory:output_type -> api.v1.GetWordHistoryResponse
	3,  // 21: api.v1.AnalyticsService.GetTrends:output_type -> api.v1.GetTrendsResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_v1_analytics_proto_init() }
func file_api_v1_analytics_proto_init() {
	if File_api_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_analytics_proto_rawDesc), len(file_api_v1_analytics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_analytics_proto_goTypes,
		DependencyIndexes: file_api_v1_analytics_proto_depIdxs,
		EnumInfos:         file_api_v1_analytics_proto_enumTypes,
		MessageInfos:      file_api_v1_analytics_proto_msgTypes,
	}.Build()
	File_api_v1_analytics_proto = out.File
	file_api_v1_analytics_proto_goTypes = nil
	file_api_v1_analytics_proto_depIdxs = nil
}
