// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/notebook.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotebookDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotebookDetailRequest) Reset() {
	*x = GetNotebookDetailRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailRequest) ProtoMessage() {}

func (x *GetNotebookDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailRequest.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotebookDetailRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

type GetNotebookDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotebookId     string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stories        []*StoryEntry          `protobuf:"bytes,3,rep,name=stories,proto3" json:"stories,omitempty"`
	TotalWordCount int32                  `protobuf:"varint,4,opt,name=total_word_count,json=totalWordCount,proto3" json:"total_word_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotebookDetailResponse) Reset() {
	*x = GetNotebookDetailResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailResponse) ProtoMessage() {}

func (x *GetNotebookDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailResponse.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{1}
}

func (x *GetNotebookDetailResponse) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *GetNotebookDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNotebookDetailResponse) GetStories() []*StoryEntry {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *GetNotebookDetailResponse) GetTotalWordCount() int32 {
	if x != nil {
		return x.TotalWordCount
	}
	return 0
}

type StoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata      *StoryMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Scenes        []*StoryScene          `protobuf:"bytes,4,rep,name=scenes,proto3" json:"scenes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryEntry) Reset() {
	*x = StoryEntry{}
	mi := &file_api_v1_notebook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryEntry) ProtoMessage() {}

func (x *StoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryEntry.ProtoReflect.Descriptor instead.
func (*StoryEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{2}
}

func (x *StoryEntry) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StoryEntry) GetMetadata() *StoryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoryEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *StoryEntry) GetScenes() []*StoryScene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

type StoryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	Season        int32                  `protobuf:"varint,2,opt,name=season,proto3" json:"season,omitempty"`
	Episode       int32                  `protobuf:"varint,3,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryMetadata) Reset() {
	*x = StoryMetadata{}
	mi := &file_api_v1_notebook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryMetadata) ProtoMessage() {}

func (x *StoryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryMetadata.ProtoReflect.Descriptor instead.
func (*StoryMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{3}
}

func (x *StoryMetadata) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *StoryMetadata) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *StoryMetadata) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

type StoryScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Conversations []*Conversation        `protobuf:"bytes,2,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Definitions   []*NotebookWord        `protobuf:"bytes,3,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Statements    []string               `protobuf:"bytes,5,rep,name=statements,proto3" json:"statements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryScene) Reset() {
	*x = StoryScene{}
	mi := &file_api_v1_notebook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryScene) ProtoMessage() {}

func (x *StoryScene) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryScene.ProtoReflect.Descriptor instead.
func (*StoryScene) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{4}
}

func (x *StoryScene) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StoryScene) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *StoryScene) GetDefinitions() []*NotebookWord {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *StoryScene) GetStatements() []string {
	if x != nil {
		return x.Statements
	}
	return nil
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speaker       string                 `protobuf:"bytes,1,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_api_v1_notebook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{5}
}

func (x *Conversation) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *Conversation) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

type NotebookWord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Expression     string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Definition     string                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Meaning        string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	PartOfSpeech   string                 `protobuf:"bytes,4,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Pronunciation  string                 `protobuf:"bytes,5,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	Examples       []string               `protobuf:"bytes,6,rep,name=examples,proto3" json:"examples,omitempty"`
	Synonyms       []string               `protobuf:"bytes,7,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Antonyms       []string               `protobuf:"bytes,8,rep,name=antonyms,proto3" json:"antonyms,omitempty"`
	LearningStatus string                 `protobuf:"bytes,9,opt,name=learning_status,json=learningStatus,proto3" json:"learning_status,omitempty"`
	LearnedLogs    []*LearningLogEntry    `protobuf:"bytes,10,rep,name=learned_logs,json=learnedLogs,proto3" json:"learned_logs,omitempty"`
	NextReviewDate string                 `protobuf:"bytes,12,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	Origin         string                 `protobuf:"bytes,13,opt,name=origin,proto3" json:"origin,omitempty"`
	IsSkipped      bool                   `protobuf:"varint,14,opt,name=is_skipped,json=isSkipped,proto3" json:"is_skipped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotebookWord) Reset() {
	*x = NotebookWord{}
	mi := &file_api_v1_notebook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotebookWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotebookWord) ProtoMessage() {}

func (x *NotebookWord) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotebookWord.ProtoReflect.Descriptor instead.
func (*NotebookWord) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{6}
}

func (x *NotebookWord) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *NotebookWord) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *NotebookWord) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *NotebookWord) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *NotebookWord) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

func (x *NotebookWord) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *NotebookWord) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *NotebookWord) GetAntonyms() []string {
	if x != nil {
		return x.Antonyms
	}
	return nil
}

func (x *NotebookWord) GetLearningStatus() string {
	if x != nil {
		return x.LearningStatus
	}
	return ""
}

func (x *NotebookWord) GetLearnedLogs() []*LearningLogEntry {
	if x != nil {
		return x.LearnedLogs
	}
	return nil
}

func (x *NotebookWord) GetNextReviewDate() string {
	if x != nil {
		return x.NextReviewDate
	}
	return ""
}

func (x *NotebookWord) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *NotebookWord) GetIsSkipped() bool {
	if x != nil {
		return x.IsSkipped
	}
	return false
}

type LearningLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LearnedAt      string                 `protobuf:"bytes,2,opt,name=learned_at,json=learnedAt,proto3" json:"learned_at,omitempty"`
	Quality        int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	QuizType       string                 `protobuf:"bytes,5,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	IntervalDays   int32                  `protobuf:"varint,6,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LearningLogEntry) Reset() {
	*x = LearningLogEntry{}
	mi := &file_api_v1_notebook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningLogEntry) ProtoMessage() {}

func (x *LearningLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningLogEntry.ProtoReflect.Descriptor instead.
func (*LearningLogEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{7}
}

func (x *LearningLogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LearningLogEntry) GetLearnedAt() string {
	if x != nil {
		return x.LearnedAt
	}
	return ""
}

func (x *LearningLogEntry) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *LearningLogEntry) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *LearningLogEntry) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *LearningLogEntry) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

type ExportNotebookPDFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNotebookPDFRequest) Reset() {
	*x = ExportNotebookPDFRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFRequest) ProtoMessage() {}

func (x *ExportNotebookPDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFRequest.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{8}
}

func (x *ExportNotebookPDFRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

type ExportNotebookPDFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfContent    []byte                 `protobuf:"bytes,1,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNotebookPDFResponse) Reset() {
	*x = ExportNotebookPDFResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFResponse) ProtoMessage() {}

func (x *ExportNotebookPDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFResponse.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{9}
}

func (x *ExportNotebookPDFResponse) GetPdfContent() []byte {
	if x != nil {
		return x.PdfContent
	}
	return nil
}

func (x *ExportNotebookPDFResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type LookupWordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	NotebookId    string                 `protobuf:"bytes,2,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupWordRequest) Reset() {
	*x = LookupWordRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWordRequest) ProtoMessage() {}

func (x *LookupWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWordRequest.ProtoReflect.Descriptor instead.
func (*LookupWordRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{10}
}

func (x *LookupWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *LookupWordRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *LookupWordRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type WordDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartOfSpeech  string                 `protobuf:"bytes,1,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Definition    string                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Examples      []string               `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	Synonyms      []string               `protobuf:"bytes,4,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Pronunciation string                 `protobuf:"bytes,5,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	Antonyms      []string               `protobuf:"bytes,6,rep,name=antonyms,proto3" json:"antonyms,omitempty"`
	Origin        string                 `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordDefinition) Reset() {
	*x = WordDefinition{}
	mi := &file_api_v1_notebook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordDefinition) ProtoMessage() {}

func (x *WordDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordDefinition.ProtoReflect.Descriptor instead.
func (*WordDefinition) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{11}
}

func (x *WordDefinition) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *WordDefinition) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *WordDefinition) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *WordDefinition) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *WordDefinition) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

func (x *WordDefinition) GetAntonyms() []string {
	if x != nil {
		return x.Antonyms
	}
	return nil
}

func (x *WordDefinition) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type LookupWordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Definitions   []*WordDefinition      `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupWordResponse) Reset() {
	*x = LookupWordResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupWordResponse) ProtoMessage() {}

func (x *LookupWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupWordResponse.ProtoReflect.Descriptor instead.
func (*LookupWordResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{12}
}

func (x *LookupWordResponse) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *LookupWordResponse) GetDefinitions() []*WordDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *LookupWordResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type RegisterDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	NotebookFile  string                 `protobuf:"bytes,2,opt,name=notebook_file,json=notebookFile,proto3" json:"notebook_file,omitempty"`
	SceneIndex    int32                  `protobuf:"varint,3,opt,name=scene_index,json=sceneIndex,proto3" json:"scene_index,omitempty"`
	Expression    string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	Meaning       string                 `protobuf:"bytes,5,opt,name=meaning,proto3" json:"meaning,omitempty"`
	PartOfSpeech  string                 `protobuf:"bytes,6,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Examples      []string               `protobuf:"bytes,7,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDefinitionRequest) Reset() {
	*x = RegisterDefinitionRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDefinitionRequest) ProtoMessage() {}

func (x *RegisterDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDefinitionRequest.ProtoReflect.Descriptor instead.
func (*RegisterDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterDefinitionRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *RegisterDefinitionRequest) GetNotebookFile() string {
	if x != nil {
		return x.NotebookFile
	}
	return ""
}

func (x *RegisterDefinitionRequest) GetSceneIndex() int32 {
	if x != nil {
		return x.SceneIndex
	}
	return 0
}

func (x *RegisterDefinitionRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *RegisterDefinitionRequest) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *RegisterDefinitionRequest) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *RegisterDefinitionRequest) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

type RegisterDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDefinitionResponse) Reset() {
	*x = RegisterDefinitionResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDefinitionResponse) ProtoMessage() {}

func (x *RegisterDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDefinitionResponse.ProtoReflect.Descriptor instead.
func (*RegisterDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{14}
}

type DeleteDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	NotebookFile  string                 `protobuf:"bytes,2,opt,name=notebook_file,json=notebookFile,proto3" json:"notebook_file,omitempty"`
	SceneIndex    int32                  `protobuf:"varint,3,opt,name=scene_index,json=sceneIndex,proto3" json:"scene_index,omitempty"`
	Expression    string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionRequest) Reset() {
	*x = DeleteDefinitionRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionRequest) ProtoMessage() {}

func (x *DeleteDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDefinitionRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *DeleteDefinitionRequest) GetNotebookFile() string {
	if x != nil {
		return x.NotebookFile
	}
	return ""
}

func (x *DeleteDefinitionRequest) GetSceneIndex() int32 {
	if x != nil {
		return x.SceneIndex
	}
	return 0
}

func (x *DeleteDefinitionRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type DeleteDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDefinitionResponse) Reset() {
	*x = DeleteDefinitionResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDefinitionResponse) ProtoMessage() {}

func (x *DeleteDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{16}
}

// Etymology Notebook
type EtymologyOriginPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Meaning       string                 `protobuf:"bytes,4,opt,name=meaning,proto3" json:"meaning,omitempty"`
	WordCount     int32                  `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtymologyOriginPart) Reset() {
	*x = EtymologyOriginPart{}
	mi := &file_api_v1_notebook_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtymologyOriginPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtymologyOriginPart) ProtoMessage() {}

func (x *EtymologyOriginPart) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtymologyOriginPart.ProtoReflect.Descriptor instead.
func (*EtymologyOriginPart) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{17}
}

func (x *EtymologyOriginPart) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *EtymologyOriginPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EtymologyOriginPart) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *EtymologyOriginPart) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *EtymologyOriginPart) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

type EtymologyDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Meaning       string                 `protobuf:"bytes,2,opt,name=meaning,proto3" json:"meaning,omitempty"`
	PartOfSpeech  string                 `protobuf:"bytes,3,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	OriginParts   []*EtymologyOriginPart `protobuf:"bytes,5,rep,name=origin_parts,json=originParts,proto3" json:"origin_parts,omitempty"`
	NotebookName  string                 `protobuf:"bytes,6,opt,name=notebook_name,json=notebookName,proto3" json:"notebook_name,omitempty"`
	Examples      []string               `protobuf:"bytes,7,rep,name=examples,proto3" json:"examples,omitempty"`
	Contexts      []string               `protobuf:"bytes,8,rep,name=contexts,proto3" json:"contexts,omitempty"` // statements or conversations from the source scene
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtymologyDefinition) Reset() {
	*x = EtymologyDefinition{}
	mi := &file_api_v1_notebook_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtymologyDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtymologyDefinition) ProtoMessage() {}

func (x *EtymologyDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtymologyDefinition.ProtoReflect.Descriptor instead.
func (*EtymologyDefinition) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{18}
}

func (x *EtymologyDefinition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *EtymologyDefinition) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *EtymologyDefinition) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *EtymologyDefinition) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *EtymologyDefinition) GetOriginParts() []*EtymologyOriginPart {
	if x != nil {
		return x.OriginParts
	}
	return nil
}

func (x *EtymologyDefinition) GetNotebookName() string {
	if x != nil {
		return x.NotebookName
	}
	return ""
}

func (x *EtymologyDefinition) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *EtymologyDefinition) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type EtymologyMeaningGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meaning       string                 `protobuf:"bytes,1,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Origins       []*EtymologyOriginPart `protobuf:"bytes,2,rep,name=origins,proto3" json:"origins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtymologyMeaningGroup) Reset() {
	*x = EtymologyMeaningGroup{}
	mi := &file_api_v1_notebook_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtymologyMeaningGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtymologyMeaningGroup) ProtoMessage() {}

func (x *EtymologyMeaningGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtymologyMeaningGroup.ProtoReflect.Descriptor instead.
func (*EtymologyMeaningGroup) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{19}
}

func (x *EtymologyMeaningGroup) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *EtymologyMeaningGroup) GetOrigins() []*EtymologyOriginPart {
	if x != nil {
		return x.Origins
	}
	return nil
}

type GetEtymologyNotebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtymologyNotebookRequest) Reset() {
	*x = GetEtymologyNotebookRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtymologyNotebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtymologyNotebookRequest) ProtoMessage() {}

func (x *GetEtymologyNotebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtymologyNotebookRequest.ProtoReflect.Descriptor instead.
func (*GetEtymologyNotebookRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{20}
}

func (x *GetEtymologyNotebookRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

type GetEtymologyNotebookResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Origins         []*EtymologyOriginPart   `protobuf:"bytes,1,rep,name=origins,proto3" json:"origins,omitempty"`
	Definitions     []*EtymologyDefinition   `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	MeaningGroups   []*EtymologyMeaningGroup `protobuf:"bytes,3,rep,name=meaning_groups,json=meaningGroups,proto3" json:"meaning_groups,omitempty"`
	OriginCount     int32                    `protobuf:"varint,4,opt,name=origin_count,json=originCount,proto3" json:"origin_count,omitempty"`
	DefinitionCount int32                    `protobuf:"varint,5,opt,name=definition_count,json=definitionCount,proto3" json:"definition_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetEtymologyNotebookResponse) Reset() {
	*x = GetEtymologyNotebookResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtymologyNotebookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtymologyNotebookResponse) ProtoMessage() {}

func (x *GetEtymologyNotebookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtymologyNotebookResponse.ProtoReflect.Descriptor instead.
func (*GetEtymologyNotebookResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{21}
}

func (x *GetEtymologyNotebookResponse) GetOrigins() []*EtymologyOriginPart {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *GetEtymologyNotebookResponse) GetDefinitions() []*EtymologyDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *GetEtymologyNotebookResponse) GetMeaningGroups() []*EtymologyMeaningGroup {
	if x != nil {
		return x.MeaningGroups
	}
	return nil
}

func (x *GetEtymologyNotebookResponse) GetOriginCount() int32 {
	if x != nil {
		return x.OriginCount
	}
	return 0
}

func (x *GetEtymologyNotebookResponse) GetDefinitionCount() int32 {
	if x != nil {
		return x.DefinitionCount
	}
	return 0
}

var File_api_v1_notebook_proto protoreflect.FileDescriptor

const file_api_v1_notebook_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/notebook.proto\x12\x06api.v1\x1a\x1bbuf/validate/validate.proto\"D\n" +
	"\x18GetNotebookDetailRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\"\xa8\x01\n" +
	"\x19GetNotebookDetailResponse\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\tR\n" +
	"notebookId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\astories\x18\x03 \x03(\v2\x12.api.v1.StoryEntryR\astories\x12(\n" +
	"\x10total_word_count\x18\x04 \x01(\x05R\x0etotalWordCount\"\x95\x01\n" +
	"\n" +
	"StoryEntry\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.api.v1.StoryMetadataR\bmetadata\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12*\n" +
	"\x06scenes\x18\x04 \x03(\v2\x12.api.v1.StorySceneR\x06scenes\"Y\n" +
	"\rStoryMetadata\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12\x16\n" +
	"\x06season\x18\x02 \x01(\x05R\x06season\x12\x18\n" +
	"\aepisode\x18\x03 \x01(\x05R\aepisode\"\xb6\x01\n" +
	"\n" +
	"StoryScene\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12:\n" +
	"\rconversations\x18\x02 \x03(\v2\x14.api.v1.ConversationR\rconversations\x126\n" +
	"\vdefinitions\x18\x03 \x03(\v2\x14.api.v1.NotebookWordR\vdefinitions\x12\x1e\n" +
	"\n" +
	"statements\x18\x05 \x03(\tR\n" +
	"statements\">\n" +
	"\fConversation\x12\x18\n" +
	"\aspeaker\x18\x01 \x01(\tR\aspeaker\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\"\xd5\x03\n" +
	"\fNotebookWord\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12\x18\n" +
	"\ameaning\x18\x03 \x01(\tR\ameaning\x12$\n" +
	"\x0epart_of_speech\x18\x04 \x01(\tR\fpartOfSpeech\x12$\n" +
	"\rpronunciation\x18\x05 \x01(\tR\rpronunciation\x12\x1a\n" +
	"\bexamples\x18\x06 \x03(\tR\bexamples\x12\x1a\n" +
	"\bsynonyms\x18\a \x03(\tR\bsynonyms\x12\x1a\n" +
	"\bantonyms\x18\b \x03(\tR\bantonyms\x12'\n" +
	"\x0flearning_status\x18\t \x01(\tR\x0elearningStatus\x12;\n" +
	"\flearned_logs\x18\n" +
	" \x03(\v2\x18.api.v1.LearningLogEntryR\vlearnedLogs\x12(\n" +
	"\x10next_review_date\x18\f \x01(\tR\x0enextReviewDate\x12\x16\n" +
	"\x06origin\x18\r \x01(\tR\x06origin\x12\x1d\n" +
	"\n" +
	"is_skipped\x18\x0e \x01(\bR\tisSkippedJ\x04\b\v\x10\f\"\xcf\x01\n" +
	"\x10LearningLogEntry\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"learned_at\x18\x02 \x01(\tR\tlearnedAt\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x03R\x0eresponseTimeMs\x12\x1b\n" +
	"\tquiz_type\x18\x05 \x01(\tR\bquizType\x12#\n" +
	"\rinterval_days\x18\x06 \x01(\x05R\fintervalDays\"D\n" +
	"\x18ExportNotebookPDFRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\"X\n" +
	"\x19ExportNotebookPDFResponse\x12\x1f\n" +
	"\vpdf_content\x18\x01 \x01(\fR\n" +
	"pdfContent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"k\n" +
	"\x11LookupWordRequest\x12\x1b\n" +
	"\x04word\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04word\x12\x1f\n" +
	"\vnotebook_id\x18\x02 \x01(\tR\n" +
	"notebookId\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"\xe8\x01\n" +
	"\x0eWordDefinition\x12$\n" +
	"\x0epart_of_speech\x18\x01 \x01(\tR\fpartOfSpeech\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12\x1a\n" +
	"\bexamples\x18\x03 \x03(\tR\bexamples\x12\x1a\n" +
	"\bsynonyms\x18\x04 \x03(\tR\bsynonyms\x12$\n" +
	"\rpronunciation\x18\x05 \x01(\tR\rpronunciation\x12\x1a\n" +
	"\bantonyms\x18\x06 \x03(\tR\bantonyms\x12\x16\n" +
	"\x06origin\x18\a \x01(\tR\x06origin\"z\n" +
	"\x12LookupWordResponse\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x128\n" +
	"\vdefinitions\x18\x02 \x03(\v2\x16.api.v1.WordDefinitionR\vdefinitions\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\x99\x02\n" +
	"\x19RegisterDefinitionRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\x12#\n" +
	"\rnotebook_file\x18\x02 \x01(\tR\fnotebookFile\x12\x1f\n" +
	"\vscene_index\x18\x03 \x01(\x05R\n" +
	"sceneIndex\x12'\n" +
	"\n" +
	"expression\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"expression\x12!\n" +
	"\ameaning\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\ameaning\x12$\n" +
	"\x0epart_of_speech\x18\x06 \x01(\tR\fpartOfSpeech\x12\x1a\n" +
	"\bexamples\x18\a \x03(\tR\bexamples\"\x1c\n" +
	"\x1aRegisterDefinitionResponse\"\xb2\x01\n" +
	"\x17DeleteDefinitionRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\x12#\n" +
	"\rnotebook_file\x18\x02 \x01(\tR\fnotebookFile\x12\x1f\n" +
	"\vscene_index\x18\x03 \x01(\x05R\n" +
	"sceneIndex\x12'\n" +
	"\n" +
	"expression\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"expression\"\x1a\n" +
	"\x18DeleteDefinitionResponse\"\x96\x01\n" +
	"\x13EtymologyOriginPart\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\ameaning\x18\x04 \x01(\tR\ameaning\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05R\twordCount\"\xa6\x02\n" +
	"\x13EtymologyDefinition\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x18\n" +
	"\ameaning\x18\x02 \x01(\tR\ameaning\x12$\n" +
	"\x0epart_of_speech\x18\x03 \x01(\tR\fpartOfSpeech\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12>\n" +
	"\forigin_parts\x18\x05 \x03(\v2\x1b.api.v1.EtymologyOriginPartR\voriginParts\x12#\n" +
	"\rnotebook_name\x18\x06 \x01(\tR\fnotebookName\x12\x1a\n" +
	"\bexamples\x18\a \x03(\tR\bexamples\x12\x1a\n" +
	"\bcontexts\x18\b \x03(\tR\bcontexts\"h\n" +
	"\x15EtymologyMeaningGroup\x12\x18\n" +
	"\ameaning\x18\x01 \x01(\tR\ameaning\x125\n" +
	"\aorigins\x18\x02 \x03(\v2\x1b.api.v1.EtymologyOriginPartR\aorigins\"G\n" +
	"\x1bGetEtymologyNotebookRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\"\xa8\x02\n" +
	"\x1cGetEtymologyNotebookResponse\x125\n" +
	"\aorigins\x18\x01 \x03(\v2\x1b.api.v1.EtymologyOriginPartR\aorigins\x12=\n" +
	"\vdefinitions\x18\x02 \x03(\v2\x1b.api.v1.EtymologyDefinitionR\vdefinitions\x12D\n" +
	"\x0emeaning_groups\x18\x03 \x03(\v2\x1d.api.v1.EtymologyMeaningGroupR\rmeaningGroups\x12!\n" +
	"\forigin_count\x18\x04 \x01(\x05R\voriginCount\x12)\n" +
	"\x10definition_count\x18\x05 \x01(\x05R\x0fdefinitionCount2\xa1\x04\n" +
	"\x0fNotebookService\x12X\n" +
	"\x11GetNotebookDetail\x12 .api.v1.GetNotebookDetailRequest\x1a!.api.v1.GetNotebookDetailResponse\x12X\n" +
	"\x11ExportNotebookPDF\x12 .api.v1.ExportNotebookPDFRequest\x1a!.api.v1.ExportNotebookPDFResponse\x12C\n" +
	"\n" +
	"LookupWord\x12\x19.api.v1.LookupWordRequest\x1a\x1a.api.v1.LookupWordResponse\x12[\n" +
	"\x12RegisterDefinition\x12!.api.v1.RegisterDefinitionRequest\x1a\".api.v1.RegisterDefinitionResponse\x12U\n" +
	"\x10DeleteDefinition\x12\x1f.api.v1.DeleteDefinitionRequest\x1a .api.v1.DeleteDefinitionResponse\x12a\n" +
	"\x14GetEtymologyNotebook\x12#.api.v1.GetEtymologyNotebookRequest\x1a$.api.v1.GetEtymologyNotebookResponseB8Z6github.com/at-ishikawa/langner/gen-protos/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_notebook_proto_rawDescOnce sync.Once
	file_api_v1_notebook_proto_rawDescData []byte
)

func file_api_v1_notebook_proto_rawDescGZIP() []byte {
	file_api_v1_notebook_proto_rawDescOnce.Do(func() {
		file_api_v1_notebook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_notebook_proto_rawDesc), len(file_api_v1_notebook_proto_rawDesc)))
	})
	return file_api_v1_notebook_proto_rawDescData
}

var file_api_v1_notebook_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_v1_notebook_proto_goTypes = []any{
	(*GetNotebookDetailRequest)(nil),     // 0: api.v1.GetNotebookDetailRequest
	(*GetNotebookDetailResponse)(nil),    // 1: api.v1.GetNotebookDetailResponse
	(*StoryEntry)(nil),                   // 2: api.v1.StoryEntry
	(*StoryMetadata)(nil),                // 3: api.v1.StoryMetadata
	(*StoryScene)(nil),                   // 4: api.v1.StoryScene
	(*Conversation)(nil),                 // 5: api.v1.Conversation
	(*NotebookWord)(nil),                 // 6: api.v1.NotebookWord
	(*LearningLogEntry)(nil),             // 7: api.v1.LearningLogEntry
	(*ExportNotebookPDFRequest)(nil),     // 8: api.v1.ExportNotebookPDFRequest
	(*ExportNotebookPDFResponse)(nil),    // 9: api.v1.ExportNotebookPDFResponse
	(*LookupWordRequest)(nil),            // 10: api.v1.LookupWordRequest
	(*WordDefinition)(nil),               // 11: api.v1.WordDefinition
	(*LookupWordResponse)(nil),           // 12: api.v1.LookupWordResponse
	(*RegisterDefinitionRequest)(nil),    // 13: api.v1.RegisterDefinitionRequest
	(*RegisterDefinitionResponse)(nil),   // 14: api.v1.RegisterDefinitionResponse
	(*DeleteDefinitionRequest)(nil),      // 15: api.v1.DeleteDefinitionRequest
	(*DeleteDefinitionResponse)(nil),     // 16: api.v1.DeleteDefinitionResponse
	(*EtymologyOriginPart)(nil),          // 17: api.v1.EtymologyOriginPart
	(*EtymologyDefinition)(nil),          // 18: api.v1.EtymologyDefinition
	(*EtymologyMeaningGroup)(nil),        // 19: api.v1.EtymologyMeaningGroup
	(*GetEtymologyNotebookRequest)(nil),  // 20: api.v1.GetEtymologyNotebookRequest
	(*GetEtymologyNotebookResponse)(nil), // 21: api.v1.GetEtymologyNotebookResponse
}
var file_api_v1_notebook_proto_depIdxs = []int32{
	2,  // 0: api.v1.GetNotebookDetailResponse.stories:type_name -> api.v1.StoryEntry
	3,  // 1: api.v1.StoryEntry.metadata:type_name -> api.v1.StoryMetadata
	4,  // 2: api.v1.StoryEntry.scenes:type_name -> api.v1.StoryScene
	5,  // 3: api.v1.StoryScene.conversations:type_name -> api.v1.Conversation
	6,  // 4: api.v1.StoryScene.definitions:type_name -> api.v1.NotebookWord
	7,  // 5: api.v1.NotebookWord.learned_logs:type_name -> api.v1.LearningLogEntry
	11, // 6: api.v1.LookupWordResponse.definitions:type_name -> api.v1.WordDefinition
	17, // 7: api.v1.EtymologyDefinition.origin_parts:type_name -> api.v1.EtymologyOriginPart
	17, // 8: api.v1.EtymologyMeaningGroup.origins:type_name -> api.v1.EtymologyOriginPart
	17, // 9: api.v1.GetEtymologyNotebookResponse.origins:type_name -> api.v1.EtymologyOriginPart
	18, // 10: api.v1.GetEtymologyNotebookResponse.definitions:type_name -> api.v1.EtymologyDefinition
	19, // 11: api.v1.GetEtymologyNotebookResponse.meaning_groups:type_name -> api.v1.EtymologyMeaningGroup
	0,  // 12: api.v1.NotebookService.GetNotebookDetail:input_type -> api.v1.GetNotebookDetailRequest
	8,  // 13: api.v1.NotebookService.ExportNotebookPDF:input_type -> api.v1.ExportNotebookPDFRequest
	10, // 14: api.v1.NotebookService.LookupWord:input_type -> api.v1.LookupWordRequest
	13, // 15: api.v1.NotebookService.RegisterDefinition:input_type -> api.v1.RegisterDefinitionRequest
	15, // 16: api.v1.NotebookService.DeleteDefinition:input_type -> api.v1.DeleteDefinitionRequest
	20, // 17: api.v1.NotebookService.GetEtymologyNotebook:input_type -> api.v1.GetEtymologyNotebookRequest
	1,  // 18: api.v1.NotebookService.GetNotebookDetail:output_type -> api.v1.GetNotebookDetailResponse
	9,  // 19: api.v1.NotebookService.ExportNotebookPDF:output_type -> api.v1.ExportNotebookPDFResponse
	12, // 20: api.v1.NotebookService.LookupWord:output_type -> api.v1.LookupWordResponse
	14, // 21: api.v1.NotebookService.RegisterDefinition:output_type -> api.v1.RegisterDefinitionResponse
	16, // 22: api.v1.NotebookService.DeleteDefinition:output_type -> api.v1.DeleteDefinitionResponse
	21, // 23: api.v1.NotebookService.GetEtymologyNotebook:output_type -> api.v1.GetEtymologyNotebookResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_v1_notebook_proto_init() }
func file_api_v1_notebook_proto_init() {
	if File_api_v1_notebook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_notebook_proto_rawDesc), len(file_api_v1_notebook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_notebook_proto_goTypes,
		DependencyIndexes: file_api_v1_notebook_proto_depIdxs,
		MessageInfos:      file_api_v1_notebook_proto_msgTypes,
	}.Build()
	File_api_v1_notebook_proto = out.File
	file_api_v1_notebook_proto_goTypes = nil
	file_api_v1_notebook_proto_depIdxs = nil
}
