// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/notebook.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNotebookDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotebookDetailRequest) Reset() {
	*x = GetNotebookDetailRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailRequest) ProtoMessage() {}

func (x *GetNotebookDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailRequest.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotebookDetailRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

type GetNotebookDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotebookId     string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stories        []*StoryEntry          `protobuf:"bytes,3,rep,name=stories,proto3" json:"stories,omitempty"`
	TotalWordCount int32                  `protobuf:"varint,4,opt,name=total_word_count,json=totalWordCount,proto3" json:"total_word_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotebookDetailResponse) Reset() {
	*x = GetNotebookDetailResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotebookDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotebookDetailResponse) ProtoMessage() {}

func (x *GetNotebookDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotebookDetailResponse.ProtoReflect.Descriptor instead.
func (*GetNotebookDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{1}
}

func (x *GetNotebookDetailResponse) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

func (x *GetNotebookDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetNotebookDetailResponse) GetStories() []*StoryEntry {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *GetNotebookDetailResponse) GetTotalWordCount() int32 {
	if x != nil {
		return x.TotalWordCount
	}
	return 0
}

type StoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Metadata      *StoryMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Scenes        []*StoryScene          `protobuf:"bytes,4,rep,name=scenes,proto3" json:"scenes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryEntry) Reset() {
	*x = StoryEntry{}
	mi := &file_api_v1_notebook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryEntry) ProtoMessage() {}

func (x *StoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryEntry.ProtoReflect.Descriptor instead.
func (*StoryEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{2}
}

func (x *StoryEntry) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *StoryEntry) GetMetadata() *StoryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoryEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *StoryEntry) GetScenes() []*StoryScene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

type StoryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	Season        int32                  `protobuf:"varint,2,opt,name=season,proto3" json:"season,omitempty"`
	Episode       int32                  `protobuf:"varint,3,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryMetadata) Reset() {
	*x = StoryMetadata{}
	mi := &file_api_v1_notebook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryMetadata) ProtoMessage() {}

func (x *StoryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryMetadata.ProtoReflect.Descriptor instead.
func (*StoryMetadata) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{3}
}

func (x *StoryMetadata) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *StoryMetadata) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *StoryMetadata) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

type StoryScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Conversations []*Conversation        `protobuf:"bytes,2,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Definitions   []*NotebookWord        `protobuf:"bytes,3,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryScene) Reset() {
	*x = StoryScene{}
	mi := &file_api_v1_notebook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryScene) ProtoMessage() {}

func (x *StoryScene) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryScene.ProtoReflect.Descriptor instead.
func (*StoryScene) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{4}
}

func (x *StoryScene) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StoryScene) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *StoryScene) GetDefinitions() []*NotebookWord {
	if x != nil {
		return x.Definitions
	}
	return nil
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speaker       string                 `protobuf:"bytes,1,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_api_v1_notebook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{5}
}

func (x *Conversation) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *Conversation) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

type NotebookWord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Expression     string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Definition     string                 `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Meaning        string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	PartOfSpeech   string                 `protobuf:"bytes,4,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Pronunciation  string                 `protobuf:"bytes,5,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	Examples       []string               `protobuf:"bytes,6,rep,name=examples,proto3" json:"examples,omitempty"`
	Synonyms       []string               `protobuf:"bytes,7,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Antonyms       []string               `protobuf:"bytes,8,rep,name=antonyms,proto3" json:"antonyms,omitempty"`
	LearningStatus string                 `protobuf:"bytes,9,opt,name=learning_status,json=learningStatus,proto3" json:"learning_status,omitempty"`
	LearnedLogs    []*LearningLogEntry    `protobuf:"bytes,10,rep,name=learned_logs,json=learnedLogs,proto3" json:"learned_logs,omitempty"`
	EasinessFactor float64                `protobuf:"fixed64,11,opt,name=easiness_factor,json=easinessFactor,proto3" json:"easiness_factor,omitempty"`
	NextReviewDate string                 `protobuf:"bytes,12,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotebookWord) Reset() {
	*x = NotebookWord{}
	mi := &file_api_v1_notebook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotebookWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotebookWord) ProtoMessage() {}

func (x *NotebookWord) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotebookWord.ProtoReflect.Descriptor instead.
func (*NotebookWord) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{6}
}

func (x *NotebookWord) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *NotebookWord) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *NotebookWord) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *NotebookWord) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *NotebookWord) GetPronunciation() string {
	if x != nil {
		return x.Pronunciation
	}
	return ""
}

func (x *NotebookWord) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *NotebookWord) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *NotebookWord) GetAntonyms() []string {
	if x != nil {
		return x.Antonyms
	}
	return nil
}

func (x *NotebookWord) GetLearningStatus() string {
	if x != nil {
		return x.LearningStatus
	}
	return ""
}

func (x *NotebookWord) GetLearnedLogs() []*LearningLogEntry {
	if x != nil {
		return x.LearnedLogs
	}
	return nil
}

func (x *NotebookWord) GetEasinessFactor() float64 {
	if x != nil {
		return x.EasinessFactor
	}
	return 0
}

func (x *NotebookWord) GetNextReviewDate() string {
	if x != nil {
		return x.NextReviewDate
	}
	return ""
}

type LearningLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	LearnedAt      string                 `protobuf:"bytes,2,opt,name=learned_at,json=learnedAt,proto3" json:"learned_at,omitempty"`
	Quality        int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	QuizType       string                 `protobuf:"bytes,5,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	IntervalDays   int32                  `protobuf:"varint,6,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LearningLogEntry) Reset() {
	*x = LearningLogEntry{}
	mi := &file_api_v1_notebook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningLogEntry) ProtoMessage() {}

func (x *LearningLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningLogEntry.ProtoReflect.Descriptor instead.
func (*LearningLogEntry) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{7}
}

func (x *LearningLogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LearningLogEntry) GetLearnedAt() string {
	if x != nil {
		return x.LearnedAt
	}
	return ""
}

func (x *LearningLogEntry) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *LearningLogEntry) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *LearningLogEntry) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *LearningLogEntry) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

type ExportNotebookPDFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotebookId    string                 `protobuf:"bytes,1,opt,name=notebook_id,json=notebookId,proto3" json:"notebook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNotebookPDFRequest) Reset() {
	*x = ExportNotebookPDFRequest{}
	mi := &file_api_v1_notebook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFRequest) ProtoMessage() {}

func (x *ExportNotebookPDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFRequest.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{8}
}

func (x *ExportNotebookPDFRequest) GetNotebookId() string {
	if x != nil {
		return x.NotebookId
	}
	return ""
}

type ExportNotebookPDFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PdfContent    []byte                 `protobuf:"bytes,1,opt,name=pdf_content,json=pdfContent,proto3" json:"pdf_content,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNotebookPDFResponse) Reset() {
	*x = ExportNotebookPDFResponse{}
	mi := &file_api_v1_notebook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNotebookPDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNotebookPDFResponse) ProtoMessage() {}

func (x *ExportNotebookPDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_notebook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNotebookPDFResponse.ProtoReflect.Descriptor instead.
func (*ExportNotebookPDFResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_notebook_proto_rawDescGZIP(), []int{9}
}

func (x *ExportNotebookPDFResponse) GetPdfContent() []byte {
	if x != nil {
		return x.PdfContent
	}
	return nil
}

func (x *ExportNotebookPDFResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_api_v1_notebook_proto protoreflect.FileDescriptor

const file_api_v1_notebook_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/notebook.proto\x12\x06api.v1\x1a\x1bbuf/validate/validate.proto\"D\n" +
	"\x18GetNotebookDetailRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\"\xa8\x01\n" +
	"\x19GetNotebookDetailResponse\x12\x1f\n" +
	"\vnotebook_id\x18\x01 \x01(\tR\n" +
	"notebookId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\astories\x18\x03 \x03(\v2\x12.api.v1.StoryEntryR\astories\x12(\n" +
	"\x10total_word_count\x18\x04 \x01(\x05R\x0etotalWordCount\"\x95\x01\n" +
	"\n" +
	"StoryEntry\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.api.v1.StoryMetadataR\bmetadata\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12*\n" +
	"\x06scenes\x18\x04 \x03(\v2\x12.api.v1.StorySceneR\x06scenes\"Y\n" +
	"\rStoryMetadata\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12\x16\n" +
	"\x06season\x18\x02 \x01(\x05R\x06season\x12\x18\n" +
	"\aepisode\x18\x03 \x01(\x05R\aepisode\"\x96\x01\n" +
	"\n" +
	"StoryScene\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12:\n" +
	"\rconversations\x18\x02 \x03(\v2\x14.api.v1.ConversationR\rconversations\x126\n" +
	"\vdefinitions\x18\x03 \x03(\v2\x14.api.v1.NotebookWordR\vdefinitions\">\n" +
	"\fConversation\x12\x18\n" +
	"\aspeaker\x18\x01 \x01(\tR\aspeaker\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\"\xc1\x03\n" +
	"\fNotebookWord\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1e\n" +
	"\n" +
	"definition\x18\x02 \x01(\tR\n" +
	"definition\x12\x18\n" +
	"\ameaning\x18\x03 \x01(\tR\ameaning\x12$\n" +
	"\x0epart_of_speech\x18\x04 \x01(\tR\fpartOfSpeech\x12$\n" +
	"\rpronunciation\x18\x05 \x01(\tR\rpronunciation\x12\x1a\n" +
	"\bexamples\x18\x06 \x03(\tR\bexamples\x12\x1a\n" +
	"\bsynonyms\x18\a \x03(\tR\bsynonyms\x12\x1a\n" +
	"\bantonyms\x18\b \x03(\tR\bantonyms\x12'\n" +
	"\x0flearning_status\x18\t \x01(\tR\x0elearningStatus\x12;\n" +
	"\flearned_logs\x18\n" +
	" \x03(\v2\x18.api.v1.LearningLogEntryR\vlearnedLogs\x12'\n" +
	"\x0feasiness_factor\x18\v \x01(\x01R\x0eeasinessFactor\x12(\n" +
	"\x10next_review_date\x18\f \x01(\tR\x0enextReviewDate\"\xcf\x01\n" +
	"\x10LearningLogEntry\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"learned_at\x18\x02 \x01(\tR\tlearnedAt\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x03R\x0eresponseTimeMs\x12\x1b\n" +
	"\tquiz_type\x18\x05 \x01(\tR\bquizType\x12#\n" +
	"\rinterval_days\x18\x06 \x01(\x05R\fintervalDays\"D\n" +
	"\x18ExportNotebookPDFRequest\x12(\n" +
	"\vnotebook_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"notebookId\"X\n" +
	"\x19ExportNotebookPDFResponse\x12\x1f\n" +
	"\vpdf_content\x18\x01 \x01(\fR\n" +
	"pdfContent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2\xc5\x01\n" +
	"\x0fNotebookService\x12X\n" +
	"\x11GetNotebookDetail\x12 .api.v1.GetNotebookDetailRequest\x1a!.api.v1.GetNotebookDetailResponse\x12X\n" +
	"\x11ExportNotebookPDF\x12 .api.v1.ExportNotebookPDFRequest\x1a!.api.v1.ExportNotebookPDFResponseB8Z6github.com/at-ishikawa/langner/gen-protos/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_notebook_proto_rawDescOnce sync.Once
	file_api_v1_notebook_proto_rawDescData []byte
)

func file_api_v1_notebook_proto_rawDescGZIP() []byte {
	file_api_v1_notebook_proto_rawDescOnce.Do(func() {
		file_api_v1_notebook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_notebook_proto_rawDesc), len(file_api_v1_notebook_proto_rawDesc)))
	})
	return file_api_v1_notebook_proto_rawDescData
}

var file_api_v1_notebook_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_notebook_proto_goTypes = []any{
	(*GetNotebookDetailRequest)(nil),  // 0: api.v1.GetNotebookDetailRequest
	(*GetNotebookDetailResponse)(nil), // 1: api.v1.GetNotebookDetailResponse
	(*StoryEntry)(nil),                // 2: api.v1.StoryEntry
	(*StoryMetadata)(nil),             // 3: api.v1.StoryMetadata
	(*StoryScene)(nil),                // 4: api.v1.StoryScene
	(*Conversation)(nil),              // 5: api.v1.Conversation
	(*NotebookWord)(nil),              // 6: api.v1.NotebookWord
	(*LearningLogEntry)(nil),          // 7: api.v1.LearningLogEntry
	(*ExportNotebookPDFRequest)(nil),  // 8: api.v1.ExportNotebookPDFRequest
	(*ExportNotebookPDFResponse)(nil), // 9: api.v1.ExportNotebookPDFResponse
}
var file_api_v1_notebook_proto_depIdxs = []int32{
	2, // 0: api.v1.GetNotebookDetailResponse.stories:type_name -> api.v1.StoryEntry
	3, // 1: api.v1.StoryEntry.metadata:type_name -> api.v1.StoryMetadata
	4, // 2: api.v1.StoryEntry.scenes:type_name -> api.v1.StoryScene
	5, // 3: api.v1.StoryScene.conversations:type_name -> api.v1.Conversation
	6, // 4: api.v1.StoryScene.definitions:type_name -> api.v1.NotebookWord
	7, // 5: api.v1.NotebookWord.learned_logs:type_name -> api.v1.LearningLogEntry
	0, // 6: api.v1.NotebookService.GetNotebookDetail:input_type -> api.v1.GetNotebookDetailRequest
	8, // 7: api.v1.NotebookService.ExportNotebookPDF:input_type -> api.v1.ExportNotebookPDFRequest
	1, // 8: api.v1.NotebookService.GetNotebookDetail:output_type -> api.v1.GetNotebookDetailResponse
	9, // 9: api.v1.NotebookService.ExportNotebookPDF:output_type -> api.v1.ExportNotebookPDFResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_notebook_proto_init() }
func file_api_v1_notebook_proto_init() {
	if File_api_v1_notebook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_notebook_proto_rawDesc), len(file_api_v1_notebook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_notebook_proto_goTypes,
		DependencyIndexes: file_api_v1_notebook_proto_depIdxs,
		MessageInfos:      file_api_v1_notebook_proto_msgTypes,
	}.Build()
	File_api_v1_notebook_proto = out.File
	file_api_v1_notebook_proto_goTypes = nil
	file_api_v1_notebook_proto_depIdxs = nil
}
