-- The importer treats (note_id, notebook_type, notebook_id, group,
-- subgroup) as the identity of one notebook_notes reference — a word
-- can legitimately appear in multiple scenes of the same story. The
-- original migration-001 unique key was only four columns (dropping
-- subgroup), so those multi-scene references collided at the DB
-- layer and either failed the insert (Postgres 23505) or silently
-- lost rows via ON CONFLICT DO NOTHING. Widen the key to match the
-- five-field identity the importer uses so sync-db's clear-and-
-- reimport round-trip stays lossless (validate-db compared source
-- YAML definition count 767 against exported 766 — off by exactly
-- one row on Word Power Made Easy where an expression showed up in
-- two scenes of the same session).

-- The autogenerated constraint name from migration 001 depends on the
-- column list; drop it via IF EXISTS both under its natural name and
-- as a fallback in case a redeploy renamed it.
ALTER TABLE notebook_notes
    DROP CONSTRAINT IF EXISTS notebook_notes_note_id_notebook_type_notebook_id_group_key;

ALTER TABLE notebook_notes
    ADD CONSTRAINT notebook_notes_note_id_notebook_type_notebook_id_group_subgroup_key
    UNIQUE (note_id, notebook_type, notebook_id, "group", subgroup);
